# LastFM — audit ketat dan eksperimen utama

> Salinan publik ini mempertahankan kode dan output eksperimen yang tersimpan. Preview baris mentah disembunyikan dari output cell agar data tidak ikut didistribusikan. Dataset mentah, file sequence/timestamp, dan checkpoint tidak disertakan. Sel training akan menjalankan training penuh jika dijalankan ulang; jangan memilih “Run all” hanya untuk membaca hasil.

> Sel audit tambahan setelah bagian hasil utama belum dieksekusi pada sumber notebook; gunakan hanya output yang memang tersimpan sebagai bukti.

# Reproduksi BSARec LastFM — versi audit ketat

**Penting untuk melanjutkan run yang sudah ada:** jangan gunakan “Run All” dan jangan jalankan sel training pada bagian E/F. Jalankan hanya sel tambahan setelah G.1, mulai dari arsip Drive, agar enam hasil training yang sudah tersimpan tidak terlatih ulang.


Notebook ini mempertahankan enam run yang sudah selesai dan menambahkan audit preprocessing independen: urutan sequence dan mapping ID dibandingkan langsung dengan prosedur LastFM S3Rec yang dirujuk, invariant 5-core diperiksa, serta hash data dan mapping disimpan. Audit baru tidak melatih ulang model.

Konfigurasi BSARec mengikuti Table 6 paper LastFM: `alpha=0.9`, `c=3`, satu attention head, dan `lr=0.001`. SASRec dijalankan sebagai baseline dengan data, split, dan evaluasi yang sama. Selisih paper di bawah adalah deskriptif: paper melaporkan satu nilai, sedangkan notebook ini merata-ratakan tiga seed.

**Catatan waktu:** `user_taggedartists-timestamps.dat` mencatat waktu tag artis, bukan waktu scrobble/mendengarkan lagu. BSARec/SASRec standar tidak memakai timestamp. Berkas waktu dan gap disimpan sebagai metadata analisis.

**Batas reproduksibilitas:** run training yang sudah terekam tidak mencatat commit Git dan hash sumber secara eksplisit. Audit manifest merekam commit yang tersedia saat sel audit dijalankan; itu membuktikan run lama hanya jika dijalankan pada runtime/repo yang sama.

## A. Setup Colab dan kode resmi

In [1]:
from pathlib import Path
import os, sys, subprocess, zipfile, urllib.request
import torch

ROOT = Path('/content')
REPO = ROOT / 'BSARec'
if not REPO.exists():
    subprocess.run(['git', 'clone', 'https://github.com/yehjin-shin/BSARec.git', str(REPO)], check=True)
SRC = REPO / 'src'
assert (SRC / 'main.py').exists(), f'main.py tidak ditemukan di {SRC}'
os.chdir(SRC)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'scipy', 'tqdm', 'pandas'], check=True)
GPU_AVAILABLE = torch.cuda.is_available()
print('Repo:', REPO)
print('GPU tersedia:', GPU_AVAILABLE)
if GPU_AVAILABLE:
    print('GPU:', torch.cuda.get_device_name(0))
else:
    print('Runtime tanpa GPU; training tetap berjalan, tetapi bisa lebih lambat.')

Repo: /content/BSARec
GPU tersedia: True
GPU: Tesla T4

## B. Unduh dan periksa data HetRec Last.fm 2K

In [ ]:
DATA_DIR = ROOT / 'lastfm_raw'
DATA_DIR.mkdir(parents=True, exist_ok=True)
ZIP_PATH = DATA_DIR / 'hetrec2011-lastfm-2k.zip'
DATA_URL = 'https://files.grouplens.org/datasets/hetrec2011/hetrec2011-lastfm-2k.zip'
if not ZIP_PATH.exists():
    urllib.request.urlretrieve(DATA_URL, ZIP_PATH)
with zipfile.ZipFile(ZIP_PATH) as zf:
    zf.extractall(DATA_DIR)
raw_matches = list(DATA_DIR.rglob('user_taggedartists-timestamps.dat'))
assert raw_matches, 'user_taggedartists-timestamps.dat tidak ditemukan dalam arsip.'
RAW_PATH = raw_matches[0]
print('Raw file:', RAW_PATH)
print('Contoh baris:', RAW_PATH.read_text(encoding='utf-8', errors='replace').splitlines()[:3])

## C. Preprocessing berpasangan item dan timestamp

Mengikuti prosedur LastFM yang dirujuk BSARec/S3Rec: simpan kemunculan pertama setiap pasangan user-artis dalam urutan file, urutkan sequence per user berdasarkan timestamp (sort stabil untuk tie), terapkan iterative 5-core, lalu petakan ID berdasarkan urutan kemunculan. Ini menjaga item dan timestamp tetap berpasangan saat deduplikasi dan filtering.

`LastFM.txt` adalah file input model. `LastFM_time.txt` berisi timestamp sumber dalam ms pada posisi item yang sama. `LastFM_gap.txt` berisi gap antar-event dalam ms; elemen pertama tiap user bernilai 0 karena tidak ada event sebelumnya.

In [3]:
import pandas as pd
from collections import Counter, OrderedDict

raw = pd.read_csv(RAW_PATH, sep='\t')
raw.columns = [str(c).strip() for c in raw.columns]
assert {'userID', 'artistID', 'timestamp'}.issubset(raw.columns), raw.columns.tolist()
raw = raw[['userID', 'artistID', 'timestamp']].dropna().copy()
raw['timestamp'] = pd.to_numeric(raw['timestamp'], errors='coerce')
raw = raw.dropna(subset=['timestamp']).copy()
raw['timestamp'] = raw['timestamp'].astype('int64')

# Deduplikasi pasangan user-artis sesuai kemunculan pertama pada file sumber.
user_events = OrderedDict()
seen_artists = {}
for user, artist, timestamp in raw.itertuples(index=False, name=None):
    if user not in user_events:
        user_events[user] = []
        seen_artists[user] = set()
    if artist not in seen_artists[user]:
        user_events[user].append((artist, int(timestamp)))
        seen_artists[user].add(artist)

# Sort stabil per user: timestamp tie mempertahankan urutan file sumber.
for user in user_events:
    user_events[user].sort(key=lambda pair: pair[1])

# Iterative user-5-core dan artist-5-core, sambil mempertahankan timestamp.
while True:
    interactions_before = sum(len(seq) for seq in user_events.values())
    user_events = OrderedDict(
        (u, seq) for u, seq in user_events.items() if len(seq) >= 5
    )
    artist_counts = Counter(
        artist for seq in user_events.values() for artist, _ in seq
    )
    user_events = OrderedDict(
        (u, [(artist, ts) for artist, ts in seq if artist_counts[artist] >= 5])
        for u, seq in user_events.items()
    )
    user_events = OrderedDict(
        (u, seq) for u, seq in user_events.items() if len(seq) >= 5
    )
    interactions_after = sum(len(seq) for seq in user_events.values())
    if interactions_after == interactions_before:
        break

# Pemetaan 1-based berdasarkan urutan kemunculan, bukan urutan alfabetis.
user2id = {user: i + 1 for i, user in enumerate(user_events)}
artist2id = {}
item_sequences = OrderedDict()
time_sequences = OrderedDict()
gap_sequences = OrderedDict()

for user, pairs in user_events.items():
    uid = user2id[user]
    item_ids, timestamps = [], []
    for artist, timestamp in pairs:
        if artist not in artist2id:
            artist2id[artist] = len(artist2id) + 1
        item_ids.append(artist2id[artist])
        timestamps.append(timestamp)
    gaps = [0] + [timestamps[i] - timestamps[i - 1] for i in range(1, len(timestamps))]
    item_sequences[uid] = item_ids
    time_sequences[uid] = timestamps
    gap_sequences[uid] = gaps

DATA_OUT = SRC / 'data'
DATA_OUT.mkdir(parents=True, exist_ok=True)
ITEM_FILE = DATA_OUT / 'LastFM.txt'
TIME_FILE = DATA_OUT / 'LastFM_time.txt'
GAP_FILE = DATA_OUT / 'LastFM_gap.txt'

def write_parallel_files(item_path, time_path, gap_path):
    with item_path.open('w', encoding='utf-8') as f_item, \
         time_path.open('w', encoding='utf-8') as f_time, \
         gap_path.open('w', encoding='utf-8') as f_gap:
        for uid, items in item_sequences.items():
            times = time_sequences[uid]
            gaps = gap_sequences[uid]
            assert len(items) == len(times) == len(gaps)
            f_item.write(str(uid) + ' ' + ' '.join(map(str, items)) + '\n')
            f_time.write(str(uid) + ' ' + ' '.join(map(str, times)) + '\n')
            f_gap.write(str(uid) + ' ' + ' '.join(map(str, gaps)) + '\n')

write_parallel_files(ITEM_FILE, TIME_FILE, GAP_FILE)

n_users = len(user2id)
n_artists = len(artist2id)
n_interactions = sum(map(len, item_sequences.values()))
seq_lengths = [len(seq) for seq in item_sequences.values()]
print(f'Users: {n_users:,} | Artists: {n_artists:,} | Interactions: {n_interactions:,}')
print(f'Average sequence: {sum(seq_lengths)/len(seq_lengths):.2f} | min: {min(seq_lengths)} | max: {max(seq_lengths)}')
print('Model input:', ITEM_FILE)
print('Aligned timestamps:', TIME_FILE)
print('Aligned gaps:', GAP_FILE)
assert (n_users, n_artists, n_interactions) == (1090, 3646, 52551), 'Stats differ from BSARec Table 5; stop and inspect preprocessing.'

Users: 1,090 | Artists: 3,646 | Interactions: 52,551
Average sequence: 48.21 | min: 5 | max: 899
Model input: /content/BSARec/src/data/LastFM.txt
Aligned timestamps: /content/BSARec/src/data/LastFM_time.txt
Aligned gaps: /content/BSARec/src/data/LastFM_gap.txt

## D. Validasi file, alignment, dan timestamp

In [4]:
item_lines = ITEM_FILE.read_text(encoding='utf-8').splitlines()
time_lines = TIME_FILE.read_text(encoding='utf-8').splitlines()
gap_lines = GAP_FILE.read_text(encoding='utf-8').splitlines()
assert len(item_lines) == len(time_lines) == len(gap_lines) == n_users

for item_line, time_line, gap_line in zip(item_lines, time_lines, gap_lines):
    item_parts = item_line.split()
    time_parts = time_line.split()
    gap_parts = gap_line.split()
    assert item_parts[0] == time_parts[0] == gap_parts[0]
    assert len(item_parts[1:]) == len(time_parts[1:]) == len(gap_parts[1:])

# Timestamp sumber adalah ms. Konversi ms -> hari dengan 86,400,000.
import numpy as np
all_gaps_ms = np.concatenate([
    np.diff(np.asarray(times, dtype=np.int64))
    for times in time_sequences.values()
    if len(times) > 1
])
print('Item/time/gap row alignment: PASSED')
print('Gap <= 0 (ms):', int((all_gaps_ms <= 0).sum()))
print('Median positive gap (days):', float(np.median(all_gaps_ms[all_gaps_ms > 0]) / 86_400_000))
print('P90 positive gap (days):', float(np.percentile(all_gaps_ms[all_gaps_ms > 0], 90) / 86_400_000))
print('Interpretation: tag-event gaps, not listening/scrobble gaps.')

Item/time/gap row alignment: PASSED
Gap <= 0 (ms): 44273
Median positive gap (days): 31.0
P90 positive gap (days): 153.04166666666666
Interpretation: tag-event gaps, not listening/scrobble gaps.

## D.1 Audit ketat terhadap preprocessing rujukan

Sel ini merekonstruksi langkah LastFM dari `data_process.py` S3Rec (deduplikasi artis per user pada kemunculan pertama, stable sort timestamp, iterative 5-core, lalu ID 1-based menurut urutan traversal). Hasilnya dibandingkan **per user, per item, dan per ID**, bukan hanya statistik agregat. Sel ini juga mengecek monotonic timestamp, duplikasi, 5-core, alignment item/time/gap, dan menyimpan mapping serta SHA-256.

Jika assertion gagal, jangan pakai metrik untuk klaim reproduksi sebelum penyebabnya ditelusuri. Sel ini hanya memproses data dan menulis manifest; tidak menjalankan training.

In [5]:
from collections import Counter, OrderedDict
from copy import deepcopy
from importlib.metadata import version, PackageNotFoundError
import hashlib, json, platform, subprocess
import numpy as np

# Bangun ulang dari baris sumber sebagai string, seperti parser referensi.
ref_raw = pd.read_csv(
    RAW_PATH, sep='\t', dtype={'userID': str, 'artistID': str, 'tagID': str, 'timestamp': str}
)
assert {'userID', 'artistID', 'timestamp'}.issubset(ref_raw.columns)
ref_pairs = OrderedDict()
ref_seen = {}
for user, artist, timestamp in ref_raw[['userID', 'artistID', 'timestamp']].itertuples(index=False, name=None):
    if user not in ref_pairs:
        ref_pairs[user] = []
        ref_seen[user] = set()
    if artist not in ref_seen[user]:
        ref_pairs[user].append((artist, int(timestamp)))
        ref_seen[user].add(artist)
for user in ref_pairs:
    ref_pairs[user].sort(key=lambda pair: pair[1])  # Python sort stabil; tie menjaga urutan file

ref_user_items = OrderedDict((u, [artist for artist, _ in pairs]) for u, pairs in ref_pairs.items())

def _reference_core_counts(user_items):
    user_counts = Counter()
    item_counts = Counter()
    for user, items in user_items.items():
        for item in items:
            user_counts[user] += 1
            item_counts[item] += 1
    core_ok = all(n >= 5 for n in user_counts.values()) and all(n >= 5 for n in item_counts.values())
    return user_counts, item_counts, core_ok

def _reference_filter_kcore(user_items):
    # Menyalin urutan pruning filter_Kcore pada data_process.py rujukan.
    user_items = deepcopy(user_items)
    user_counts, item_counts, core_ok = _reference_core_counts(user_items)
    while not core_ok:
        for user, _ in user_counts.items():
            if user_counts[user] < 5:
                user_items.pop(user)
            else:
                for item in user_items[user]:
                    if item_counts[item] < 5:
                        user_items[user].remove(item)
        user_counts, item_counts, core_ok = _reference_core_counts(user_items)
    return user_items

ref_user_items = _reference_filter_kcore(ref_user_items)
ref_user2id, ref_artist2id, ref_sequences = {}, {}, OrderedDict()
for user, artists in ref_user_items.items():
    if user not in ref_user2id:
        ref_user2id[user] = len(ref_user2id) + 1
    uid = ref_user2id[user]
    ids = []
    for artist in artists:
        if artist not in ref_artist2id:
            ref_artist2id[artist] = len(ref_artist2id) + 1
        ids.append(ref_artist2id[artist])
    ref_sequences[uid] = ids

# Compare mappings and complete ordered sequences with the notebook's pipeline.
current_user2id = {str(int(k)): int(v) for k, v in user2id.items()}
current_artist2id = {str(int(k)): int(v) for k, v in artist2id.items()}
assert current_user2id == ref_user2id, 'User-to-ID mapping differs from reference.'
assert current_artist2id == ref_artist2id, 'Artist-to-ID mapping differs from reference.'
assert list(item_sequences.items()) == list(ref_sequences.items()), 'At least one ordered item sequence differs from reference.'

# Verify core, ID range, unique interactions, time ordering, gap arithmetic, and serialized files.
assert len(item_sequences) == n_users == 1090
assert len(artist2id) == n_artists == 3646
assert sum(map(len, item_sequences.values())) == n_interactions == 52551
assert list(item_sequences) == list(range(1, n_users + 1))
assert sorted(artist2id.values()) == list(range(1, n_artists + 1))
item_frequency = Counter(item for items in item_sequences.values() for item in items)
assert min(map(len, item_sequences.values())) >= 5
assert min(item_frequency.values()) >= 5
for uid, items in item_sequences.items():
    times = time_sequences[uid]
    gaps = gap_sequences[uid]
    assert len(items) == len(times) == len(gaps)
    assert len(items) == len(set(items)), f'Duplicate artist for user {uid}'
    assert all(times[i] <= times[i + 1] for i in range(len(times) - 1)), f'Timestamps out of order for user {uid}'
    assert gaps[0] == 0
    assert gaps[1:] == [times[i] - times[i - 1] for i in range(1, len(times))]

def _serialized_lines(mapping):
    return [f'{uid} ' + ' '.join(map(str, values)) for uid, values in mapping.items()]
assert ITEM_FILE.read_text(encoding='utf-8').splitlines() == _serialized_lines(item_sequences)
assert TIME_FILE.read_text(encoding='utf-8').splitlines() == _serialized_lines(time_sequences)
assert GAP_FILE.read_text(encoding='utf-8').splitlines() == _serialized_lines(gap_sequences)

# Persist raw-ID maps so later versions can prove which item/user each integer ID means.
USER_MAP_FILE = DATA_OUT / 'LastFM_user2id.json'
ARTIST_MAP_FILE = DATA_OUT / 'LastFM_artist2id.json'
USER_MAP_FILE.write_text(json.dumps(ref_user2id, ensure_ascii=False, indent=2, sort_keys=True), encoding='utf-8')
ARTIST_MAP_FILE.write_text(json.dumps(ref_artist2id, ensure_ascii=False, indent=2, sort_keys=True), encoding='utf-8')

def _sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            h.update(block)
    return h.hexdigest()

def _git_value(args):
    result = subprocess.run(['git', '-C', str(REPO), *args], capture_output=True, text=True)
    return result.stdout.strip() if result.returncode == 0 else 'unavailable'

package_versions = {}
for package in ('numpy', 'pandas', 'scipy', 'torch', 'tqdm'):
    try:
        package_versions[package] = version(package)
    except PackageNotFoundError:
        package_versions[package] = 'not-installed'

manifest = {
    'audit_status': 'PASS',
    'audit_scope': 'per-user ordered sequence, user/item ID mappings, iterative 5-core, timestamp/gap alignment, serialized files',
    'reference': 'RUCAIBox/CIKM2020-S3Rec data/data_process.py LastFM preprocessing',
    'dataset': 'GroupLens HetRec 2011 Last.fm 2K; timestamps are tag-event timestamps, not listening/scrobble timestamps',
    'counts': {'users': n_users, 'artists': n_artists, 'interactions': n_interactions},
    'id_policy': '1-based IDs assigned by reference traversal order after 5-core filtering',
    'code': {'repository': 'https://github.com/yehjin-shin/BSARec', 'git_commit_at_audit': _git_value(['rev-parse', 'HEAD']), 'git_dirty': _git_value(['status', '--porcelain']) != ''},
    'runtime': {'python': platform.python_version(), 'packages': package_versions, 'cuda_available': bool(torch.cuda.is_available()), 'gpu': torch.cuda.get_device_name(0) if torch.cuda.is_available() else None},
    'sha256': {
        'dataset_zip': _sha256(ZIP_PATH), 'raw_timestamp_file': _sha256(RAW_PATH),
        'LastFM.txt': _sha256(ITEM_FILE), 'LastFM_time.txt': _sha256(TIME_FILE), 'LastFM_gap.txt': _sha256(GAP_FILE),
        'LastFM_user2id.json': _sha256(USER_MAP_FILE), 'LastFM_artist2id.json': _sha256(ARTIST_MAP_FILE),
    },
    'note': 'The commit recorded here proves the earlier training run only if this cell ran in that same repository/runtime; the original saved outputs did not record its commit.'
}
MANIFEST_FILE = DATA_OUT / 'LastFM_preprocessing_manifest.json'
MANIFEST_FILE.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding='utf-8')
print('Exact reference mapping and ordered sequence comparison: PASS (1,090/1,090 users)')
print('5-core, unique artists/user, monotonic times, exact gaps, and serialized row checks: PASS')
print('Saved:', USER_MAP_FILE, ARTIST_MAP_FILE, MANIFEST_FILE)
print('BSARec commit at audit time:', manifest['code']['git_commit_at_audit'])

Exact reference mapping and ordered sequence comparison: PASS (1,090/1,090 users)
5-core, unique artists/user, monotonic times, exact gaps, and serialized row checks: PASS
Saved: /content/BSARec/src/data/LastFM_user2id.json /content/BSARec/src/data/LastFM_artist2id.json /content/BSARec/src/data/LastFM_preprocessing_manifest.json
BSARec commit at audit time: c80bdc0f1a889b78fe9a27e2058389cc84caea84

## E. Jalankan BSARec dengan konfigurasi LastFM paper

Tiap seed memiliki nama run/checkpoint berbeda. Training mengikuti early stopping repo resmi. Jalankan ketiga sel ini satu per satu dan pastikan setiap proses selesai sampai `Test Score`.

In [6]:
!python main.py --data_name LastFM --lr 0.001 --alpha 0.9 --c 3 --num_attention_heads 1 --seed 42 --train_name BSARec_LastFM_final_s42

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:424: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
2026-10-29 15:22:11,370 - Namespace(data_dir='./data/', output_dir='output/', data_name='LastFM', do_eval=False, load_model=None, train_name='BSARec_LastFM_final_s42', num_items=10, num_users=1091, lr=0.001, batch_size=256, epochs=200, no_cuda=False, log_freq=1, patience=10, num_workers=4, seed=42, weight_decay=0.0, adam_beta1=0.9, adam_beta2=0.999, gpu_id='0', variance=5, model_type='BSARec', max_seq_length=50, hidden_size=64, num_hidden_layers=2, hidden_act='gelu', num_attention_heads=1, attention_probs_dropout_prob=0.5, hidden_dropout_prob=0.5, initializer_range=0.02, c=3, alpha=0.9, cuda_condition=True, data_file='./data/LastFM.txt', item_size=3647, checkpoint_path='output/BSARec_LastFM_final_s42.pt', same_target_path='./data/LastFM_same_target.npy')
2026-10-29 15:22:11,490 - BSARecModel(
  (item_embeddings): Embedding(3647, 64, padding_idx=0)
  (position_embeddings): Embedding(50, 64)
  (LayerNorm): LayerNorm()
  (dropout): Dropout(p=0.5, inplace=False)
  (item_encoder): BSARecEncoder(
    (blocks): ModuleList(
      (0-1): 2 x BSARecBlock(
        (layer): BSARecLayer(
          (filter_layer): FrequencyLayer(
            (out_dropout): Dropout(p=0.5, inplace=False)
            (LayerNorm): LayerNorm()
          )
          (attention_layer): MultiHeadAttention(
            (query): Linear(in_features=64, out_features=64, bias=True)
            (key): Linear(in_features=64, out_features=64, bias=True)
            (value): Linear(in_features=64, out_features=64, bias=True)
            (softmax): Softmax(dim=-1)
            (attn_dropout): Dropout(p=0.5, inplace=False)
            (dense): Linear(in_features=64, out_features=64, bias=True)
            (LayerNorm): LayerNorm((64,), eps=1e-12, elementwise_affine=True)
            (out_dropout): Dropout(p=0.5, inplace=False)
          )
        )
        (feed_forward): FeedForward(
          (dense_1): Linear(in_features=64, out_features=256, bias=True)
          (dense_2): Linear(in_features=256, out_features=64, bias=True)
          (LayerNorm): LayerNorm()
          (dropout): Dropout(p=0.5, inplace=False)
        )
      )
    )
  )
)
2026-10-29 15:22:17,147 - Total Parameters: 337088
/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
Mode_train:0: 100% 101/101 [00:03<00:00, 28.54it/s]
2026-10-29 15:22:20,789 - {'epoch': 0, 'rec_loss': '7.9841'}
Mode_test:0: 100% 5/5 [00:00<00:00, 23.49it/s]
2026-10-29 15:22:21,121 - {'Epoch': 0, 'HR@5': '0.0202', 'NDCG@5': '0.0119', 'HR@10': '0.0339', 'NDCG@10': '0.0163', 'HR@20': '0.0615', 'NDCG@20': '0.0231'}
2026-10-29 15:22:21,122 - Validation score increased.  Saving model ...
Mode_train:1: 100% 101/101 [00:02<00:00, 40.86it/s]
2026-10-29 15:22:23,669 - {'epoch': 1, 'rec_loss': '7.6945'}
Mode_test:1: 100% 5/5 [00:00<00:00, 24.28it/s]
2026-10-29 15:22:23,990 - {'Epoch': 1, 'HR@5': '0.0211', 'NDCG@5': '0.0124', 'HR@10': '0.0330', 'NDCG@10': '0.0163', 'HR@20': '0.0532', 'NDCG@20': '0.0213'}
2026-10-29 15:22:23,992 - EarlyStopping counter: 1 out of 10
Mode_train:2: 100% 101/101 [00:02<00:00, 40.62it/s]
2026-10-29 15:22:26,542 - {'epoch': 2, 'rec_loss': '7.5208'}
Mode_test:2: 100% 5/5 [00:00<00:00, 24.61it/s]
2026-10-29 15:22:26,892 - {'Epoch': 2, 'HR@5': '0.0202', 'NDCG@5': '0.0113', 'HR@10': '0.0349', 'NDCG@10': '0.0161', 'HR@20': '0.0560', 'NDCG@20': '0.0215'}
2026-10-29 15:22:26,893 - EarlyStopping counter: 2 out of 10
Mode_train:3: 100% 101/101 [00:02<00:00, 40.90it/s]
2026-10-29 15:22:29,419 - {'epoch': 3, 'rec_loss': '7.3486'}
Mode_test:3: 100% 5/5 [00:00<00:00, 24.56it/s]
2026-10-29 15:22:29,744 - {'Epoch': 3, 'HR@5': '0.0303', 'NDCG@5': '0.0198', 'HR@10': '0.0450', 'NDCG@10': '0.0243', 'HR@20': '0.0679', 'NDCG@20': '0.0300'}
2026-10-29 15:22:29,745 - Validation score increased.  Saving model ...
Mode_train:4: 100% 101/101 [00:02<00:00, 40.07it/s]
2026-10-29 15:22:32,334 - {'epoch': 4, 'rec_loss': '7.1726'}
Mode_test:4: 100% 5/5 [00:00<00:00, 23.01it/s]
2026-10-29 15:22:32,678 - {'Epoch': 4, 'HR@5': '0.0349', 'NDCG@5': '0.0218', 'HR@10': '0.0532', 'NDCG@10': '0.0278', 'HR@20': '0.0844', 'NDCG@20': '0.0356'}
2026-10-29 15:22:32,679 - Validation score increased.  Saving model ...
Mode_train:5: 100% 101/101 [00:02<00:00, 39.93it/s]
2026-10-29 15:22:35,279 - {'epoch': 5, 'rec_loss': '6.9763'}
Mode_test:5: 100% 5/5 [00:00<00:00, 25.04it/s]
2026-10-29 15:22:35,617 - {'Epoch': 5, 'HR@5': '0.0477', 'NDCG@5': '0.0309', 'HR@10': '0.0706', 'NDCG@10': '0.0381', 'HR@20': '0.0917', 'NDCG@20': '0.0433'}
2026-10-29 15:22:35,618 - Validation score increased.  Saving model ...
Mode_train:6: 100% 101/101 [00:02<00:00, 37.98it/s]
2026-10-29 15:22:38,353 - {'epoch': 6, 'rec_loss': '6.7724'}
Mode_test:6: 100% 5/5 [00:00<00:00, 25.12it/s]
2026-10-29 15:22:38,679 - {'Epoch': 6, 'HR@5': '0.0486', 'NDCG@5': '0.0304', 'HR@10': '0.0706', 'NDCG@10': '0.0374', 'HR@20': '0.1055', 'NDCG@20': '0.0461'}
2026-10-29 15:22:38,680 - Validation score increased.  Saving model ...
Mode_train:7: 100% 101/101 [00:02<00:00, 40.53it/s]
2026-10-29 15:22:41,260 - {'epoch': 7, 'rec_loss': '6.5819'}
Mode_test:7: 100% 5/5 [00:00<00:00, 25.04it/s]
2026-10-29 15:22:41,579 - {'Epoch': 7, 'HR@5': '0.0523', 'NDCG@5': '0.0338', 'HR@10': '0.0761', 'NDCG@10': '0.0416', 'HR@20': '0.1083', 'NDCG@20': '0.0494'}
2026-10-29 15:22:41,580 - Validation score increased.  Saving model ...
Mode_train:8: 100% 101/101 [00:02<00:00, 39.97it/s]
2026-10-29 15:22:44,180 - {'epoch': 8, 'rec_loss': '6.4166'}
Mode_test:8: 100% 5/5 [00:00<00:00, 25.57it/s]
2026-10-29 15:22:44,498 - {'Epoch': 8, 'HR@5': '0.0523', 'NDCG@5': '0.0329', 'HR@10': '0.0752', 'NDCG@10': '0.0402', 'HR@20': '0.1083', 'NDCG@20': '0.0487'}
2026-10-29 15:22:44,499 - EarlyStopping counter: 1 out of 10
Mode_train:9: 100% 101/101 [00:02<00:00, 40.93it/s]
2026-10-29 15:22:47,022 - {'epoch': 9, 'rec_loss': '6.2622'}
Mode_test:9: 100% 5/5 [00:00<00:00, 23.36it/s]
2026-10-29 15:22:47,366 - {'Epoch': 9, 'HR@5': '0.0505', 'NDCG@5': '0.0342', 'HR@10': '0.0761', 'NDCG@10': '0.0426', 'HR@20': '0.1239', 'NDCG@20': '0.0546'}
2026-10-29 15:22:47,367 - Validation score increased.  Saving model ...
Mode_train:10: 100% 101/101 [00:02<00:00, 41.60it/s]
2026-10-29 15:22:49,867 - {'epoch': 10, 'rec_loss': '6.1328'}
Mode_test:10: 100% 5/5 [00:00<00:00, 24.07it/s]
2026-10-29 15:22:50,187 - {'Epoch': 10, 'HR@5': '0.0560', 'NDCG@5': '0.0364', 'HR@10': '0.0890', 'NDCG@10': '0.0471', 'HR@20': '0.1339', 'NDCG@20': '0.0583'}
2026-10-29 15:22:50,188 - Validation score increased.  Saving model ...
Mode_train:11: 100% 101/101 [00:02<00:00, 38.99it/s]
2026-10-29 15:22:52,862 - {'epoch': 11, 'rec_loss': '6.0153'}
Mode_test:11: 100% 5/5 [00:00<00:00, 21.37it/s]
2026-10-29 15:22:53,457 - {'Epoch': 11, 'HR@5': '0.0523', 'NDCG@5': '0.0329', 'HR@10': '0.0862', 'NDCG@10': '0.0440', 'HR@20': '0.1275', 'NDCG@20': '0.0544'}
2026-10-29 15:22:53,458 - EarlyStopping counter: 1 out of 10
Mode_train:12: 100% 101/101 [00:02<00:00, 36.44it/s]
2026-10-29 15:22:56,288 - {'epoch': 12, 'rec_loss': '5.9113'}
Mode_test:12: 100% 5/5 [00:00<00:00, 23.98it/s]
2026-10-29 15:22:56,618 - {'Epoch': 12, 'HR@5': '0.0606', 'NDCG@5': '0.0378', 'HR@10': '0.0890', 'NDCG@10': '0.0470', 'HR@20': '0.1275', 'NDCG@20': '0.0567'}
2026-10-29 15:22:56,620 - EarlyStopping counter: 2 out of 10
Mode_train:13: 100% 101/101 [00:02<00:00, 40.59it/s]
2026-10-29 15:22:59,173 - {'epoch': 13, 'rec_loss': '5.8062'}
Mode_test:13: 100% 5/5 [00:00<00:00, 25.79it/s]
2026-10-29 15:22:59,490 - {'Epoch': 13, 'HR@5': '0.0523', 'NDCG@5': '0.0351', 'HR@10': '0.0908', 'NDCG@10': '0.0472', 'HR@20': '0.1312', 'NDCG@20': '0.0573'}
2026-10-29 15:22:59,492 - EarlyStopping counter: 3 out of 10
Mode_train:14: 100% 101/101 [00:02<00:00, 39.20it/s]
2026-10-29 15:23:02,130 - {'epoch': 14, 'rec_loss': '5.7290'}
Mode_test:14: 100% 5/5 [00:00<00:00, 23.81it/s]
2026-10-29 15:23:02,459 - {'Epoch': 14, 'HR@5': '0.0569', 'NDCG@5': '0.0347', 'HR@10': '0.0862', 'NDCG@10': '0.0442', 'HR@20': '0.1294', 'NDCG@20': '0.0550'}
2026-10-29 15:23:02,460 - EarlyStopping counter: 4 out of 10
Mode_train:15: 100% 101/101 [00:02<00:00, 39.86it/s]
2026-10-29 15:23:05,057 - {'epoch': 15, 'rec_loss': '5.6525'}
Mode_test:15: 100% 5/5 [00:00<00:00, 21.92it/s]
2026-10-29 15:23:05,410 - {'Epoch': 15, 'HR@5': '0.0541', 'NDCG@5': '0.0342', 'HR@10': '0.0963', 'NDCG@10': '0.0477', 'HR@20': '0.1275', 'NDCG@20': '0.0556'}
2026-10-29 15:23:05,412 - EarlyStopping counter: 5 out of 10
Mode_train:16: 100% 101/101 [00:02<00:00, 38.32it/s]
2026-10-29 15:23:08,106 - {'epoch': 16, 'rec_loss': '5.5841'}
Mode_test:16: 100% 5/5 [00:00<00:00, 21.28it/s]
2026-10-29 15:23:08,459 - {'Epoch': 16, 'HR@5': '0.0560', 'NDCG@5': '0.0357', 'HR@10': '0.0945', 'NDCG@10': '0.0481', 'HR@20': '0.1358', 'NDCG@20': '0.0583'}
2026-10-29 15:23:08,461 - Validation score increased.  Saving model ...
Mode_train:17: 100% 101/101 [00:02<00:00, 37.06it/s]
2026-10-29 15:23:11,254 - {'epoch': 17, 'rec_loss': '5.5331'}
Mode_test:17: 100% 5/5 [00:00<00:00, 20.35it/s]
2026-10-29 15:23:11,619 - {'Epoch': 17, 'HR@5': '0.0606', 'NDCG@5': '0.0385', 'HR@10': '0.0927', 'NDCG@10': '0.0487', 'HR@20': '0.1312', 'NDCG@20': '0.0583'}
2026-10-29 15:23:11,621 - EarlyStopping counter: 1 out of 10
Mode_train:18: 100% 101/101 [00:02<00:00, 38.00it/s]
2026-10-29 15:23:14,336 - {'epoch': 18, 'rec_loss': '5.4775'}
Mode_test:18: 100% 5/5 [00:00<00:00, 21.73it/s]
2026-10-29 15:23:14,691 - {'Epoch': 18, 'HR@5': '0.0523', 'NDCG@5': '0.0352', 'HR@10': '0.0872', 'NDCG@10': '0.0465', 'HR@20': '0.1358', 'NDCG@20': '0.0587'}
2026-10-29 15:23:14,692 - Validation score increased.  Saving model ...
Mode_train:19: 100% 101/101 [00:02<00:00, 38.03it/s]
2026-10-29 15:23:17,423 - {'epoch': 19, 'rec_loss': '5.4385'}
Mode_test:19: 100% 5/5 [00:00<00:00, 21.65it/s]
2026-10-29 15:23:17,789 - {'Epoch': 19, 'HR@5': '0.0606', 'NDCG@5': '0.0390', 'HR@10': '0.0945', 'NDCG@10': '0.0499', 'HR@20': '0.1431', 'NDCG@20': '0.0621'}
2026-10-29 15:23:17,790 - Validation score increased.  Saving model ...
Mode_train:20: 100% 101/101 [00:02<00:00, 38.30it/s]
2026-10-29 15:23:20,500 - {'epoch': 20, 'rec_loss': '5.3994'}
Mode_test:20: 100% 5/5 [00:00<00:00, 20.08it/s]
2026-10-29 15:23:20,897 - {'Epoch': 20, 'HR@5': '0.0578', 'NDCG@5': '0.0365', 'HR@10': '0.0936', 'NDCG@10': '0.0480', 'HR@20': '0.1376', 'NDCG@20': '0.0592'}
2026-10-29 15:23:20,899 - EarlyStopping counter: 1 out of 10
Mode_train:21: 100% 101/101 [00:02<00:00, 40.32it/s]
2026-10-29 15:23:23,488 - {'epoch': 21, 'rec_loss': '5.3594'}
Mode_test:21: 100% 5/5 [00:00<00:00, 20.12it/s]
2026-10-29 15:23:23,861 - {'Epoch': 21, 'HR@5': '0.0569', 'NDCG@5': '0.0380', 'HR@10': '0.0945', 'NDCG@10': '0.0501', 'HR@20': '0.1394', 'NDCG@20': '0.0613'}
2026-10-29 15:23:23,862 - EarlyStopping counter: 2 out of 10
Mode_train:22: 100% 101/101 [00:02<00:00, 40.17it/s]
2026-10-29 15:23:26,446 - {'epoch': 22, 'rec_loss': '5.3210'}
Mode_test:22: 100% 5/5 [00:00<00:00, 20.73it/s]
2026-10-29 15:23:26,814 - {'Epoch': 22, 'HR@5': '0.0615', 'NDCG@5': '0.0375', 'HR@10': '0.0954', 'NDCG@10': '0.0484', 'HR@20': '0.1385', 'NDCG@20': '0.0592'}
2026-10-29 15:23:26,816 - EarlyStopping counter: 3 out of 10
Mode_train:23: 100% 101/101 [00:02<00:00, 40.50it/s]
2026-10-29 15:23:29,387 - {'epoch': 23, 'rec_loss': '5.2875'}
Mode_test:23: 100% 5/5 [00:00<00:00, 20.43it/s]
2026-10-29 15:23:29,767 - {'Epoch': 23, 'HR@5': '0.0624', 'NDCG@5': '0.0396', 'HR@10': '0.0954', 'NDCG@10': '0.0501', 'HR@20': '0.1422', 'NDCG@20': '0.0618'}
2026-10-29 15:23:29,768 - EarlyStopping counter: 4 out of 10
Mode_train:24: 100% 101/101 [00:02<00:00, 36.68it/s]
2026-10-29 15:23:32,581 - {'epoch': 24, 'rec_loss': '5.2746'}
Mode_test:24: 100% 5/5 [00:00<00:00, 21.37it/s]
2026-10-29 15:23:32,939 - {'Epoch': 24, 'HR@5': '0.0661', 'NDCG@5': '0.0414', 'HR@10': '0.1028', 'NDCG@10': '0.0531', 'HR@20': '0.1349', 'NDCG@20': '0.0611'}
2026-10-29 15:23:32,940 - EarlyStopping counter: 5 out of 10
Mode_train:25: 100% 101/101 [00:02<00:00, 39.60it/s]
2026-10-29 15:23:35,555 - {'epoch': 25, 'rec_loss': '5.2516'}
Mode_test:25: 100% 5/5 [00:00<00:00, 20.08it/s]
2026-10-29 15:23:35,922 - {'Epoch': 25, 'HR@5': '0.0569', 'NDCG@5': '0.0372', 'HR@10': '0.0963', 'NDCG@10': '0.0498', 'HR@20': '0.1376', 'NDCG@20': '0.0603'}
2026-10-29 15:23:35,923 - EarlyStopping counter: 6 out of 10
Mode_train:26: 100% 101/101 [00:02<00:00, 37.20it/s]
2026-10-29 15:23:38,703 - {'epoch': 26, 'rec_loss': '5.2306'}
Mode_test:26: 100% 5/5 [00:00<00:00, 19.48it/s]
2026-10-29 15:23:39,075 - {'Epoch': 26, 'HR@5': '0.0569', 'NDCG@5': '0.0366', 'HR@10': '0.0982', 'NDCG@10': '0.0500', 'HR@20': '0.1431', 'NDCG@20': '0.0615'}
2026-10-29 15:23:39,077 - EarlyStopping counter: 7 out of 10
Mode_train:27: 100% 101/101 [00:02<00:00, 39.39it/s]
2026-10-29 15:23:41,709 - {'epoch': 27, 'rec_loss': '5.1983'}
Mode_test:27: 100% 5/5 [00:00<00:00, 20.76it/s]
2026-10-29 15:23:42,085 - {'Epoch': 27, 'HR@5': '0.0633', 'NDCG@5': '0.0397', 'HR@10': '0.1009', 'NDCG@10': '0.0518', 'HR@20': '0.1376', 'NDCG@20': '0.0611'}
2026-10-29 15:23:42,086 - EarlyStopping counter: 8 out of 10
Mode_train:28: 100% 101/101 [00:02<00:00, 38.74it/s]
2026-10-29 15:23:44,756 - {'epoch': 28, 'rec_loss': '5.1858'}
Mode_test:28: 100% 5/5 [00:00<00:00, 21.77it/s]
2026-10-29 15:23:45,116 - {'Epoch': 28, 'HR@5': '0.0615', 'NDCG@5': '0.0391', 'HR@10': '0.0945', 'NDCG@10': '0.0496', 'HR@20': '0.1450', 'NDCG@20': '0.0624'}
2026-10-29 15:23:45,118 - Validation score increased.  Saving model ...
Mode_train:29: 100% 101/101 [00:02<00:00, 40.86it/s]
2026-10-29 15:23:47,660 - {'epoch': 29, 'rec_loss': '5.1566'}
Mode_test:29: 100% 5/5 [00:00<00:00, 19.65it/s]
2026-10-29 15:23:48,051 - {'Epoch': 29, 'HR@5': '0.0587', 'NDCG@5': '0.0377', 'HR@10': '0.0982', 'NDCG@10': '0.0504', 'HR@20': '0.1459', 'NDCG@20': '0.0622'}
2026-10-29 15:23:48,052 - EarlyStopping counter: 1 out of 10
Mode_train:30: 100% 101/101 [00:02<00:00, 41.26it/s]
2026-10-29 15:23:50,568 - {'epoch': 30, 'rec_loss': '5.1377'}
Mode_test:30: 100% 5/5 [00:00<00:00, 20.55it/s]
2026-10-29 15:23:50,923 - {'Epoch': 30, 'HR@5': '0.0661', 'NDCG@5': '0.0416', 'HR@10': '0.1028', 'NDCG@10': '0.0536', 'HR@20': '0.1431', 'NDCG@20': '0.0637'}
2026-10-29 15:23:50,924 - Validation score increased.  Saving model ...
Mode_train:31: 100% 101/101 [00:02<00:00, 39.16it/s]
2026-10-29 15:23:53,592 - {'epoch': 31, 'rec_loss': '5.1173'}
Mode_test:31: 100% 5/5 [00:00<00:00, 22.29it/s]
2026-10-29 15:23:53,943 - {'Epoch': 31, 'HR@5': '0.0651', 'NDCG@5': '0.0415', 'HR@10': '0.0972', 'NDCG@10': '0.0519', 'HR@20': '0.1367', 'NDCG@20': '0.0619'}
2026-10-29 15:23:53,945 - EarlyStopping counter: 1 out of 10
Mode_train:32: 100% 101/101 [00:02<00:00, 40.18it/s]
2026-10-29 15:23:56,528 - {'epoch': 32, 'rec_loss': '5.0990'}
Mode_test:32: 100% 5/5 [00:00<00:00, 20.46it/s]
2026-10-29 15:23:56,895 - {'Epoch': 32, 'HR@5': '0.0661', 'NDCG@5': '0.0420', 'HR@10': '0.0991', 'NDCG@10': '0.0528', 'HR@20': '0.1477', 'NDCG@20': '0.0649'}
2026-10-29 15:23:56,896 - Validation score increased.  Saving model ...
Mode_train:33: 100% 101/101 [00:02<00:00, 39.44it/s]
2026-10-29 15:23:59,534 - {'epoch': 33, 'rec_loss': '5.0835'}
Mode_test:33: 100% 5/5 [00:00<00:00, 19.95it/s]
2026-10-29 15:23:59,895 - {'Epoch': 33, 'HR@5': '0.0642', 'NDCG@5': '0.0406', 'HR@10': '0.1009', 'NDCG@10': '0.0522', 'HR@20': '0.1486', 'NDCG@20': '0.0640'}
2026-10-29 15:23:59,897 - EarlyStopping counter: 1 out of 10
Mode_train:34: 100% 101/101 [00:02<00:00, 39.64it/s]
2026-10-29 15:24:02,509 - {'epoch': 34, 'rec_loss': '5.0674'}
Mode_test:34: 100% 5/5 [00:00<00:00, 20.49it/s]
2026-10-29 15:24:02,869 - {'Epoch': 34, 'HR@5': '0.0679', 'NDCG@5': '0.0445', 'HR@10': '0.0972', 'NDCG@10': '0.0537', 'HR@20': '0.1495', 'NDCG@20': '0.0669'}
2026-10-29 15:24:02,870 - Validation score increased.  Saving model ...
Mode_train:35: 100% 101/101 [00:02<00:00, 39.48it/s]
2026-10-29 15:24:05,503 - {'epoch': 35, 'rec_loss': '5.0586'}
Mode_test:35: 100% 5/5 [00:00<00:00, 18.62it/s]
2026-10-29 15:24:05,887 - {'Epoch': 35, 'HR@5': '0.0661', 'NDCG@5': '0.0415', 'HR@10': '0.0936', 'NDCG@10': '0.0503', 'HR@20': '0.1505', 'NDCG@20': '0.0644'}
2026-10-29 15:24:05,889 - EarlyStopping counter: 1 out of 10
Mode_train:36: 100% 101/101 [00:02<00:00, 38.56it/s]
2026-10-29 15:24:08,572 - {'epoch': 36, 'rec_loss': '5.0325'}
Mode_test:36: 100% 5/5 [00:00<00:00, 19.00it/s]
2026-10-29 15:24:08,946 - {'Epoch': 36, 'HR@5': '0.0596', 'NDCG@5': '0.0405', 'HR@10': '0.1000', 'NDCG@10': '0.0534', 'HR@20': '0.1440', 'NDCG@20': '0.0643'}
2026-10-29 15:24:08,947 - EarlyStopping counter: 2 out of 10
Mode_train:37: 100% 101/101 [00:02<00:00, 40.32it/s]
2026-10-29 15:24:11,517 - {'epoch': 37, 'rec_loss': '5.0232'}
Mode_test:37: 100% 5/5 [00:00<00:00, 16.84it/s]
2026-10-29 15:24:11,947 - {'Epoch': 37, 'HR@5': '0.0670', 'NDCG@5': '0.0447', 'HR@10': '0.1009', 'NDCG@10': '0.0555', 'HR@20': '0.1450', 'NDCG@20': '0.0665'}
2026-10-29 15:24:11,949 - EarlyStopping counter: 3 out of 10
Mode_train:38: 100% 101/101 [00:02<00:00, 40.59it/s]
2026-10-29 15:24:14,493 - {'epoch': 38, 'rec_loss': '5.0110'}
Mode_test:38: 100% 5/5 [00:00<00:00, 21.76it/s]
2026-10-29 15:24:14,839 - {'Epoch': 38, 'HR@5': '0.0606', 'NDCG@5': '0.0404', 'HR@10': '0.0982', 'NDCG@10': '0.0524', 'HR@20': '0.1404', 'NDCG@20': '0.0631'}
2026-10-29 15:24:14,840 - EarlyStopping counter: 4 out of 10
Mode_train:39: 100% 101/101 [00:02<00:00, 39.54it/s]
2026-10-29 15:24:17,461 - {'epoch': 39, 'rec_loss': '5.0094'}
Mode_test:39: 100% 5/5 [00:00<00:00, 21.58it/s]
2026-10-29 15:24:17,829 - {'Epoch': 39, 'HR@5': '0.0670', 'NDCG@5': '0.0426', 'HR@10': '0.1037', 'NDCG@10': '0.0546', 'HR@20': '0.1404', 'NDCG@20': '0.0638'}
2026-10-29 15:24:17,831 - EarlyStopping counter: 5 out of 10
Mode_train:40: 100% 101/101 [00:02<00:00, 40.31it/s]
2026-10-29 15:24:20,397 - {'epoch': 40, 'rec_loss': '4.9933'}
Mode_test:40: 100% 5/5 [00:00<00:00, 20.40it/s]
2026-10-29 15:24:20,759 - {'Epoch': 40, 'HR@5': '0.0624', 'NDCG@5': '0.0427', 'HR@10': '0.1028', 'NDCG@10': '0.0557', 'HR@20': '0.1440', 'NDCG@20': '0.0661'}
2026-10-29 15:24:20,760 - EarlyStopping counter: 6 out of 10
Mode_train:41: 100% 101/101 [00:02<00:00, 39.10it/s]
2026-10-29 15:24:23,409 - {'epoch': 41, 'rec_loss': '4.9733'}
Mode_test:41: 100% 5/5 [00:00<00:00, 21.79it/s]
2026-10-29 15:24:23,771 - {'Epoch': 41, 'HR@5': '0.0642', 'NDCG@5': '0.0420', 'HR@10': '0.1009', 'NDCG@10': '0.0536', 'HR@20': '0.1459', 'NDCG@20': '0.0648'}
2026-10-29 15:24:23,772 - EarlyStopping counter: 7 out of 10
Mode_train:42: 100% 101/101 [00:02<00:00, 39.90it/s]
2026-10-29 15:24:26,359 - {'epoch': 42, 'rec_loss': '4.9776'}
Mode_test:42: 100% 5/5 [00:00<00:00, 20.42it/s]
2026-10-29 15:24:26,738 - {'Epoch': 42, 'HR@5': '0.0679', 'NDCG@5': '0.0438', 'HR@10': '0.1009', 'NDCG@10': '0.0543', 'HR@20': '0.1477', 'NDCG@20': '0.0659'}
2026-10-29 15:24:26,740 - EarlyStopping counter: 8 out of 10
Mode_train:43: 100% 101/101 [00:02<00:00, 40.14it/s]
2026-10-29 15:24:29,322 - {'epoch': 43, 'rec_loss': '4.9426'}
Mode_test:43: 100% 5/5 [00:00<00:00, 20.60it/s]

In [7]:
!python main.py --data_name LastFM --lr 0.001 --alpha 0.9 --c 3 --num_attention_heads 1 --seed 43 --train_name BSARec_LastFM_final_s43

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:424: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
2026-10-29 15:26:17,597 - Namespace(data_dir='./data/', output_dir='output/', data_name='LastFM', do_eval=False, load_model=None, train_name='BSARec_LastFM_final_s43', num_items=10, num_users=1091, lr=0.001, batch_size=256, epochs=200, no_cuda=False, log_freq=1, patience=10, num_workers=4, seed=43, weight_decay=0.0, adam_beta1=0.9, adam_beta2=0.999, gpu_id='0', variance=5, model_type='BSARec', max_seq_length=50, hidden_size=64, num_hidden_layers=2, hidden_act='gelu', num_attention_heads=1, attention_probs_dropout_prob=0.5, hidden_dropout_prob=0.5, initializer_range=0.02, c=3, alpha=0.9, cuda_condition=True, data_file='./data/LastFM.txt', item_size=3647, checkpoint_path='output/BSARec_LastFM_final_s43.pt', same_target_path='./data/LastFM_same_target.npy')
2026-10-29 15:26:17,614 - BSARecModel(
  (item_embeddings): Embedding(3647, 64, padding_idx=0)
  (position_embeddings): Embedding(50, 64)
  (LayerNorm): LayerNorm()
  (dropout): Dropout(p=0.5, inplace=False)
  (item_encoder): BSARecEncoder(
    (blocks): ModuleList(
      (0-1): 2 x BSARecBlock(
        (layer): BSARecLayer(
          (filter_layer): FrequencyLayer(
            (out_dropout): Dropout(p=0.5, inplace=False)
            (LayerNorm): LayerNorm()
          )
          (attention_layer): MultiHeadAttention(
            (query): Linear(in_features=64, out_features=64, bias=True)
            (key): Linear(in_features=64, out_features=64, bias=True)
            (value): Linear(in_features=64, out_features=64, bias=True)
            (softmax): Softmax(dim=-1)
            (attn_dropout): Dropout(p=0.5, inplace=False)
            (dense): Linear(in_features=64, out_features=64, bias=True)
            (LayerNorm): LayerNorm((64,), eps=1e-12, elementwise_affine=True)
            (out_dropout): Dropout(p=0.5, inplace=False)
          )
        )
        (feed_forward): FeedForward(
          (dense_1): Linear(in_features=64, out_features=256, bias=True)
          (dense_2): Linear(in_features=256, out_features=64, bias=True)
          (LayerNorm): LayerNorm()
          (dropout): Dropout(p=0.5, inplace=False)
        )
      )
    )
  )
)
2026-10-29 15:26:18,762 - Total Parameters: 337088
/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
Mode_train:0: 100% 101/101 [00:02<00:00, 35.74it/s]
2026-10-29 15:26:21,672 - {'epoch': 0, 'rec_loss': '7.9890'}
Mode_test:0: 100% 5/5 [00:00<00:00, 21.82it/s]
2026-10-29 15:26:22,032 - {'Epoch': 0, 'HR@5': '0.0220', 'NDCG@5': '0.0139', 'HR@10': '0.0404', 'NDCG@10': '0.0199', 'HR@20': '0.0624', 'NDCG@20': '0.0253'}
2026-10-29 15:26:22,033 - Validation score increased.  Saving model ...
Mode_train:1: 100% 101/101 [00:02<00:00, 38.60it/s]
2026-10-29 15:26:24,729 - {'epoch': 1, 'rec_loss': '7.7273'}
Mode_test:1: 100% 5/5 [00:00<00:00, 22.32it/s]
2026-10-29 15:26:25,070 - {'Epoch': 1, 'HR@5': '0.0248', 'NDCG@5': '0.0154', 'HR@10': '0.0339', 'NDCG@10': '0.0184', 'HR@20': '0.0541', 'NDCG@20': '0.0236'}
2026-10-29 15:26:25,071 - EarlyStopping counter: 1 out of 10
Mode_train:2: 100% 101/101 [00:02<00:00, 41.30it/s]
2026-10-29 15:26:27,581 - {'epoch': 2, 'rec_loss': '7.5625'}
Mode_test:2: 100% 5/5 [00:00<00:00, 25.15it/s]
2026-10-29 15:26:27,900 - {'Epoch': 2, 'HR@5': '0.0248', 'NDCG@5': '0.0159', 'HR@10': '0.0422', 'NDCG@10': '0.0215', 'HR@20': '0.0661', 'NDCG@20': '0.0274'}
2026-10-29 15:26:27,901 - Validation score increased.  Saving model ...
Mode_train:3: 100% 101/101 [00:02<00:00, 40.78it/s]
2026-10-29 15:26:30,450 - {'epoch': 3, 'rec_loss': '7.3983'}
Mode_test:3: 100% 5/5 [00:00<00:00, 24.40it/s]
2026-10-29 15:26:30,766 - {'Epoch': 3, 'HR@5': '0.0303', 'NDCG@5': '0.0216', 'HR@10': '0.0450', 'NDCG@10': '0.0264', 'HR@20': '0.0642', 'NDCG@20': '0.0312'}
2026-10-29 15:26:30,767 - Validation score increased.  Saving model ...
Mode_train:4: 100% 101/101 [00:02<00:00, 41.12it/s]
2026-10-29 15:26:33,299 - {'epoch': 4, 'rec_loss': '7.2442'}
Mode_test:4: 100% 5/5 [00:00<00:00, 24.77it/s]
2026-10-29 15:26:33,626 - {'Epoch': 4, 'HR@5': '0.0349', 'NDCG@5': '0.0220', 'HR@10': '0.0505', 'NDCG@10': '0.0270', 'HR@20': '0.0706', 'NDCG@20': '0.0322'}
2026-10-29 15:26:33,628 - Validation score increased.  Saving model ...
Mode_train:5: 100% 101/101 [00:02<00:00, 38.94it/s]
2026-10-29 15:26:36,294 - {'epoch': 5, 'rec_loss': '7.0960'}
Mode_test:5: 100% 5/5 [00:00<00:00, 23.25it/s]
2026-10-29 15:26:36,632 - {'Epoch': 5, 'HR@5': '0.0358', 'NDCG@5': '0.0237', 'HR@10': '0.0532', 'NDCG@10': '0.0293', 'HR@20': '0.0835', 'NDCG@20': '0.0371'}
2026-10-29 15:26:36,634 - Validation score increased.  Saving model ...
Mode_train:6: 100% 101/101 [00:02<00:00, 39.39it/s]
2026-10-29 15:26:39,267 - {'epoch': 6, 'rec_loss': '6.9378'}
Mode_test:6: 100% 5/5 [00:00<00:00, 16.19it/s]
2026-10-29 15:26:39,693 - {'Epoch': 6, 'HR@5': '0.0413', 'NDCG@5': '0.0268', 'HR@10': '0.0615', 'NDCG@10': '0.0332', 'HR@20': '0.0908', 'NDCG@20': '0.0407'}
2026-10-29 15:26:39,694 - Validation score increased.  Saving model ...
Mode_train:7: 100% 101/101 [00:02<00:00, 40.76it/s]
2026-10-29 15:26:42,245 - {'epoch': 7, 'rec_loss': '6.7756'}
Mode_test:7: 100% 5/5 [00:00<00:00, 25.75it/s]
2026-10-29 15:26:42,565 - {'Epoch': 7, 'HR@5': '0.0495', 'NDCG@5': '0.0316', 'HR@10': '0.0679', 'NDCG@10': '0.0374', 'HR@20': '0.0982', 'NDCG@20': '0.0450'}
2026-10-29 15:26:42,566 - Validation score increased.  Saving model ...
Mode_train:8: 100% 101/101 [00:02<00:00, 40.01it/s]
2026-10-29 15:26:45,167 - {'epoch': 8, 'rec_loss': '6.6174'}
Mode_test:8: 100% 5/5 [00:00<00:00, 24.88it/s]
2026-10-29 15:26:45,487 - {'Epoch': 8, 'HR@5': '0.0514', 'NDCG@5': '0.0336', 'HR@10': '0.0725', 'NDCG@10': '0.0403', 'HR@20': '0.0972', 'NDCG@20': '0.0465'}
2026-10-29 15:26:45,488 - Validation score increased.  Saving model ...
Mode_train:9: 100% 101/101 [00:02<00:00, 41.27it/s]
2026-10-29 15:26:48,006 - {'epoch': 9, 'rec_loss': '6.4639'}
Mode_test:9: 100% 5/5 [00:00<00:00, 25.17it/s]
2026-10-29 15:26:48,336 - {'Epoch': 9, 'HR@5': '0.0477', 'NDCG@5': '0.0312', 'HR@10': '0.0688', 'NDCG@10': '0.0381', 'HR@20': '0.1018', 'NDCG@20': '0.0465'}
2026-10-29 15:26:48,337 - Validation score increased.  Saving model ...
Mode_train:10: 100% 101/101 [00:02<00:00, 41.69it/s]
2026-10-29 15:26:50,830 - {'epoch': 10, 'rec_loss': '6.3150'}
Mode_test:10: 100% 5/5 [00:00<00:00, 24.47it/s]
2026-10-29 15:26:51,164 - {'Epoch': 10, 'HR@5': '0.0532', 'NDCG@5': '0.0361', 'HR@10': '0.0734', 'NDCG@10': '0.0427', 'HR@20': '0.1119', 'NDCG@20': '0.0523'}
2026-10-29 15:26:51,165 - Validation score increased.  Saving model ...
Mode_train:11: 100% 101/101 [00:02<00:00, 41.77it/s]
2026-10-29 15:26:53,653 - {'epoch': 11, 'rec_loss': '6.1712'}
Mode_test:11: 100% 5/5 [00:00<00:00, 27.38it/s]
2026-10-29 15:26:53,952 - {'Epoch': 11, 'HR@5': '0.0486', 'NDCG@5': '0.0327', 'HR@10': '0.0734', 'NDCG@10': '0.0407', 'HR@20': '0.1165', 'NDCG@20': '0.0516'}
2026-10-29 15:26:53,953 - EarlyStopping counter: 1 out of 10
Mode_train:12: 100% 101/101 [00:02<00:00, 40.21it/s]
2026-10-29 15:26:56,528 - {'epoch': 12, 'rec_loss': '6.0565'}
Mode_test:12: 100% 5/5 [00:00<00:00, 24.95it/s]
2026-10-29 15:26:56,842 - {'Epoch': 12, 'HR@5': '0.0495', 'NDCG@5': '0.0312', 'HR@10': '0.0743', 'NDCG@10': '0.0391', 'HR@20': '0.1248', 'NDCG@20': '0.0516'}
2026-10-29 15:26:56,843 - EarlyStopping counter: 2 out of 10
Mode_train:13: 100% 101/101 [00:02<00:00, 41.71it/s]
2026-10-29 15:26:59,320 - {'epoch': 13, 'rec_loss': '5.9429'}
Mode_test:13: 100% 5/5 [00:00<00:00, 24.46it/s]
2026-10-29 15:26:59,649 - {'Epoch': 13, 'HR@5': '0.0450', 'NDCG@5': '0.0302', 'HR@10': '0.0734', 'NDCG@10': '0.0395', 'HR@20': '0.1257', 'NDCG@20': '0.0526'}
2026-10-29 15:26:59,650 - Validation score increased.  Saving model ...
Mode_train:14: 100% 101/101 [00:02<00:00, 41.53it/s]
2026-10-29 15:27:02,157 - {'epoch': 14, 'rec_loss': '5.8432'}
Mode_test:14: 100% 5/5 [00:00<00:00, 24.05it/s]
2026-10-29 15:27:02,481 - {'Epoch': 14, 'HR@5': '0.0523', 'NDCG@5': '0.0321', 'HR@10': '0.0798', 'NDCG@10': '0.0410', 'HR@20': '0.1349', 'NDCG@20': '0.0546'}
2026-10-29 15:27:02,482 - Validation score increased.  Saving model ...
Mode_train:15: 100% 101/101 [00:02<00:00, 40.01it/s]
2026-10-29 15:27:05,083 - {'epoch': 15, 'rec_loss': '5.7504'}
Mode_test:15: 100% 5/5 [00:00<00:00, 26.65it/s]
2026-10-29 15:27:05,388 - {'Epoch': 15, 'HR@5': '0.0514', 'NDCG@5': '0.0332', 'HR@10': '0.0862', 'NDCG@10': '0.0443', 'HR@20': '0.1339', 'NDCG@20': '0.0561'}
2026-10-29 15:27:05,389 - Validation score increased.  Saving model ...
Mode_train:16: 100% 101/101 [00:02<00:00, 40.90it/s]
2026-10-29 15:27:07,935 - {'epoch': 16, 'rec_loss': '5.6740'}
Mode_test:16: 100% 5/5 [00:00<00:00, 25.99it/s]
2026-10-29 15:27:08,246 - {'Epoch': 16, 'HR@5': '0.0560', 'NDCG@5': '0.0368', 'HR@10': '0.0872', 'NDCG@10': '0.0471', 'HR@20': '0.1358', 'NDCG@20': '0.0592'}
2026-10-29 15:27:08,247 - Validation score increased.  Saving model ...
Mode_train:17: 100% 101/101 [00:02<00:00, 39.58it/s]
2026-10-29 15:27:10,877 - {'epoch': 17, 'rec_loss': '5.6153'}
Mode_test:17: 100% 5/5 [00:00<00:00, 22.97it/s]
2026-10-29 15:27:11,228 - {'Epoch': 17, 'HR@5': '0.0532', 'NDCG@5': '0.0331', 'HR@10': '0.0945', 'NDCG@10': '0.0461', 'HR@20': '0.1358', 'NDCG@20': '0.0563'}
2026-10-29 15:27:11,229 - EarlyStopping counter: 1 out of 10
Mode_train:18: 100% 101/101 [00:02<00:00, 39.98it/s]
2026-10-29 15:27:13,824 - {'epoch': 18, 'rec_loss': '5.5588'}
Mode_test:18: 100% 5/5 [00:00<00:00, 27.26it/s]
2026-10-29 15:27:14,135 - {'Epoch': 18, 'HR@5': '0.0550', 'NDCG@5': '0.0378', 'HR@10': '0.0972', 'NDCG@10': '0.0513', 'HR@20': '0.1404', 'NDCG@20': '0.0620'}
2026-10-29 15:27:14,137 - Validation score increased.  Saving model ...
Mode_train:19: 100% 101/101 [00:02<00:00, 39.86it/s]
2026-10-29 15:27:16,756 - {'epoch': 19, 'rec_loss': '5.4987'}
Mode_test:19: 100% 5/5 [00:00<00:00, 26.65it/s]
2026-10-29 15:27:17,061 - {'Epoch': 19, 'HR@5': '0.0569', 'NDCG@5': '0.0383', 'HR@10': '0.0899', 'NDCG@10': '0.0489', 'HR@20': '0.1477', 'NDCG@20': '0.0635'}
2026-10-29 15:27:17,063 - Validation score increased.  Saving model ...
Mode_train:20: 100% 101/101 [00:02<00:00, 41.63it/s]
2026-10-29 15:27:19,561 - {'epoch': 20, 'rec_loss': '5.4628'}
Mode_test:20: 100% 5/5 [00:00<00:00, 24.92it/s]
2026-10-29 15:27:19,880 - {'Epoch': 20, 'HR@5': '0.0587', 'NDCG@5': '0.0394', 'HR@10': '0.0917', 'NDCG@10': '0.0499', 'HR@20': '0.1440', 'NDCG@20': '0.0632'}
2026-10-29 15:27:19,881 - EarlyStopping counter: 1 out of 10
Mode_train:21: 100% 101/101 [00:02<00:00, 40.81it/s]
2026-10-29 15:27:22,429 - {'epoch': 21, 'rec_loss': '5.4138'}
Mode_test:21: 100% 5/5 [00:00<00:00, 24.56it/s]
2026-10-29 15:27:22,775 - {'Epoch': 21, 'HR@5': '0.0624', 'NDCG@5': '0.0384', 'HR@10': '0.0954', 'NDCG@10': '0.0488', 'HR@20': '0.1440', 'NDCG@20': '0.0610'}
2026-10-29 15:27:22,776 - EarlyStopping counter: 2 out of 10
Mode_train:22: 100% 101/101 [00:02<00:00, 39.29it/s]
2026-10-29 15:27:25,406 - {'epoch': 22, 'rec_loss': '5.3854'}
Mode_test:22: 100% 5/5 [00:00<00:00, 24.39it/s]
2026-10-29 15:27:25,740 - {'Epoch': 22, 'HR@5': '0.0532', 'NDCG@5': '0.0361', 'HR@10': '0.0890', 'NDCG@10': '0.0474', 'HR@20': '0.1486', 'NDCG@20': '0.0621'}
2026-10-29 15:27:25,741 - EarlyStopping counter: 3 out of 10
Mode_train:23: 100% 101/101 [00:02<00:00, 41.32it/s]
2026-10-29 15:27:28,257 - {'epoch': 23, 'rec_loss': '5.3467'}
Mode_test:23: 100% 5/5 [00:00<00:00, 24.14it/s]
2026-10-29 15:27:28,583 - {'Epoch': 23, 'HR@5': '0.0633', 'NDCG@5': '0.0396', 'HR@10': '0.0890', 'NDCG@10': '0.0478', 'HR@20': '0.1468', 'NDCG@20': '0.0625'}
2026-10-29 15:27:28,584 - EarlyStopping counter: 4 out of 10
Mode_train:24: 100% 101/101 [00:02<00:00, 40.96it/s]
2026-10-29 15:27:31,118 - {'epoch': 24, 'rec_loss': '5.3211'}
Mode_test:24: 100% 5/5 [00:00<00:00, 24.11it/s]
2026-10-29 15:27:31,444 - {'Epoch': 24, 'HR@5': '0.0550', 'NDCG@5': '0.0371', 'HR@10': '0.0899', 'NDCG@10': '0.0485', 'HR@20': '0.1477', 'NDCG@20': '0.0631'}
2026-10-29 15:27:31,446 - EarlyStopping counter: 5 out of 10
Mode_train:25: 100% 101/101 [00:02<00:00, 40.99it/s]
2026-10-29 15:27:33,984 - {'epoch': 25, 'rec_loss': '5.2818'}
Mode_test:25: 100% 5/5 [00:00<00:00, 25.24it/s]
2026-10-29 15:27:34,309 - {'Epoch': 25, 'HR@5': '0.0596', 'NDCG@5': '0.0400', 'HR@10': '0.0982', 'NDCG@10': '0.0525', 'HR@20': '0.1486', 'NDCG@20': '0.0653'}
2026-10-29 15:27:34,310 - Validation score increased.  Saving model ...
Mode_train:26: 100% 101/101 [00:02<00:00, 39.78it/s]
2026-10-29 15:27:36,925 - {'epoch': 26, 'rec_loss': '5.2635'}
Mode_test:26: 100% 5/5 [00:00<00:00, 25.29it/s]
2026-10-29 15:27:37,245 - {'Epoch': 26, 'HR@5': '0.0642', 'NDCG@5': '0.0421', 'HR@10': '0.0982', 'NDCG@10': '0.0530', 'HR@20': '0.1431', 'NDCG@20': '0.0644'}
2026-10-29 15:27:37,246 - EarlyStopping counter: 1 out of 10
Mode_train:27: 100% 101/101 [00:02<00:00, 41.43it/s]
2026-10-29 15:27:39,751 - {'epoch': 27, 'rec_loss': '5.2315'}
Mode_test:27: 100% 5/5 [00:00<00:00, 27.01it/s]
2026-10-29 15:27:40,061 - {'Epoch': 27, 'HR@5': '0.0651', 'NDCG@5': '0.0427', 'HR@10': '0.0991', 'NDCG@10': '0.0537', 'HR@20': '0.1532', 'NDCG@20': '0.0674'}
2026-10-29 15:27:40,062 - Validation score increased.  Saving model ...
Mode_train:28: 100% 101/101 [00:02<00:00, 38.61it/s]
2026-10-29 15:27:42,753 - {'epoch': 28, 'rec_loss': '5.2197'}
Mode_test:28: 100% 5/5 [00:00<00:00, 26.10it/s]
2026-10-29 15:27:43,063 - {'Epoch': 28, 'HR@5': '0.0670', 'NDCG@5': '0.0441', 'HR@10': '0.0982', 'NDCG@10': '0.0542', 'HR@20': '0.1505', 'NDCG@20': '0.0674'}
2026-10-29 15:27:43,064 - Validation score increased.  Saving model ...
Mode_train:29: 100% 101/101 [00:02<00:00, 39.81it/s]
2026-10-29 15:27:45,674 - {'epoch': 29, 'rec_loss': '5.1895'}
Mode_test:29: 100% 5/5 [00:00<00:00, 25.90it/s]
2026-10-29 15:27:45,995 - {'Epoch': 29, 'HR@5': '0.0633', 'NDCG@5': '0.0410', 'HR@10': '0.1000', 'NDCG@10': '0.0527', 'HR@20': '0.1505', 'NDCG@20': '0.0655'}
2026-10-29 15:27:45,997 - EarlyStopping counter: 1 out of 10
Mode_train:30: 100% 101/101 [00:02<00:00, 40.52it/s]
2026-10-29 15:27:48,556 - {'epoch': 30, 'rec_loss': '5.1679'}
Mode_test:30: 100% 5/5 [00:00<00:00, 23.66it/s]
2026-10-29 15:27:48,897 - {'Epoch': 30, 'HR@5': '0.0670', 'NDCG@5': '0.0431', 'HR@10': '0.1037', 'NDCG@10': '0.0548', 'HR@20': '0.1486', 'NDCG@20': '0.0659'}
2026-10-29 15:27:48,898 - EarlyStopping counter: 2 out of 10
Mode_train:31: 100% 101/101 [00:02<00:00, 41.16it/s]
2026-10-29 15:27:51,418 - {'epoch': 31, 'rec_loss': '5.1520'}
Mode_test:31: 100% 5/5 [00:00<00:00, 25.44it/s]
2026-10-29 15:27:51,739 - {'Epoch': 31, 'HR@5': '0.0615', 'NDCG@5': '0.0416', 'HR@10': '0.1064', 'NDCG@10': '0.0560', 'HR@20': '0.1486', 'NDCG@20': '0.0665'}
2026-10-29 15:27:51,741 - EarlyStopping counter: 3 out of 10
Mode_train:32: 100% 101/101 [00:02<00:00, 41.30it/s]
2026-10-29 15:27:54,267 - {'epoch': 32, 'rec_loss': '5.1331'}
Mode_test:32: 100% 5/5 [00:00<00:00, 26.73it/s]
2026-10-29 15:27:54,580 - {'Epoch': 32, 'HR@5': '0.0633', 'NDCG@5': '0.0422', 'HR@10': '0.1055', 'NDCG@10': '0.0559', 'HR@20': '0.1541', 'NDCG@20': '0.0681'}
2026-10-29 15:27:54,581 - Validation score increased.  Saving model ...
Mode_train:33: 100% 101/101 [00:02<00:00, 39.92it/s]
2026-10-29 15:27:57,185 - {'epoch': 33, 'rec_loss': '5.1174'}
Mode_test:33: 100% 5/5 [00:00<00:00, 25.32it/s]
2026-10-29 15:27:57,496 - {'Epoch': 33, 'HR@5': '0.0596', 'NDCG@5': '0.0401', 'HR@10': '0.0927', 'NDCG@10': '0.0509', 'HR@20': '0.1514', 'NDCG@20': '0.0659'}
2026-10-29 15:27:57,497 - EarlyStopping counter: 1 out of 10
Mode_train:34: 100% 101/101 [00:02<00:00, 41.01it/s]
2026-10-29 15:28:00,032 - {'epoch': 34, 'rec_loss': '5.0966'}
Mode_test:34: 100% 5/5 [00:00<00:00, 22.86it/s]
2026-10-29 15:28:00,382 - {'Epoch': 34, 'HR@5': '0.0661', 'NDCG@5': '0.0437', 'HR@10': '0.0963', 'NDCG@10': '0.0534', 'HR@20': '0.1459', 'NDCG@20': '0.0660'}
2026-10-29 15:28:00,383 - EarlyStopping counter: 2 out of 10
Mode_train:35: 100% 101/101 [00:02<00:00, 41.31it/s]
2026-10-29 15:28:02,904 - {'epoch': 35, 'rec_loss': '5.0920'}
Mode_test:35: 100% 5/5 [00:00<00:00, 25.88it/s]
2026-10-29 15:28:03,214 - {'Epoch': 35, 'HR@5': '0.0679', 'NDCG@5': '0.0459', 'HR@10': '0.0936', 'NDCG@10': '0.0542', 'HR@20': '0.1523', 'NDCG@20': '0.0692'}
2026-10-29 15:28:03,215 - Validation score increased.  Saving model ...
Mode_train:36: 100% 101/101 [00:02<00:00, 39.82it/s]
2026-10-29 15:28:05,838 - {'epoch': 36, 'rec_loss': '5.0583'}
Mode_test:36: 100% 5/5 [00:00<00:00, 23.58it/s]
2026-10-29 15:28:06,168 - {'Epoch': 36, 'HR@5': '0.0642', 'NDCG@5': '0.0434', 'HR@10': '0.0982', 'NDCG@10': '0.0541', 'HR@20': '0.1486', 'NDCG@20': '0.0668'}
2026-10-29 15:28:06,169 - EarlyStopping counter: 1 out of 10
Mode_train:37: 100% 101/101 [00:02<00:00, 40.60it/s]
2026-10-29 15:28:08,716 - {'epoch': 37, 'rec_loss': '5.0360'}
Mode_test:37: 100% 5/5 [00:00<00:00, 27.45it/s]
2026-10-29 15:28:09,017 - {'Epoch': 37, 'HR@5': '0.0651', 'NDCG@5': '0.0436', 'HR@10': '0.1000', 'NDCG@10': '0.0547', 'HR@20': '0.1468', 'NDCG@20': '0.0664'}
2026-10-29 15:28:09,018 - EarlyStopping counter: 2 out of 10
Mode_train:38: 100% 101/101 [00:02<00:00, 38.29it/s]
2026-10-29 15:28:11,724 - {'epoch': 38, 'rec_loss': '5.0342'}
Mode_test:38: 100% 5/5 [00:00<00:00, 25.57it/s]
2026-10-29 15:28:12,045 - {'Epoch': 38, 'HR@5': '0.0596', 'NDCG@5': '0.0402', 'HR@10': '0.0954', 'NDCG@10': '0.0518', 'HR@20': '0.1477', 'NDCG@20': '0.0651'}
2026-10-29 15:28:12,047 - EarlyStopping counter: 3 out of 10
Mode_train:39: 100% 101/101 [00:02<00:00, 39.64it/s]
2026-10-29 15:28:14,670 - {'epoch': 39, 'rec_loss': '5.0272'}
Mode_test:39: 100% 5/5 [00:00<00:00, 24.38it/s]
2026-10-29 15:28:14,997 - {'Epoch': 39, 'HR@5': '0.0670', 'NDCG@5': '0.0443', 'HR@10': '0.1037', 'NDCG@10': '0.0559', 'HR@20': '0.1486', 'NDCG@20': '0.0673'}
2026-10-29 15:28:14,998 - EarlyStopping counter: 4 out of 10
Mode_train:40: 100% 101/101 [00:02<00:00, 40.46it/s]
2026-10-29 15:28:17,565 - {'epoch': 40, 'rec_loss': '5.0137'}
Mode_test:40: 100% 5/5 [00:00<00:00, 25.02it/s]
2026-10-29 15:28:17,880 - {'Epoch': 40, 'HR@5': '0.0624', 'NDCG@5': '0.0422', 'HR@10': '0.1018', 'NDCG@10': '0.0547', 'HR@20': '0.1514', 'NDCG@20': '0.0671'}
2026-10-29 15:28:17,881 - EarlyStopping counter: 5 out of 10
Mode_train:41: 100% 101/101 [00:02<00:00, 41.44it/s]
2026-10-29 15:28:20,391 - {'epoch': 41, 'rec_loss': '5.0081'}
Mode_test:41: 100% 5/5 [00:00<00:00, 24.75it/s]
2026-10-29 15:28:20,716 - {'Epoch': 41, 'HR@5': '0.0633', 'NDCG@5': '0.0418', 'HR@10': '0.1000', 'NDCG@10': '0.0535', 'HR@20': '0.1514', 'NDCG@20': '0.0663'}
2026-10-29 15:28:20,717 - EarlyStopping counter: 6 out of 10
Mode_train:42: 100% 101/101 [00:02<00:00, 41.48it/s]
2026-10-29 15:28:23,227 - {'epoch': 42, 'rec_loss': '4.9897'}
Mode_test:42: 100% 5/5 [00:00<00:00, 26.22it/s]
2026-10-29 15:28:23,530 - {'Epoch': 42, 'HR@5': '0.0633', 'NDCG@5': '0.0419', 'HR@10': '0.0991', 'NDCG@10': '0.0535', 'HR@20': '0.1505', 'NDCG@20': '0.0664'}
2026-10-29 15:28:23,532 - EarlyStopping counter: 7 out of 10
Mode_train:43: 100% 101/101 [00:02<00:00, 40.87it/s]
2026-10-29 15:28:26,068 - {'epoch': 43, 'rec_loss': '4.9797'}
Mode_test:43: 100% 5/5 [00:00<00:00, 22.33it/s]

In [8]:
!python main.py --data_name LastFM --lr 0.001 --alpha 0.9 --c 3 --num_attention_heads 1 --seed 44 --train_name BSARec_LastFM_final_s44

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:424: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
2026-10-29 15:28:35,238 - Namespace(data_dir='./data/', output_dir='output/', data_name='LastFM', do_eval=False, load_model=None, train_name='BSARec_LastFM_final_s44', num_items=10, num_users=1091, lr=0.001, batch_size=256, epochs=200, no_cuda=False, log_freq=1, patience=10, num_workers=4, seed=44, weight_decay=0.0, adam_beta1=0.9, adam_beta2=0.999, gpu_id='0', variance=5, model_type='BSARec', max_seq_length=50, hidden_size=64, num_hidden_layers=2, hidden_act='gelu', num_attention_heads=1, attention_probs_dropout_prob=0.5, hidden_dropout_prob=0.5, initializer_range=0.02, c=3, alpha=0.9, cuda_condition=True, data_file='./data/LastFM.txt', item_size=3647, checkpoint_path='output/BSARec_LastFM_final_s44.pt', same_target_path='./data/LastFM_same_target.npy')
2026-10-29 15:28:35,249 - BSARecModel(
  (item_embeddings): Embedding(3647, 64, padding_idx=0)
  (position_embeddings): Embedding(50, 64)
  (LayerNorm): LayerNorm()
  (dropout): Dropout(p=0.5, inplace=False)
  (item_encoder): BSARecEncoder(
    (blocks): ModuleList(
      (0-1): 2 x BSARecBlock(
        (layer): BSARecLayer(
          (filter_layer): FrequencyLayer(
            (out_dropout): Dropout(p=0.5, inplace=False)
            (LayerNorm): LayerNorm()
          )
          (attention_layer): MultiHeadAttention(
            (query): Linear(in_features=64, out_features=64, bias=True)
            (key): Linear(in_features=64, out_features=64, bias=True)
            (value): Linear(in_features=64, out_features=64, bias=True)
            (softmax): Softmax(dim=-1)
            (attn_dropout): Dropout(p=0.5, inplace=False)
            (dense): Linear(in_features=64, out_features=64, bias=True)
            (LayerNorm): LayerNorm((64,), eps=1e-12, elementwise_affine=True)
            (out_dropout): Dropout(p=0.5, inplace=False)
          )
        )
        (feed_forward): FeedForward(
          (dense_1): Linear(in_features=64, out_features=256, bias=True)
          (dense_2): Linear(in_features=256, out_features=64, bias=True)
          (LayerNorm): LayerNorm()
          (dropout): Dropout(p=0.5, inplace=False)
        )
      )
    )
  )
)
2026-10-29 15:28:36,425 - Total Parameters: 337088
/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
Mode_train:0: 100% 101/101 [00:02<00:00, 36.29it/s]
2026-10-29 15:28:39,296 - {'epoch': 0, 'rec_loss': '7.9742'}
Mode_test:0: 100% 5/5 [00:00<00:00, 25.31it/s]
2026-10-29 15:28:39,624 - {'Epoch': 0, 'HR@5': '0.0229', 'NDCG@5': '0.0127', 'HR@10': '0.0367', 'NDCG@10': '0.0171', 'HR@20': '0.0606', 'NDCG@20': '0.0231'}
2026-10-29 15:28:39,625 - Validation score increased.  Saving model ...
Mode_train:1: 100% 101/101 [00:02<00:00, 38.42it/s]
2026-10-29 15:28:42,331 - {'epoch': 1, 'rec_loss': '7.6691'}
Mode_test:1: 100% 5/5 [00:00<00:00, 24.22it/s]
2026-10-29 15:28:42,658 - {'Epoch': 1, 'HR@5': '0.0211', 'NDCG@5': '0.0132', 'HR@10': '0.0394', 'NDCG@10': '0.0192', 'HR@20': '0.0578', 'NDCG@20': '0.0236'}
2026-10-29 15:28:42,659 - Validation score increased.  Saving model ...
Mode_train:2: 100% 101/101 [00:02<00:00, 41.05it/s]
2026-10-29 15:28:45,197 - {'epoch': 2, 'rec_loss': '7.4871'}
Mode_test:2: 100% 5/5 [00:00<00:00, 26.18it/s]
2026-10-29 15:28:45,503 - {'Epoch': 2, 'HR@5': '0.0211', 'NDCG@5': '0.0118', 'HR@10': '0.0367', 'NDCG@10': '0.0170', 'HR@20': '0.0541', 'NDCG@20': '0.0213'}
2026-10-29 15:28:45,504 - EarlyStopping counter: 1 out of 10
Mode_train:3: 100% 101/101 [00:02<00:00, 40.13it/s]
2026-10-29 15:28:48,090 - {'epoch': 3, 'rec_loss': '7.3056'}
Mode_test:3: 100% 5/5 [00:00<00:00, 22.94it/s]
2026-10-29 15:28:48,432 - {'Epoch': 3, 'HR@5': '0.0294', 'NDCG@5': '0.0196', 'HR@10': '0.0450', 'NDCG@10': '0.0248', 'HR@20': '0.0743', 'NDCG@20': '0.0322'}
2026-10-29 15:28:48,434 - Validation score increased.  Saving model ...
Mode_train:4: 100% 101/101 [00:02<00:00, 40.79it/s]
2026-10-29 15:28:50,983 - {'epoch': 4, 'rec_loss': '7.1035'}
Mode_test:4: 100% 5/5 [00:00<00:00, 26.28it/s]
2026-10-29 15:28:51,295 - {'Epoch': 4, 'HR@5': '0.0367', 'NDCG@5': '0.0223', 'HR@10': '0.0615', 'NDCG@10': '0.0301', 'HR@20': '0.0927', 'NDCG@20': '0.0380'}
2026-10-29 15:28:51,296 - Validation score increased.  Saving model ...
Mode_train:5: 100% 101/101 [00:02<00:00, 40.62it/s]
2026-10-29 15:28:53,857 - {'epoch': 5, 'rec_loss': '6.8978'}
Mode_test:5: 100% 5/5 [00:00<00:00, 25.37it/s]
2026-10-29 15:28:54,182 - {'Epoch': 5, 'HR@5': '0.0495', 'NDCG@5': '0.0321', 'HR@10': '0.0743', 'NDCG@10': '0.0402', 'HR@20': '0.1018', 'NDCG@20': '0.0470'}
2026-10-29 15:28:54,183 - Validation score increased.  Saving model ...
Mode_train:6: 100% 101/101 [00:02<00:00, 40.10it/s]
2026-10-29 15:28:56,776 - {'epoch': 6, 'rec_loss': '6.7028'}
Mode_test:6: 100% 5/5 [00:00<00:00, 25.75it/s]
2026-10-29 15:28:57,091 - {'Epoch': 6, 'HR@5': '0.0459', 'NDCG@5': '0.0309', 'HR@10': '0.0771', 'NDCG@10': '0.0410', 'HR@20': '0.1046', 'NDCG@20': '0.0478'}
2026-10-29 15:28:57,093 - Validation score increased.  Saving model ...
Mode_train:7: 100% 101/101 [00:02<00:00, 41.07it/s]
2026-10-29 15:28:59,616 - {'epoch': 7, 'rec_loss': '6.5086'}
Mode_test:7: 100% 5/5 [00:00<00:00, 24.00it/s]
2026-10-29 15:28:59,945 - {'Epoch': 7, 'HR@5': '0.0486', 'NDCG@5': '0.0336', 'HR@10': '0.0752', 'NDCG@10': '0.0422', 'HR@20': '0.1073', 'NDCG@20': '0.0502'}
2026-10-29 15:28:59,946 - Validation score increased.  Saving model ...
Mode_train:8: 100% 101/101 [00:02<00:00, 41.30it/s]
2026-10-29 15:29:02,466 - {'epoch': 8, 'rec_loss': '6.3342'}
Mode_test:8: 100% 5/5 [00:00<00:00, 25.63it/s]
2026-10-29 15:29:02,789 - {'Epoch': 8, 'HR@5': '0.0495', 'NDCG@5': '0.0329', 'HR@10': '0.0798', 'NDCG@10': '0.0426', 'HR@20': '0.1165', 'NDCG@20': '0.0518'}
2026-10-29 15:29:02,790 - Validation score increased.  Saving model ...
Mode_train:9: 100% 101/101 [00:02<00:00, 41.46it/s]
2026-10-29 15:29:05,305 - {'epoch': 9, 'rec_loss': '6.1883'}
Mode_test:9: 100% 5/5 [00:00<00:00, 26.69it/s]
2026-10-29 15:29:05,615 - {'Epoch': 9, 'HR@5': '0.0495', 'NDCG@5': '0.0322', 'HR@10': '0.0734', 'NDCG@10': '0.0401', 'HR@20': '0.1211', 'NDCG@20': '0.0521'}
2026-10-29 15:29:05,616 - Validation score increased.  Saving model ...
Mode_train:10: 100% 101/101 [00:02<00:00, 38.88it/s]
2026-10-29 15:29:08,283 - {'epoch': 10, 'rec_loss': '6.0459'}
Mode_test:10: 100% 5/5 [00:00<00:00, 24.87it/s]
2026-10-29 15:29:08,612 - {'Epoch': 10, 'HR@5': '0.0450', 'NDCG@5': '0.0314', 'HR@10': '0.0716', 'NDCG@10': '0.0401', 'HR@20': '0.1128', 'NDCG@20': '0.0507'}
2026-10-29 15:29:08,613 - EarlyStopping counter: 1 out of 10
Mode_train:11: 100% 101/101 [00:03<00:00, 25.74it/s]
2026-10-29 15:29:12,604 - {'epoch': 11, 'rec_loss': '5.9260'}
Mode_test:11: 100% 5/5 [00:00<00:00, 17.33it/s]
2026-10-29 15:29:13,190 - {'Epoch': 11, 'HR@5': '0.0468', 'NDCG@5': '0.0283', 'HR@10': '0.0862', 'NDCG@10': '0.0411', 'HR@20': '0.1229', 'NDCG@20': '0.0504'}
2026-10-29 15:29:13,192 - EarlyStopping counter: 2 out of 10
Mode_train:12: 100% 101/101 [00:04<00:00, 22.42it/s]
2026-10-29 15:29:17,807 - {'epoch': 12, 'rec_loss': '5.8190'}
Mode_test:12: 100% 5/5 [00:00<00:00, 26.02it/s]
2026-10-29 15:29:18,130 - {'Epoch': 12, 'HR@5': '0.0505', 'NDCG@5': '0.0338', 'HR@10': '0.0817', 'NDCG@10': '0.0437', 'HR@20': '0.1294', 'NDCG@20': '0.0558'}
2026-10-29 15:29:18,131 - Validation score increased.  Saving model ...
Mode_train:13: 100% 101/101 [00:02<00:00, 40.17it/s]
2026-10-29 15:29:20,721 - {'epoch': 13, 'rec_loss': '5.7178'}
Mode_test:13: 100% 5/5 [00:00<00:00, 26.47it/s]
2026-10-29 15:29:21,039 - {'Epoch': 13, 'HR@5': '0.0532', 'NDCG@5': '0.0344', 'HR@10': '0.0908', 'NDCG@10': '0.0463', 'HR@20': '0.1284', 'NDCG@20': '0.0559'}
2026-10-29 15:29:21,040 - Validation score increased.  Saving model ...
Mode_train:14: 100% 101/101 [00:02<00:00, 40.69it/s]
2026-10-29 15:29:23,603 - {'epoch': 14, 'rec_loss': '5.6367'}
Mode_test:14: 100% 5/5 [00:00<00:00, 24.32it/s]
2026-10-29 15:29:23,926 - {'Epoch': 14, 'HR@5': '0.0532', 'NDCG@5': '0.0362', 'HR@10': '0.0872', 'NDCG@10': '0.0470', 'HR@20': '0.1275', 'NDCG@20': '0.0572'}
2026-10-29 15:29:23,927 - Validation score increased.  Saving model ...
Mode_train:15: 100% 101/101 [00:02<00:00, 40.79it/s]
2026-10-29 15:29:26,479 - {'epoch': 15, 'rec_loss': '5.5728'}
Mode_test:15: 100% 5/5 [00:00<00:00, 24.63it/s]
2026-10-29 15:29:26,799 - {'Epoch': 15, 'HR@5': '0.0523', 'NDCG@5': '0.0343', 'HR@10': '0.0982', 'NDCG@10': '0.0492', 'HR@20': '0.1349', 'NDCG@20': '0.0586'}
2026-10-29 15:29:26,801 - Validation score increased.  Saving model ...
Mode_train:16: 100% 101/101 [00:02<00:00, 39.90it/s]
2026-10-29 15:29:29,433 - {'epoch': 16, 'rec_loss': '5.5001'}
Mode_test:16: 100% 5/5 [00:00<00:00, 24.84it/s]
2026-10-29 15:29:29,753 - {'Epoch': 16, 'HR@5': '0.0541', 'NDCG@5': '0.0359', 'HR@10': '0.0881', 'NDCG@10': '0.0466', 'HR@20': '0.1266', 'NDCG@20': '0.0564'}
2026-10-29 15:29:29,754 - EarlyStopping counter: 1 out of 10
Mode_train:17: 100% 101/101 [00:02<00:00, 40.37it/s]
2026-10-29 15:29:32,319 - {'epoch': 17, 'rec_loss': '5.4603'}
Mode_test:17: 100% 5/5 [00:00<00:00, 24.82it/s]
2026-10-29 15:29:32,644 - {'Epoch': 17, 'HR@5': '0.0596', 'NDCG@5': '0.0373', 'HR@10': '0.0982', 'NDCG@10': '0.0496', 'HR@20': '0.1367', 'NDCG@20': '0.0595'}
2026-10-29 15:29:32,646 - Validation score increased.  Saving model ...
Mode_train:18: 100% 101/101 [00:02<00:00, 41.15it/s]
2026-10-29 15:29:35,181 - {'epoch': 18, 'rec_loss': '5.4108'}
Mode_test:18: 100% 5/5 [00:00<00:00, 24.80it/s]
2026-10-29 15:29:35,504 - {'Epoch': 18, 'HR@5': '0.0670', 'NDCG@5': '0.0428', 'HR@10': '0.1009', 'NDCG@10': '0.0535', 'HR@20': '0.1468', 'NDCG@20': '0.0649'}
2026-10-29 15:29:35,505 - Validation score increased.  Saving model ...
Mode_train:19: 100% 101/101 [00:02<00:00, 38.56it/s]
2026-10-29 15:29:38,193 - {'epoch': 19, 'rec_loss': '5.3753'}
Mode_test:19: 100% 5/5 [00:00<00:00, 25.07it/s]
2026-10-29 15:29:38,536 - {'Epoch': 19, 'HR@5': '0.0578', 'NDCG@5': '0.0372', 'HR@10': '0.0899', 'NDCG@10': '0.0475', 'HR@20': '0.1394', 'NDCG@20': '0.0599'}
2026-10-29 15:29:38,538 - EarlyStopping counter: 1 out of 10
Mode_train:20: 100% 101/101 [00:02<00:00, 39.42it/s]
2026-10-29 15:29:41,173 - {'epoch': 20, 'rec_loss': '5.3375'}
Mode_test:20: 100% 5/5 [00:00<00:00, 24.07it/s]
2026-10-29 15:29:41,511 - {'Epoch': 20, 'HR@5': '0.0651', 'NDCG@5': '0.0395', 'HR@10': '0.0963', 'NDCG@10': '0.0495', 'HR@20': '0.1358', 'NDCG@20': '0.0593'}
2026-10-29 15:29:41,512 - EarlyStopping counter: 2 out of 10
Mode_train:21: 100% 101/101 [00:02<00:00, 38.47it/s]
2026-10-29 15:29:44,207 - {'epoch': 21, 'rec_loss': '5.3053'}
Mode_test:21: 100% 5/5 [00:00<00:00, 25.50it/s]
2026-10-29 15:29:44,536 - {'Epoch': 21, 'HR@5': '0.0642', 'NDCG@5': '0.0383', 'HR@10': '0.0963', 'NDCG@10': '0.0486', 'HR@20': '0.1413', 'NDCG@20': '0.0599'}
2026-10-29 15:29:44,537 - EarlyStopping counter: 3 out of 10
Mode_train:22: 100% 101/101 [00:02<00:00, 40.63it/s]
2026-10-29 15:29:47,093 - {'epoch': 22, 'rec_loss': '5.2687'}
Mode_test:22: 100% 5/5 [00:00<00:00, 20.18it/s]
2026-10-29 15:29:47,455 - {'Epoch': 22, 'HR@5': '0.0661', 'NDCG@5': '0.0399', 'HR@10': '0.0982', 'NDCG@10': '0.0502', 'HR@20': '0.1431', 'NDCG@20': '0.0615'}
2026-10-29 15:29:47,456 - EarlyStopping counter: 4 out of 10
Mode_train:23: 100% 101/101 [00:02<00:00, 40.73it/s]
2026-10-29 15:29:50,009 - {'epoch': 23, 'rec_loss': '5.2493'}
Mode_test:23: 100% 5/5 [00:00<00:00, 26.23it/s]
2026-10-29 15:29:50,323 - {'Epoch': 23, 'HR@5': '0.0651', 'NDCG@5': '0.0387', 'HR@10': '0.0972', 'NDCG@10': '0.0489', 'HR@20': '0.1431', 'NDCG@20': '0.0607'}
2026-10-29 15:29:50,324 - EarlyStopping counter: 5 out of 10
Mode_train:24: 100% 101/101 [00:02<00:00, 39.88it/s]
2026-10-29 15:29:52,919 - {'epoch': 24, 'rec_loss': '5.2168'}
Mode_test:24: 100% 5/5 [00:00<00:00, 24.82it/s]
2026-10-29 15:29:53,242 - {'Epoch': 24, 'HR@5': '0.0688', 'NDCG@5': '0.0406', 'HR@10': '0.0972', 'NDCG@10': '0.0498', 'HR@20': '0.1422', 'NDCG@20': '0.0611'}
2026-10-29 15:29:53,244 - EarlyStopping counter: 6 out of 10
Mode_train:25: 100% 101/101 [00:02<00:00, 42.05it/s]
2026-10-29 15:29:55,712 - {'epoch': 25, 'rec_loss': '5.1936'}
Mode_test:25: 100% 5/5 [00:00<00:00, 25.96it/s]
2026-10-29 15:29:56,019 - {'Epoch': 25, 'HR@5': '0.0578', 'NDCG@5': '0.0377', 'HR@10': '0.0927', 'NDCG@10': '0.0490', 'HR@20': '0.1431', 'NDCG@20': '0.0618'}
2026-10-29 15:29:56,020 - EarlyStopping counter: 7 out of 10
Mode_train:26: 100% 101/101 [00:02<00:00, 39.75it/s]
2026-10-29 15:29:58,632 - {'epoch': 26, 'rec_loss': '5.1764'}
Mode_test:26: 100% 5/5 [00:00<00:00, 26.27it/s]
2026-10-29 15:29:58,946 - {'Epoch': 26, 'HR@5': '0.0624', 'NDCG@5': '0.0401', 'HR@10': '0.1028', 'NDCG@10': '0.0530', 'HR@20': '0.1495', 'NDCG@20': '0.0649'}
2026-10-29 15:29:58,947 - EarlyStopping counter: 8 out of 10
Mode_train:27: 100% 101/101 [00:02<00:00, 40.11it/s]
2026-10-29 15:30:01,531 - {'epoch': 27, 'rec_loss': '5.1539'}
Mode_test:27: 100% 5/5 [00:00<00:00, 25.62it/s]
2026-10-29 15:30:01,854 - {'Epoch': 27, 'HR@5': '0.0642', 'NDCG@5': '0.0413', 'HR@10': '0.1046', 'NDCG@10': '0.0544', 'HR@20': '0.1532', 'NDCG@20': '0.0668'}
2026-10-29 15:30:01,855 - Validation score increased.  Saving model ...
Mode_train:28: 100% 101/101 [00:02<00:00, 41.03it/s]
2026-10-29 15:30:04,391 - {'epoch': 28, 'rec_loss': '5.1273'}
Mode_test:28: 100% 5/5 [00:00<00:00, 23.44it/s]
2026-10-29 15:30:04,731 - {'Epoch': 28, 'HR@5': '0.0606', 'NDCG@5': '0.0374', 'HR@10': '0.0982', 'NDCG@10': '0.0496', 'HR@20': '0.1514', 'NDCG@20': '0.0628'}
2026-10-29 15:30:04,732 - EarlyStopping counter: 1 out of 10
Mode_train:29: 100% 101/101 [00:03<00:00, 33.12it/s]
2026-10-29 15:30:07,855 - {'epoch': 29, 'rec_loss': '5.1140'}
Mode_test:29: 100% 5/5 [00:00<00:00, 26.50it/s]
2026-10-29 15:30:08,169 - {'Epoch': 29, 'HR@5': '0.0587', 'NDCG@5': '0.0371', 'HR@10': '0.1009', 'NDCG@10': '0.0506', 'HR@20': '0.1495', 'NDCG@20': '0.0628'}
2026-10-29 15:30:08,170 - EarlyStopping counter: 2 out of 10
Mode_train:30: 100% 101/101 [00:02<00:00, 40.46it/s]
2026-10-29 15:30:10,739 - {'epoch': 30, 'rec_loss': '5.0937'}
Mode_test:30: 100% 5/5 [00:00<00:00, 23.81it/s]
2026-10-29 15:30:11,077 - {'Epoch': 30, 'HR@5': '0.0624', 'NDCG@5': '0.0395', 'HR@10': '0.0963', 'NDCG@10': '0.0504', 'HR@20': '0.1550', 'NDCG@20': '0.0651'}
2026-10-29 15:30:11,078 - EarlyStopping counter: 3 out of 10
Mode_train:31: 100% 101/101 [00:02<00:00, 37.68it/s]
2026-10-29 15:30:13,829 - {'epoch': 31, 'rec_loss': '5.0703'}
Mode_test:31: 100% 5/5 [00:00<00:00, 24.45it/s]
2026-10-29 15:30:14,155 - {'Epoch': 31, 'HR@5': '0.0541', 'NDCG@5': '0.0365', 'HR@10': '0.0963', 'NDCG@10': '0.0503', 'HR@20': '0.1477', 'NDCG@20': '0.0633'}
2026-10-29 15:30:14,156 - EarlyStopping counter: 4 out of 10
Mode_train:32: 100% 101/101 [00:02<00:00, 39.94it/s]
2026-10-29 15:30:16,748 - {'epoch': 32, 'rec_loss': '5.0609'}
Mode_test:32: 100% 5/5 [00:00<00:00, 24.99it/s]
2026-10-29 15:30:17,071 - {'Epoch': 32, 'HR@5': '0.0578', 'NDCG@5': '0.0371', 'HR@10': '0.0917', 'NDCG@10': '0.0482', 'HR@20': '0.1550', 'NDCG@20': '0.0640'}
2026-10-29 15:30:17,072 - EarlyStopping counter: 5 out of 10
Mode_train:33: 100% 101/101 [00:02<00:00, 39.38it/s]
2026-10-29 15:30:19,706 - {'epoch': 33, 'rec_loss': '5.0411'}
Mode_test:33: 100% 5/5 [00:00<00:00, 25.58it/s]
2026-10-29 15:30:20,023 - {'Epoch': 33, 'HR@5': '0.0606', 'NDCG@5': '0.0379', 'HR@10': '0.0899', 'NDCG@10': '0.0472', 'HR@20': '0.1505', 'NDCG@20': '0.0623'}
2026-10-29 15:30:20,024 - EarlyStopping counter: 6 out of 10
Mode_train:34: 100% 101/101 [00:02<00:00, 40.25it/s]
2026-10-29 15:30:22,604 - {'epoch': 34, 'rec_loss': '5.0409'}
Mode_test:34: 100% 5/5 [00:00<00:00, 26.54it/s]
2026-10-29 15:30:22,914 - {'Epoch': 34, 'HR@5': '0.0569', 'NDCG@5': '0.0386', 'HR@10': '0.0963', 'NDCG@10': '0.0512', 'HR@20': '0.1560', 'NDCG@20': '0.0663'}
2026-10-29 15:30:22,915 - EarlyStopping counter: 7 out of 10
Mode_train:35: 100% 101/101 [00:02<00:00, 40.21it/s]
2026-10-29 15:30:25,500 - {'epoch': 35, 'rec_loss': '5.0094'}
Mode_test:35: 100% 5/5 [00:00<00:00, 25.42it/s]
2026-10-29 15:30:25,844 - {'Epoch': 35, 'HR@5': '0.0651', 'NDCG@5': '0.0423', 'HR@10': '0.1009', 'NDCG@10': '0.0537', 'HR@20': '0.1541', 'NDCG@20': '0.0669'}
2026-10-29 15:30:25,846 - Validation score increased.  Saving model ...
Mode_train:36: 100% 101/101 [00:02<00:00, 37.63it/s]
2026-10-29 15:30:28,608 - {'epoch': 36, 'rec_loss': '5.0025'}
Mode_test:36: 100% 5/5 [00:00<00:00, 23.08it/s]
2026-10-29 15:30:28,958 - {'Epoch': 36, 'HR@5': '0.0587', 'NDCG@5': '0.0393', 'HR@10': '0.0972', 'NDCG@10': '0.0515', 'HR@20': '0.1523', 'NDCG@20': '0.0655'}
2026-10-29 15:30:28,959 - EarlyStopping counter: 1 out of 10
Mode_train:37: 100% 101/101 [00:02<00:00, 40.51it/s]
2026-10-29 15:30:31,521 - {'epoch': 37, 'rec_loss': '4.9994'}
Mode_test:37: 100% 5/5 [00:00<00:00, 26.55it/s]
2026-10-29 15:30:31,854 - {'Epoch': 37, 'HR@5': '0.0587', 'NDCG@5': '0.0396', 'HR@10': '0.0963', 'NDCG@10': '0.0514', 'HR@20': '0.1532', 'NDCG@20': '0.0657'}
2026-10-29 15:30:31,855 - EarlyStopping counter: 2 out of 10
Mode_train:38: 100% 101/101 [00:02<00:00, 40.56it/s]
2026-10-29 15:30:34,411 - {'epoch': 38, 'rec_loss': '4.9789'}
Mode_test:38: 100% 5/5 [00:00<00:00, 23.88it/s]
2026-10-29 15:30:34,740 - {'Epoch': 38, 'HR@5': '0.0624', 'NDCG@5': '0.0432', 'HR@10': '0.0991', 'NDCG@10': '0.0548', 'HR@20': '0.1532', 'NDCG@20': '0.0685'}
2026-10-29 15:30:34,741 - Validation score increased.  Saving model ...
Mode_train:39: 100% 101/101 [00:02<00:00, 39.73it/s]
2026-10-29 15:30:37,360 - {'epoch': 39, 'rec_loss': '4.9670'}
Mode_test:39: 100% 5/5 [00:00<00:00, 24.84it/s]
2026-10-29 15:30:37,688 - {'Epoch': 39, 'HR@5': '0.0615', 'NDCG@5': '0.0416', 'HR@10': '0.1009', 'NDCG@10': '0.0543', 'HR@20': '0.1514', 'NDCG@20': '0.0670'}
2026-10-29 15:30:37,689 - EarlyStopping counter: 1 out of 10
Mode_train:40: 100% 101/101 [00:02<00:00, 40.05it/s]
2026-10-29 15:30:40,278 - {'epoch': 40, 'rec_loss': '4.9491'}
Mode_test:40: 100% 5/5 [00:00<00:00, 24.95it/s]
2026-10-29 15:30:40,597 - {'Epoch': 40, 'HR@5': '0.0606', 'NDCG@5': '0.0416', 'HR@10': '0.1073', 'NDCG@10': '0.0567', 'HR@20': '0.1615', 'NDCG@20': '0.0703'}
2026-10-29 15:30:40,599 - Validation score increased.  Saving model ...
Mode_train:41: 100% 101/101 [00:02<00:00, 38.00it/s]
2026-10-29 15:30:43,339 - {'epoch': 41, 'rec_loss': '4.9557'}
Mode_test:41: 100% 5/5 [00:00<00:00, 25.17it/s]
2026-10-29 15:30:43,672 - {'Epoch': 41, 'HR@5': '0.0651', 'NDCG@5': '0.0402', 'HR@10': '0.1028', 'NDCG@10': '0.0521', 'HR@20': '0.1514', 'NDCG@20': '0.0645'}
2026-10-29 15:30:43,674 - EarlyStopping counter: 1 out of 10
Mode_train:42: 100% 101/101 [00:02<00:00, 40.91it/s]
2026-10-29 15:30:46,205 - {'epoch': 42, 'rec_loss': '4.9143'}
Mode_test:42: 100% 5/5 [00:00<00:00, 22.95it/s]
2026-10-29 15:30:46,543 - {'Epoch': 42, 'HR@5': '0.0661', 'NDCG@5': '0.0424', 'HR@10': '0.1028', 'NDCG@10': '0.0541', 'HR@20': '0.1606', 'NDCG@20': '0.0686'}
2026-10-29 15:30:46,544 - EarlyStopping counter: 2 out of 10
Mode_train:43: 100% 101/101 [00:02<00:00, 38.96it/s]
2026-10-29 15:30:49,209 - {'epoch': 43, 'rec_loss': '4.9263'}
Mode_test:43: 100% 5/5 [00:00<00:00, 24.88it/s]

## F. Jalankan baseline SASRec

SASRec memakai data, split, dan evaluasi full-item yang sama. Parameter `alpha` dan `c` hanya milik BSARec.

In [9]:
!python main.py --model_type SASRec --data_name LastFM --lr 0.001 --num_attention_heads 1 --seed 42 --train_name SASRec_LastFM_final_s42

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:424: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
2026-10-29 15:31:13,146 - Namespace(data_dir='./data/', output_dir='output/', data_name='LastFM', do_eval=False, load_model=None, train_name='SASRec_LastFM_final_s42', num_items=10, num_users=1091, lr=0.001, batch_size=256, epochs=200, no_cuda=False, log_freq=1, patience=10, num_workers=4, seed=42, weight_decay=0.0, adam_beta1=0.9, adam_beta2=0.999, gpu_id='0', variance=5, model_type='SASRec', max_seq_length=50, hidden_size=64, num_hidden_layers=2, hidden_act='gelu', num_attention_heads=1, attention_probs_dropout_prob=0.5, hidden_dropout_prob=0.5, initializer_range=0.02, cuda_condition=True, data_file='./data/LastFM.txt', item_size=3647, checkpoint_path='output/SASRec_LastFM_final_s42.pt', same_target_path='./data/LastFM_same_target.npy')
2026-10-29 15:31:13,162 - SASRecModel(
  (item_embeddings): Embedding(3647, 64, padding_idx=0)
  (position_embeddings): Embedding(50, 64)
  (LayerNorm): LayerNorm()
  (dropout): Dropout(p=0.5, inplace=False)
  (item_encoder): TransformerEncoder(
    (blocks): ModuleList(
      (0-1): 2 x TransformerBlock(
        (layer): MultiHeadAttention(
          (query): Linear(in_features=64, out_features=64, bias=True)
          (key): Linear(in_features=64, out_features=64, bias=True)
          (value): Linear(in_features=64, out_features=64, bias=True)
          (softmax): Softmax(dim=-1)
          (attn_dropout): Dropout(p=0.5, inplace=False)
          (dense): Linear(in_features=64, out_features=64, bias=True)
          (LayerNorm): LayerNorm((64,), eps=1e-12, elementwise_affine=True)
          (out_dropout): Dropout(p=0.5, inplace=False)
        )
        (feed_forward): FeedForward(
          (dense_1): Linear(in_features=64, out_features=256, bias=True)
          (dense_2): Linear(in_features=256, out_features=64, bias=True)
          (LayerNorm): LayerNorm()
          (dropout): Dropout(p=0.5, inplace=False)
        )
      )
    )
  )
)
2026-10-29 15:31:14,304 - Total Parameters: 336704
/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
Mode_train:0: 100% 101/101 [00:02<00:00, 38.75it/s]
2026-10-29 15:31:16,998 - {'epoch': 0, 'rec_loss': '1.3340'}
Mode_test:0: 100% 5/5 [00:00<00:00, 24.41it/s]
2026-10-29 15:31:17,333 - {'Epoch': 0, 'HR@5': '0.0202', 'NDCG@5': '0.0114', 'HR@10': '0.0376', 'NDCG@10': '0.0169', 'HR@20': '0.0587', 'NDCG@20': '0.0222'}
2026-10-29 15:31:17,334 - Validation score increased.  Saving model ...
Mode_train:1: 100% 101/101 [00:02<00:00, 43.34it/s]
2026-10-29 15:31:19,749 - {'epoch': 1, 'rec_loss': '1.2205'}
Mode_test:1: 100% 5/5 [00:00<00:00, 24.17it/s]
2026-10-29 15:31:20,085 - {'Epoch': 1, 'HR@5': '0.0183', 'NDCG@5': '0.0111', 'HR@10': '0.0321', 'NDCG@10': '0.0155', 'HR@20': '0.0550', 'NDCG@20': '0.0213'}
2026-10-29 15:31:20,086 - EarlyStopping counter: 1 out of 10
Mode_train:2: 100% 101/101 [00:02<00:00, 46.17it/s]
2026-10-29 15:31:22,345 - {'epoch': 2, 'rec_loss': '1.1521'}
Mode_test:2: 100% 5/5 [00:00<00:00, 25.30it/s]
2026-10-29 15:31:22,666 - {'Epoch': 2, 'HR@5': '0.0174', 'NDCG@5': '0.0112', 'HR@10': '0.0312', 'NDCG@10': '0.0155', 'HR@20': '0.0596', 'NDCG@20': '0.0226'}
2026-10-29 15:31:22,667 - Validation score increased.  Saving model ...
Mode_train:3: 100% 101/101 [00:02<00:00, 47.83it/s]
2026-10-29 15:31:24,856 - {'epoch': 3, 'rec_loss': '1.0811'}
Mode_test:3: 100% 5/5 [00:00<00:00, 25.12it/s]
2026-10-29 15:31:25,198 - {'Epoch': 3, 'HR@5': '0.0183', 'NDCG@5': '0.0116', 'HR@10': '0.0339', 'NDCG@10': '0.0166', 'HR@20': '0.0541', 'NDCG@20': '0.0215'}
2026-10-29 15:31:25,199 - EarlyStopping counter: 1 out of 10
Mode_train:4: 100% 101/101 [00:02<00:00, 47.55it/s]
2026-10-29 15:31:27,400 - {'epoch': 4, 'rec_loss': '1.0327'}
Mode_test:4: 100% 5/5 [00:00<00:00, 27.37it/s]
2026-10-29 15:31:27,708 - {'Epoch': 4, 'HR@5': '0.0193', 'NDCG@5': '0.0103', 'HR@10': '0.0385', 'NDCG@10': '0.0165', 'HR@20': '0.0679', 'NDCG@20': '0.0238'}
2026-10-29 15:31:27,709 - Validation score increased.  Saving model ...
Mode_train:5: 100% 101/101 [00:02<00:00, 46.73it/s]
2026-10-29 15:31:29,951 - {'epoch': 5, 'rec_loss': '0.9787'}
Mode_test:5: 100% 5/5 [00:00<00:00, 25.93it/s]
2026-10-29 15:31:30,269 - {'Epoch': 5, 'HR@5': '0.0229', 'NDCG@5': '0.0145', 'HR@10': '0.0459', 'NDCG@10': '0.0217', 'HR@20': '0.0716', 'NDCG@20': '0.0282'}
2026-10-29 15:31:30,270 - Validation score increased.  Saving model ...
Mode_train:6: 100% 101/101 [00:02<00:00, 46.95it/s]
2026-10-29 15:31:32,511 - {'epoch': 6, 'rec_loss': '0.9211'}
Mode_test:6: 100% 5/5 [00:00<00:00, 24.39it/s]
2026-10-29 15:31:32,837 - {'Epoch': 6, 'HR@5': '0.0312', 'NDCG@5': '0.0208', 'HR@10': '0.0495', 'NDCG@10': '0.0268', 'HR@20': '0.0771', 'NDCG@20': '0.0335'}
2026-10-29 15:31:32,838 - Validation score increased.  Saving model ...
Mode_train:7: 100% 101/101 [00:02<00:00, 47.59it/s]
2026-10-29 15:31:35,038 - {'epoch': 7, 'rec_loss': '0.8674'}
Mode_test:7: 100% 5/5 [00:00<00:00, 25.29it/s]
2026-10-29 15:31:35,356 - {'Epoch': 7, 'HR@5': '0.0330', 'NDCG@5': '0.0213', 'HR@10': '0.0486', 'NDCG@10': '0.0264', 'HR@20': '0.0826', 'NDCG@20': '0.0349'}
2026-10-29 15:31:35,357 - Validation score increased.  Saving model ...
Mode_train:8: 100% 101/101 [00:02<00:00, 47.57it/s]
2026-10-29 15:31:37,560 - {'epoch': 8, 'rec_loss': '0.8231'}
Mode_test:8: 100% 5/5 [00:00<00:00, 24.15it/s]
2026-10-29 15:31:37,892 - {'Epoch': 8, 'HR@5': '0.0358', 'NDCG@5': '0.0205', 'HR@10': '0.0596', 'NDCG@10': '0.0280', 'HR@20': '0.0881', 'NDCG@20': '0.0350'}
2026-10-29 15:31:37,893 - Validation score increased.  Saving model ...
Mode_train:9: 100% 101/101 [00:02<00:00, 46.84it/s]
2026-10-29 15:31:40,126 - {'epoch': 9, 'rec_loss': '0.7807'}
Mode_test:9: 100% 5/5 [00:00<00:00, 25.91it/s]
2026-10-29 15:31:40,446 - {'Epoch': 9, 'HR@5': '0.0284', 'NDCG@5': '0.0163', 'HR@10': '0.0514', 'NDCG@10': '0.0236', 'HR@20': '0.0853', 'NDCG@20': '0.0323'}
2026-10-29 15:31:40,447 - EarlyStopping counter: 1 out of 10
Mode_train:10: 100% 101/101 [00:02<00:00, 46.54it/s]
2026-10-29 15:31:42,691 - {'epoch': 10, 'rec_loss': '0.7471'}
Mode_test:10: 100% 5/5 [00:00<00:00, 25.36it/s]
2026-10-29 15:31:43,018 - {'Epoch': 10, 'HR@5': '0.0339', 'NDCG@5': '0.0199', 'HR@10': '0.0505', 'NDCG@10': '0.0251', 'HR@20': '0.0862', 'NDCG@20': '0.0339'}
2026-10-29 15:31:43,019 - EarlyStopping counter: 2 out of 10
Mode_train:11: 100% 101/101 [00:02<00:00, 44.22it/s]
2026-10-29 15:31:45,382 - {'epoch': 11, 'rec_loss': '0.7049'}
Mode_test:11: 100% 5/5 [00:00<00:00, 25.60it/s]
2026-10-29 15:31:45,714 - {'Epoch': 11, 'HR@5': '0.0294', 'NDCG@5': '0.0161', 'HR@10': '0.0550', 'NDCG@10': '0.0243', 'HR@20': '0.0908', 'NDCG@20': '0.0333'}
2026-10-29 15:31:45,715 - EarlyStopping counter: 3 out of 10
Mode_train:12: 100% 101/101 [00:02<00:00, 44.69it/s]
2026-10-29 15:31:48,047 - {'epoch': 12, 'rec_loss': '0.6743'}
Mode_test:12: 100% 5/5 [00:00<00:00, 22.88it/s]
2026-10-29 15:31:48,394 - {'Epoch': 12, 'HR@5': '0.0275', 'NDCG@5': '0.0164', 'HR@10': '0.0587', 'NDCG@10': '0.0262', 'HR@20': '0.1046', 'NDCG@20': '0.0377'}
2026-10-29 15:31:48,395 - Validation score increased.  Saving model ...
Mode_train:13: 100% 101/101 [00:02<00:00, 45.88it/s]
2026-10-29 15:31:50,680 - {'epoch': 13, 'rec_loss': '0.6491'}
Mode_test:13: 100% 5/5 [00:00<00:00, 26.42it/s]
2026-10-29 15:31:50,992 - {'Epoch': 13, 'HR@5': '0.0339', 'NDCG@5': '0.0199', 'HR@10': '0.0587', 'NDCG@10': '0.0280', 'HR@20': '0.0917', 'NDCG@20': '0.0363'}
2026-10-29 15:31:50,994 - EarlyStopping counter: 1 out of 10
Mode_train:14: 100% 101/101 [00:02<00:00, 44.81it/s]
2026-10-29 15:31:53,321 - {'epoch': 14, 'rec_loss': '0.6231'}
Mode_test:14: 100% 5/5 [00:00<00:00, 23.49it/s]
2026-10-29 15:31:53,670 - {'Epoch': 14, 'HR@5': '0.0358', 'NDCG@5': '0.0197', 'HR@10': '0.0642', 'NDCG@10': '0.0289', 'HR@20': '0.0991', 'NDCG@20': '0.0375'}
2026-10-29 15:31:53,671 - EarlyStopping counter: 2 out of 10
Mode_train:15: 100% 101/101 [00:02<00:00, 47.10it/s]
2026-10-29 15:31:55,889 - {'epoch': 15, 'rec_loss': '0.5957'}
Mode_test:15: 100% 5/5 [00:00<00:00, 25.61it/s]
2026-10-29 15:31:56,209 - {'Epoch': 15, 'HR@5': '0.0330', 'NDCG@5': '0.0190', 'HR@10': '0.0541', 'NDCG@10': '0.0258', 'HR@20': '0.1037', 'NDCG@20': '0.0382'}
2026-10-29 15:31:56,210 - Validation score increased.  Saving model ...
Mode_train:16: 100% 101/101 [00:02<00:00, 48.19it/s]
2026-10-29 15:31:58,386 - {'epoch': 16, 'rec_loss': '0.5705'}
Mode_test:16: 100% 5/5 [00:00<00:00, 23.95it/s]
2026-10-29 15:31:58,727 - {'Epoch': 16, 'HR@5': '0.0404', 'NDCG@5': '0.0253', 'HR@10': '0.0606', 'NDCG@10': '0.0319', 'HR@20': '0.1037', 'NDCG@20': '0.0428'}
2026-10-29 15:31:58,728 - Validation score increased.  Saving model ...
Mode_train:17: 100% 101/101 [00:02<00:00, 46.47it/s]
2026-10-29 15:32:00,976 - {'epoch': 17, 'rec_loss': '0.5568'}
Mode_test:17: 100% 5/5 [00:00<00:00, 25.56it/s]
2026-10-29 15:32:01,300 - {'Epoch': 17, 'HR@5': '0.0376', 'NDCG@5': '0.0230', 'HR@10': '0.0569', 'NDCG@10': '0.0293', 'HR@20': '0.1046', 'NDCG@20': '0.0413'}
2026-10-29 15:32:01,302 - EarlyStopping counter: 1 out of 10
Mode_train:18: 100% 101/101 [00:02<00:00, 48.12it/s]
2026-10-29 15:32:03,487 - {'epoch': 18, 'rec_loss': '0.5438'}
Mode_test:18: 100% 5/5 [00:00<00:00, 26.77it/s]
2026-10-29 15:32:03,797 - {'Epoch': 18, 'HR@5': '0.0312', 'NDCG@5': '0.0185', 'HR@10': '0.0624', 'NDCG@10': '0.0285', 'HR@20': '0.1110', 'NDCG@20': '0.0407'}
2026-10-29 15:32:03,798 - EarlyStopping counter: 2 out of 10
Mode_train:19: 100% 101/101 [00:02<00:00, 44.57it/s]
2026-10-29 15:32:06,148 - {'epoch': 19, 'rec_loss': '0.5294'}
Mode_test:19: 100% 5/5 [00:00<00:00, 25.60it/s]
2026-10-29 15:32:06,484 - {'Epoch': 19, 'HR@5': '0.0367', 'NDCG@5': '0.0227', 'HR@10': '0.0587', 'NDCG@10': '0.0297', 'HR@20': '0.1064', 'NDCG@20': '0.0416'}
2026-10-29 15:32:06,485 - EarlyStopping counter: 3 out of 10
Mode_train:20: 100% 101/101 [00:02<00:00, 44.83it/s]
2026-10-29 15:32:08,810 - {'epoch': 20, 'rec_loss': '0.5133'}
Mode_test:20: 100% 5/5 [00:00<00:00, 24.65it/s]
2026-10-29 15:32:09,152 - {'Epoch': 20, 'HR@5': '0.0385', 'NDCG@5': '0.0235', 'HR@10': '0.0615', 'NDCG@10': '0.0308', 'HR@20': '0.1138', 'NDCG@20': '0.0439'}
2026-10-29 15:32:09,153 - Validation score increased.  Saving model ...
Mode_train:21: 100% 101/101 [00:02<00:00, 43.70it/s]
2026-10-29 15:32:11,549 - {'epoch': 21, 'rec_loss': '0.4957'}
Mode_test:21: 100% 5/5 [00:00<00:00, 25.58it/s]
2026-10-29 15:32:11,871 - {'Epoch': 21, 'HR@5': '0.0394', 'NDCG@5': '0.0267', 'HR@10': '0.0661', 'NDCG@10': '0.0351', 'HR@20': '0.1046', 'NDCG@20': '0.0448'}
2026-10-29 15:32:11,873 - Validation score increased.  Saving model ...
Mode_train:22: 100% 101/101 [00:02<00:00, 45.48it/s]
2026-10-29 15:32:14,173 - {'epoch': 22, 'rec_loss': '0.4850'}
Mode_test:22: 100% 5/5 [00:00<00:00, 23.60it/s]
2026-10-29 15:32:14,517 - {'Epoch': 22, 'HR@5': '0.0404', 'NDCG@5': '0.0240', 'HR@10': '0.0596', 'NDCG@10': '0.0300', 'HR@20': '0.1064', 'NDCG@20': '0.0419'}
2026-10-29 15:32:14,518 - EarlyStopping counter: 1 out of 10
Mode_train:23: 100% 101/101 [00:02<00:00, 44.25it/s]
2026-10-29 15:32:16,885 - {'epoch': 23, 'rec_loss': '0.4813'}
Mode_test:23: 100% 5/5 [00:00<00:00, 26.22it/s]
2026-10-29 15:32:17,199 - {'Epoch': 23, 'HR@5': '0.0394', 'NDCG@5': '0.0224', 'HR@10': '0.0651', 'NDCG@10': '0.0308', 'HR@20': '0.1037', 'NDCG@20': '0.0405'}
2026-10-29 15:32:17,200 - EarlyStopping counter: 2 out of 10
Mode_train:24: 100% 101/101 [00:02<00:00, 47.54it/s]
2026-10-29 15:32:19,404 - {'epoch': 24, 'rec_loss': '0.4712'}
Mode_test:24: 100% 5/5 [00:00<00:00, 24.71it/s]
2026-10-29 15:32:19,740 - {'Epoch': 24, 'HR@5': '0.0339', 'NDCG@5': '0.0192', 'HR@10': '0.0615', 'NDCG@10': '0.0279', 'HR@20': '0.0982', 'NDCG@20': '0.0371'}
2026-10-29 15:32:19,741 - EarlyStopping counter: 3 out of 10
Mode_train:25: 100% 101/101 [00:02<00:00, 45.83it/s]
2026-10-29 15:32:22,047 - {'epoch': 25, 'rec_loss': '0.4669'}
Mode_test:25: 100% 5/5 [00:00<00:00, 24.62it/s]
2026-10-29 15:32:22,374 - {'Epoch': 25, 'HR@5': '0.0367', 'NDCG@5': '0.0213', 'HR@10': '0.0587', 'NDCG@10': '0.0285', 'HR@20': '0.0991', 'NDCG@20': '0.0386'}
2026-10-29 15:32:22,376 - EarlyStopping counter: 4 out of 10
Mode_train:26: 100% 101/101 [00:02<00:00, 46.67it/s]
2026-10-29 15:32:24,625 - {'epoch': 26, 'rec_loss': '0.4429'}
Mode_test:26: 100% 5/5 [00:00<00:00, 23.27it/s]
2026-10-29 15:32:24,981 - {'Epoch': 26, 'HR@5': '0.0339', 'NDCG@5': '0.0212', 'HR@10': '0.0624', 'NDCG@10': '0.0303', 'HR@20': '0.0954', 'NDCG@20': '0.0386'}
2026-10-29 15:32:24,982 - EarlyStopping counter: 5 out of 10
Mode_train:27: 100% 101/101 [00:02<00:00, 46.09it/s]
2026-10-29 15:32:27,246 - {'epoch': 27, 'rec_loss': '0.4437'}
Mode_test:27: 100% 5/5 [00:00<00:00, 25.34it/s]
2026-10-29 15:32:27,576 - {'Epoch': 27, 'HR@5': '0.0413', 'NDCG@5': '0.0263', 'HR@10': '0.0624', 'NDCG@10': '0.0329', 'HR@20': '0.1018', 'NDCG@20': '0.0427'}
2026-10-29 15:32:27,577 - EarlyStopping counter: 6 out of 10
Mode_train:28: 100% 101/101 [00:02<00:00, 44.42it/s]
2026-10-29 15:32:29,924 - {'epoch': 28, 'rec_loss': '0.4320'}
Mode_test:28: 100% 5/5 [00:00<00:00, 22.35it/s]
2026-10-29 15:32:30,349 - {'Epoch': 28, 'HR@5': '0.0376', 'NDCG@5': '0.0232', 'HR@10': '0.0633', 'NDCG@10': '0.0314', 'HR@20': '0.1037', 'NDCG@20': '0.0417'}
2026-10-29 15:32:30,351 - EarlyStopping counter: 7 out of 10
Mode_train:29: 100% 101/101 [00:02<00:00, 47.71it/s]
2026-10-29 15:32:32,537 - {'epoch': 29, 'rec_loss': '0.4358'}
Mode_test:29: 100% 5/5 [00:00<00:00, 26.50it/s]
2026-10-29 15:32:32,857 - {'Epoch': 29, 'HR@5': '0.0321', 'NDCG@5': '0.0203', 'HR@10': '0.0578', 'NDCG@10': '0.0286', 'HR@20': '0.1037', 'NDCG@20': '0.0402'}
2026-10-29 15:32:32,858 - EarlyStopping counter: 8 out of 10
Mode_train:30: 100% 101/101 [00:02<00:00, 48.06it/s]
2026-10-29 15:32:35,032 - {'epoch': 30, 'rec_loss': '0.4203'}
Mode_test:30: 100% 5/5 [00:00<00:00, 24.36it/s]
2026-10-29 15:32:35,379 - {'Epoch': 30, 'HR@5': '0.0394', 'NDCG@5': '0.0239', 'HR@10': '0.0550', 'NDCG@10': '0.0289', 'HR@20': '0.1000', 'NDCG@20': '0.0401'}
2026-10-29 15:32:35,380 - EarlyStopping counter: 9 out of 10
Mode_train:31: 100% 101/101 [00:02<00:00, 47.69it/s]
2026-10-29 15:32:37,568 - {'epoch': 31, 'rec_loss': '0.4184'}
Mode_test:31: 100% 5/5 [00:00<00:00, 26.16it/s]
2026-10-29 15:32:37,891 - {'Epoch': 31, 'HR@5': '0.0385', 'NDCG@5': '0.0241', 'HR@10': '0.0642', 'NDCG@10': '0.0323', 'HR@20': '0.0991', 'NDCG@20': '0.0411'}
2026-10-29 15:32:37,892 - EarlyStopping counter: 10 out of 10
2026-10-29 15:32:37,892 - Early stopping
2026-10-29 15:32:37,893 - ---------------Test Score---------------
Mode_test:0: 100% 5/5 [00:00<00:00, 27.69it/s]
2026-10-29 15:32:38,216 - {'Epoch': 0, 'HR@5': '0.0450', 'NDCG@5': '0.0337', 'HR@10': '0.0642', 'NDCG@10': '0.0398', 'HR@20': '0.0881', 'NDCG@20': '0.0458'}
2026-10-29 15:32:38,217 - SASRec_LastFM_final_s42
2026-10-29 15:32:38,217 - {'Epoch': 0, 'HR@5': '0.0450', 'NDCG@5': '0.0337', 'HR@10': '0.0642', 'NDCG@10': '0.0398', 'HR@20': '0.0881', 'NDCG@20': '0.0458'}

In [10]:
!python main.py --model_type SASRec --data_name LastFM --lr 0.001 --num_attention_heads 1 --seed 43 --train_name SASRec_LastFM_final_s43

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:424: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
2026-10-29 15:32:41,054 - Namespace(data_dir='./data/', output_dir='output/', data_name='LastFM', do_eval=False, load_model=None, train_name='SASRec_LastFM_final_s43', num_items=10, num_users=1091, lr=0.001, batch_size=256, epochs=200, no_cuda=False, log_freq=1, patience=10, num_workers=4, seed=43, weight_decay=0.0, adam_beta1=0.9, adam_beta2=0.999, gpu_id='0', variance=5, model_type='SASRec', max_seq_length=50, hidden_size=64, num_hidden_layers=2, hidden_act='gelu', num_attention_heads=1, attention_probs_dropout_prob=0.5, hidden_dropout_prob=0.5, initializer_range=0.02, cuda_condition=True, data_file='./data/LastFM.txt', item_size=3647, checkpoint_path='output/SASRec_LastFM_final_s43.pt', same_target_path='./data/LastFM_same_target.npy')
2026-10-29 15:32:41,067 - SASRecModel(
  (item_embeddings): Embedding(3647, 64, padding_idx=0)
  (position_embeddings): Embedding(50, 64)
  (LayerNorm): LayerNorm()
  (dropout): Dropout(p=0.5, inplace=False)
  (item_encoder): TransformerEncoder(
    (blocks): ModuleList(
      (0-1): 2 x TransformerBlock(
        (layer): MultiHeadAttention(
          (query): Linear(in_features=64, out_features=64, bias=True)
          (key): Linear(in_features=64, out_features=64, bias=True)
          (value): Linear(in_features=64, out_features=64, bias=True)
          (softmax): Softmax(dim=-1)
          (attn_dropout): Dropout(p=0.5, inplace=False)
          (dense): Linear(in_features=64, out_features=64, bias=True)
          (LayerNorm): LayerNorm((64,), eps=1e-12, elementwise_affine=True)
          (out_dropout): Dropout(p=0.5, inplace=False)
        )
        (feed_forward): FeedForward(
          (dense_1): Linear(in_features=64, out_features=256, bias=True)
          (dense_2): Linear(in_features=256, out_features=64, bias=True)
          (LayerNorm): LayerNorm()
          (dropout): Dropout(p=0.5, inplace=False)
        )
      )
    )
  )
)
2026-10-29 15:32:42,166 - Total Parameters: 336704
/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
Mode_train:0: 100% 101/101 [00:02<00:00, 39.27it/s]
2026-10-29 15:32:44,825 - {'epoch': 0, 'rec_loss': '1.3341'}
Mode_test:0: 100% 5/5 [00:00<00:00, 21.22it/s]
2026-10-29 15:32:45,203 - {'Epoch': 0, 'HR@5': '0.0220', 'NDCG@5': '0.0122', 'HR@10': '0.0358', 'NDCG@10': '0.0166', 'HR@20': '0.0550', 'NDCG@20': '0.0214'}
2026-10-29 15:32:45,204 - Validation score increased.  Saving model ...
Mode_train:1: 100% 101/101 [00:02<00:00, 47.96it/s]
2026-10-29 15:32:47,391 - {'epoch': 1, 'rec_loss': '1.2214'}
Mode_test:1: 100% 5/5 [00:00<00:00, 26.51it/s]
2026-10-29 15:32:47,710 - {'Epoch': 1, 'HR@5': '0.0165', 'NDCG@5': '0.0095', 'HR@10': '0.0284', 'NDCG@10': '0.0134', 'HR@20': '0.0578', 'NDCG@20': '0.0208'}
2026-10-29 15:32:47,712 - EarlyStopping counter: 1 out of 10
Mode_train:2: 100% 101/101 [00:02<00:00, 46.59it/s]
2026-10-29 15:32:49,960 - {'epoch': 2, 'rec_loss': '1.1488'}
Mode_test:2: 100% 5/5 [00:00<00:00, 27.27it/s]
2026-10-29 15:32:50,322 - {'Epoch': 2, 'HR@5': '0.0202', 'NDCG@5': '0.0131', 'HR@10': '0.0294', 'NDCG@10': '0.0160', 'HR@20': '0.0495', 'NDCG@20': '0.0210'}
2026-10-29 15:32:50,323 - EarlyStopping counter: 2 out of 10
Mode_train:3: 100% 101/101 [00:02<00:00, 47.71it/s]
2026-10-29 15:32:52,512 - {'epoch': 3, 'rec_loss': '1.0861'}
Mode_test:3: 100% 5/5 [00:00<00:00, 27.95it/s]
2026-10-29 15:32:52,816 - {'Epoch': 3, 'HR@5': '0.0183', 'NDCG@5': '0.0119', 'HR@10': '0.0312', 'NDCG@10': '0.0162', 'HR@20': '0.0532', 'NDCG@20': '0.0216'}
2026-10-29 15:32:52,817 - Validation score increased.  Saving model ...
Mode_train:4: 100% 101/101 [00:02<00:00, 48.06it/s]
2026-10-29 15:32:54,998 - {'epoch': 4, 'rec_loss': '1.0206'}
Mode_test:4: 100% 5/5 [00:00<00:00, 24.27it/s]
2026-10-29 15:32:55,325 - {'Epoch': 4, 'HR@5': '0.0193', 'NDCG@5': '0.0109', 'HR@10': '0.0312', 'NDCG@10': '0.0148', 'HR@20': '0.0606', 'NDCG@20': '0.0223'}
2026-10-29 15:32:55,326 - Validation score increased.  Saving model ...
Mode_train:5: 100% 101/101 [00:02<00:00, 48.79it/s]
2026-10-29 15:32:57,477 - {'epoch': 5, 'rec_loss': '0.9625'}
Mode_test:5: 100% 5/5 [00:00<00:00, 25.84it/s]
2026-10-29 15:32:57,799 - {'Epoch': 5, 'HR@5': '0.0229', 'NDCG@5': '0.0144', 'HR@10': '0.0440', 'NDCG@10': '0.0211', 'HR@20': '0.0633', 'NDCG@20': '0.0260'}
2026-10-29 15:32:57,800 - Validation score increased.  Saving model ...
Mode_train:6: 100% 101/101 [00:02<00:00, 48.49it/s]
2026-10-29 15:32:59,964 - {'epoch': 6, 'rec_loss': '0.9186'}
Mode_test:6: 100% 5/5 [00:00<00:00, 26.09it/s]
2026-10-29 15:33:00,285 - {'Epoch': 6, 'HR@5': '0.0248', 'NDCG@5': '0.0144', 'HR@10': '0.0413', 'NDCG@10': '0.0196', 'HR@20': '0.0716', 'NDCG@20': '0.0272'}
2026-10-29 15:33:00,286 - Validation score increased.  Saving model ...
Mode_train:7: 100% 101/101 [00:02<00:00, 46.45it/s]
2026-10-29 15:33:02,566 - {'epoch': 7, 'rec_loss': '0.8620'}
Mode_test:7: 100% 5/5 [00:00<00:00, 27.03it/s]
2026-10-29 15:33:02,876 - {'Epoch': 7, 'HR@5': '0.0330', 'NDCG@5': '0.0201', 'HR@10': '0.0578', 'NDCG@10': '0.0281', 'HR@20': '0.0789', 'NDCG@20': '0.0334'}
2026-10-29 15:33:02,877 - Validation score increased.  Saving model ...
Mode_train:8: 100% 101/101 [00:02<00:00, 48.19it/s]
2026-10-29 15:33:05,056 - {'epoch': 8, 'rec_loss': '0.8213'}
Mode_test:8: 100% 5/5 [00:00<00:00, 25.91it/s]
2026-10-29 15:33:05,375 - {'Epoch': 8, 'HR@5': '0.0376', 'NDCG@5': '0.0227', 'HR@10': '0.0523', 'NDCG@10': '0.0274', 'HR@20': '0.0844', 'NDCG@20': '0.0355'}
2026-10-29 15:33:05,376 - Validation score increased.  Saving model ...
Mode_train:9: 100% 101/101 [00:02<00:00, 48.63it/s]
2026-10-29 15:33:07,534 - {'epoch': 9, 'rec_loss': '0.7815'}
Mode_test:9: 100% 5/5 [00:00<00:00, 25.86it/s]
2026-10-29 15:33:07,868 - {'Epoch': 9, 'HR@5': '0.0376', 'NDCG@5': '0.0257', 'HR@10': '0.0596', 'NDCG@10': '0.0326', 'HR@20': '0.0862', 'NDCG@20': '0.0394'}
2026-10-29 15:33:07,869 - Validation score increased.  Saving model ...
Mode_train:10: 100% 101/101 [00:02<00:00, 46.79it/s]
2026-10-29 15:33:10,114 - {'epoch': 10, 'rec_loss': '0.7426'}
Mode_test:10: 100% 5/5 [00:00<00:00, 26.43it/s]
2026-10-29 15:33:10,435 - {'Epoch': 10, 'HR@5': '0.0349', 'NDCG@5': '0.0213', 'HR@10': '0.0550', 'NDCG@10': '0.0278', 'HR@20': '0.0844', 'NDCG@20': '0.0352'}
2026-10-29 15:33:10,436 - EarlyStopping counter: 1 out of 10
Mode_train:11: 100% 101/101 [00:02<00:00, 45.69it/s]
2026-10-29 15:33:12,723 - {'epoch': 11, 'rec_loss': '0.7028'}
Mode_test:11: 100% 5/5 [00:00<00:00, 25.07it/s]
2026-10-29 15:33:13,049 - {'Epoch': 11, 'HR@5': '0.0422', 'NDCG@5': '0.0233', 'HR@10': '0.0615', 'NDCG@10': '0.0295', 'HR@20': '0.0881', 'NDCG@20': '0.0362'}
2026-10-29 15:33:13,050 - EarlyStopping counter: 2 out of 10
Mode_train:12: 100% 101/101 [00:02<00:00, 48.23it/s]
2026-10-29 15:33:15,220 - {'epoch': 12, 'rec_loss': '0.6747'}
Mode_test:12: 100% 5/5 [00:00<00:00, 18.47it/s]
2026-10-29 15:33:15,625 - {'Epoch': 12, 'HR@5': '0.0367', 'NDCG@5': '0.0245', 'HR@10': '0.0578', 'NDCG@10': '0.0311', 'HR@20': '0.0954', 'NDCG@20': '0.0406'}
2026-10-29 15:33:15,626 - Validation score increased.  Saving model ...
Mode_train:13: 100% 101/101 [00:02<00:00, 45.78it/s]
2026-10-29 15:33:17,914 - {'epoch': 13, 'rec_loss': '0.6527'}
Mode_test:13: 100% 5/5 [00:00<00:00, 27.38it/s]
2026-10-29 15:33:18,245 - {'Epoch': 13, 'HR@5': '0.0330', 'NDCG@5': '0.0228', 'HR@10': '0.0560', 'NDCG@10': '0.0306', 'HR@20': '0.0890', 'NDCG@20': '0.0389'}
2026-10-29 15:33:18,246 - EarlyStopping counter: 1 out of 10
Mode_train:14: 100% 101/101 [00:02<00:00, 44.80it/s]
2026-10-29 15:33:20,569 - {'epoch': 14, 'rec_loss': '0.6231'}
Mode_test:14: 100% 5/5 [00:00<00:00, 22.35it/s]
2026-10-29 15:33:20,934 - {'Epoch': 14, 'HR@5': '0.0404', 'NDCG@5': '0.0245', 'HR@10': '0.0578', 'NDCG@10': '0.0301', 'HR@20': '0.0936', 'NDCG@20': '0.0391'}
2026-10-29 15:33:20,936 - EarlyStopping counter: 2 out of 10
Mode_train:15: 100% 101/101 [00:02<00:00, 45.34it/s]
2026-10-29 15:33:23,241 - {'epoch': 15, 'rec_loss': '0.6039'}
Mode_test:15: 100% 5/5 [00:00<00:00, 25.05it/s]
2026-10-29 15:33:23,581 - {'Epoch': 15, 'HR@5': '0.0312', 'NDCG@5': '0.0203', 'HR@10': '0.0642', 'NDCG@10': '0.0307', 'HR@20': '0.0972', 'NDCG@20': '0.0390'}
2026-10-29 15:33:23,583 - EarlyStopping counter: 3 out of 10
Mode_train:16: 100% 101/101 [00:02<00:00, 45.09it/s]
2026-10-29 15:33:25,895 - {'epoch': 16, 'rec_loss': '0.5720'}
Mode_test:16: 100% 5/5 [00:00<00:00, 25.59it/s]
2026-10-29 15:33:26,229 - {'Epoch': 16, 'HR@5': '0.0358', 'NDCG@5': '0.0223', 'HR@10': '0.0569', 'NDCG@10': '0.0291', 'HR@20': '0.1028', 'NDCG@20': '0.0404'}
2026-10-29 15:33:26,230 - EarlyStopping counter: 4 out of 10
Mode_train:17: 100% 101/101 [00:02<00:00, 45.49it/s]
2026-10-29 15:33:28,530 - {'epoch': 17, 'rec_loss': '0.5551'}
Mode_test:17: 100% 5/5 [00:00<00:00, 23.37it/s]
2026-10-29 15:33:28,877 - {'Epoch': 17, 'HR@5': '0.0321', 'NDCG@5': '0.0214', 'HR@10': '0.0587', 'NDCG@10': '0.0297', 'HR@20': '0.0954', 'NDCG@20': '0.0390'}
2026-10-29 15:33:28,878 - EarlyStopping counter: 5 out of 10
Mode_train:18: 100% 101/101 [00:02<00:00, 43.67it/s]
2026-10-29 15:33:31,266 - {'epoch': 18, 'rec_loss': '0.5454'}
Mode_test:18: 100% 5/5 [00:00<00:00, 26.62it/s]
2026-10-29 15:33:31,590 - {'Epoch': 18, 'HR@5': '0.0404', 'NDCG@5': '0.0264', 'HR@10': '0.0661', 'NDCG@10': '0.0346', 'HR@20': '0.0908', 'NDCG@20': '0.0408'}
2026-10-29 15:33:31,591 - Validation score increased.  Saving model ...
Mode_train:19: 100% 101/101 [00:02<00:00, 44.43it/s]
2026-10-29 15:33:33,950 - {'epoch': 19, 'rec_loss': '0.5317'}
Mode_test:19: 100% 5/5 [00:00<00:00, 25.69it/s]
2026-10-29 15:33:34,274 - {'Epoch': 19, 'HR@5': '0.0358', 'NDCG@5': '0.0234', 'HR@10': '0.0670', 'NDCG@10': '0.0336', 'HR@20': '0.1000', 'NDCG@20': '0.0419'}
2026-10-29 15:33:34,275 - Validation score increased.  Saving model ...
Mode_train:20: 100% 101/101 [00:02<00:00, 48.12it/s]
2026-10-29 15:33:36,451 - {'epoch': 20, 'rec_loss': '0.5062'}
Mode_test:20: 100% 5/5 [00:00<00:00, 26.07it/s]
2026-10-29 15:33:36,779 - {'Epoch': 20, 'HR@5': '0.0413', 'NDCG@5': '0.0258', 'HR@10': '0.0624', 'NDCG@10': '0.0327', 'HR@20': '0.1000', 'NDCG@20': '0.0420'}
2026-10-29 15:33:36,780 - Validation score increased.  Saving model ...
Mode_train:21: 100% 101/101 [00:02<00:00, 45.67it/s]
2026-10-29 15:33:39,076 - {'epoch': 21, 'rec_loss': '0.4971'}
Mode_test:21: 100% 5/5 [00:00<00:00, 27.84it/s]
2026-10-29 15:33:39,408 - {'Epoch': 21, 'HR@5': '0.0358', 'NDCG@5': '0.0222', 'HR@10': '0.0706', 'NDCG@10': '0.0333', 'HR@20': '0.0991', 'NDCG@20': '0.0404'}
2026-10-29 15:33:39,409 - EarlyStopping counter: 1 out of 10
Mode_train:22: 100% 101/101 [00:02<00:00, 46.21it/s]
2026-10-29 15:33:41,672 - {'epoch': 22, 'rec_loss': '0.4899'}
Mode_test:22: 100% 5/5 [00:00<00:00, 26.40it/s]
2026-10-29 15:33:42,000 - {'Epoch': 22, 'HR@5': '0.0394', 'NDCG@5': '0.0266', 'HR@10': '0.0633', 'NDCG@10': '0.0342', 'HR@20': '0.1073', 'NDCG@20': '0.0452'}
2026-10-29 15:33:42,001 - Validation score increased.  Saving model ...
Mode_train:23: 100% 101/101 [00:02<00:00, 47.21it/s]
2026-10-29 15:33:44,230 - {'epoch': 23, 'rec_loss': '0.4783'}
Mode_test:23: 100% 5/5 [00:00<00:00, 24.53it/s]
2026-10-29 15:33:44,565 - {'Epoch': 23, 'HR@5': '0.0404', 'NDCG@5': '0.0258', 'HR@10': '0.0624', 'NDCG@10': '0.0329', 'HR@20': '0.0899', 'NDCG@20': '0.0398'}
2026-10-29 15:33:44,566 - EarlyStopping counter: 1 out of 10
Mode_train:24: 100% 101/101 [00:02<00:00, 44.98it/s]
2026-10-29 15:33:46,886 - {'epoch': 24, 'rec_loss': '0.4691'}
Mode_test:24: 100% 5/5 [00:00<00:00, 25.30it/s]
2026-10-29 15:33:47,209 - {'Epoch': 24, 'HR@5': '0.0422', 'NDCG@5': '0.0267', 'HR@10': '0.0661', 'NDCG@10': '0.0342', 'HR@20': '0.0991', 'NDCG@20': '0.0423'}
2026-10-29 15:33:47,210 - EarlyStopping counter: 2 out of 10
Mode_train:25: 100% 101/101 [00:02<00:00, 44.91it/s]
2026-10-29 15:33:49,532 - {'epoch': 25, 'rec_loss': '0.4625'}
Mode_test:25: 100% 5/5 [00:00<00:00, 24.75it/s]
2026-10-29 15:33:49,873 - {'Epoch': 25, 'HR@5': '0.0385', 'NDCG@5': '0.0239', 'HR@10': '0.0587', 'NDCG@10': '0.0304', 'HR@20': '0.1037', 'NDCG@20': '0.0416'}
2026-10-29 15:33:49,874 - EarlyStopping counter: 3 out of 10
Mode_train:26: 100% 101/101 [00:02<00:00, 44.38it/s]
2026-10-29 15:33:52,227 - {'epoch': 26, 'rec_loss': '0.4541'}
Mode_test:26: 100% 5/5 [00:00<00:00, 25.33it/s]
2026-10-29 15:33:52,561 - {'Epoch': 26, 'HR@5': '0.0385', 'NDCG@5': '0.0260', 'HR@10': '0.0661', 'NDCG@10': '0.0349', 'HR@20': '0.1000', 'NDCG@20': '0.0434'}
2026-10-29 15:33:52,562 - EarlyStopping counter: 4 out of 10
Mode_train:27: 100% 101/101 [00:02<00:00, 48.21it/s]
2026-10-29 15:33:54,731 - {'epoch': 27, 'rec_loss': '0.4427'}
Mode_test:27: 100% 5/5 [00:00<00:00, 24.89it/s]
2026-10-29 15:33:55,064 - {'Epoch': 27, 'HR@5': '0.0431', 'NDCG@5': '0.0283', 'HR@10': '0.0716', 'NDCG@10': '0.0374', 'HR@20': '0.1000', 'NDCG@20': '0.0446'}
2026-10-29 15:33:55,065 - EarlyStopping counter: 5 out of 10
Mode_train:28: 100% 101/101 [00:02<00:00, 47.58it/s]
2026-10-29 15:33:57,265 - {'epoch': 28, 'rec_loss': '0.4394'}
Mode_test:28: 100% 5/5 [00:00<00:00, 24.80it/s]
2026-10-29 15:33:57,598 - {'Epoch': 28, 'HR@5': '0.0440', 'NDCG@5': '0.0290', 'HR@10': '0.0651', 'NDCG@10': '0.0360', 'HR@20': '0.0982', 'NDCG@20': '0.0444'}
2026-10-29 15:33:57,599 - EarlyStopping counter: 6 out of 10
Mode_train:29: 100% 101/101 [00:02<00:00, 45.93it/s]
2026-10-29 15:33:59,875 - {'epoch': 29, 'rec_loss': '0.4258'}
Mode_test:29: 100% 5/5 [00:00<00:00, 24.58it/s]
2026-10-29 15:34:00,215 - {'Epoch': 29, 'HR@5': '0.0385', 'NDCG@5': '0.0263', 'HR@10': '0.0615', 'NDCG@10': '0.0336', 'HR@20': '0.1009', 'NDCG@20': '0.0435'}
2026-10-29 15:34:00,217 - EarlyStopping counter: 7 out of 10
Mode_train:30: 100% 101/101 [00:02<00:00, 46.21it/s]
2026-10-29 15:34:02,473 - {'epoch': 30, 'rec_loss': '0.4296'}
Mode_test:30: 100% 5/5 [00:00<00:00, 24.91it/s]
2026-10-29 15:34:02,806 - {'Epoch': 30, 'HR@5': '0.0459', 'NDCG@5': '0.0305', 'HR@10': '0.0725', 'NDCG@10': '0.0391', 'HR@20': '0.1046', 'NDCG@20': '0.0471'}
2026-10-29 15:34:02,807 - Validation score increased.  Saving model ...
Mode_train:31: 100% 101/101 [00:02<00:00, 47.66it/s]
2026-10-29 15:34:05,007 - {'epoch': 31, 'rec_loss': '0.4197'}
Mode_test:31: 100% 5/5 [00:00<00:00, 25.59it/s]
2026-10-29 15:34:05,328 - {'Epoch': 31, 'HR@5': '0.0450', 'NDCG@5': '0.0282', 'HR@10': '0.0697', 'NDCG@10': '0.0363', 'HR@20': '0.1046', 'NDCG@20': '0.0449'}
2026-10-29 15:34:05,329 - EarlyStopping counter: 1 out of 10
Mode_train:32: 100% 101/101 [00:02<00:00, 47.34it/s]
2026-10-29 15:34:07,558 - {'epoch': 32, 'rec_loss': '0.4158'}
Mode_test:32: 100% 5/5 [00:00<00:00, 26.21it/s]
2026-10-29 15:34:07,877 - {'Epoch': 32, 'HR@5': '0.0440', 'NDCG@5': '0.0276', 'HR@10': '0.0661', 'NDCG@10': '0.0346', 'HR@20': '0.1128', 'NDCG@20': '0.0463'}
2026-10-29 15:34:07,878 - EarlyStopping counter: 2 out of 10
Mode_train:33: 100% 101/101 [00:02<00:00, 48.51it/s]
2026-10-29 15:34:10,036 - {'epoch': 33, 'rec_loss': '0.4215'}
Mode_test:33: 100% 5/5 [00:00<00:00, 25.94it/s]
2026-10-29 15:34:10,357 - {'Epoch': 33, 'HR@5': '0.0404', 'NDCG@5': '0.0261', 'HR@10': '0.0670', 'NDCG@10': '0.0346', 'HR@20': '0.1046', 'NDCG@20': '0.0441'}
2026-10-29 15:34:10,358 - EarlyStopping counter: 3 out of 10
Mode_train:34: 100% 101/101 [00:02<00:00, 45.80it/s]
2026-10-29 15:34:12,637 - {'epoch': 34, 'rec_loss': '0.4019'}
Mode_test:34: 100% 5/5 [00:00<00:00, 24.78it/s]
2026-10-29 15:34:12,985 - {'Epoch': 34, 'HR@5': '0.0376', 'NDCG@5': '0.0246', 'HR@10': '0.0615', 'NDCG@10': '0.0324', 'HR@20': '0.0954', 'NDCG@20': '0.0410'}
2026-10-29 15:34:12,986 - EarlyStopping counter: 4 out of 10
Mode_train:35: 100% 101/101 [00:02<00:00, 47.58it/s]
2026-10-29 15:34:15,188 - {'epoch': 35, 'rec_loss': '0.4040'}
Mode_test:35: 100% 5/5 [00:00<00:00, 25.56it/s]
2026-10-29 15:34:15,517 - {'Epoch': 35, 'HR@5': '0.0385', 'NDCG@5': '0.0260', 'HR@10': '0.0569', 'NDCG@10': '0.0319', 'HR@20': '0.1000', 'NDCG@20': '0.0427'}
2026-10-29 15:34:15,518 - EarlyStopping counter: 5 out of 10
Mode_train:36: 100% 101/101 [00:02<00:00, 44.09it/s]
2026-10-29 15:34:17,888 - {'epoch': 36, 'rec_loss': '0.3956'}
Mode_test:36: 100% 5/5 [00:00<00:00, 24.78it/s]
2026-10-29 15:34:18,240 - {'Epoch': 36, 'HR@5': '0.0385', 'NDCG@5': '0.0249', 'HR@10': '0.0596', 'NDCG@10': '0.0318', 'HR@20': '0.1037', 'NDCG@20': '0.0428'}
2026-10-29 15:34:18,241 - EarlyStopping counter: 6 out of 10
Mode_train:37: 100% 101/101 [00:02<00:00, 47.24it/s]
2026-10-29 15:34:20,454 - {'epoch': 37, 'rec_loss': '0.3881'}
Mode_test:37: 100% 5/5 [00:00<00:00, 25.56it/s]
2026-10-29 15:34:20,781 - {'Epoch': 37, 'HR@5': '0.0431', 'NDCG@5': '0.0278', 'HR@10': '0.0670', 'NDCG@10': '0.0353', 'HR@20': '0.1110', 'NDCG@20': '0.0462'}
2026-10-29 15:34:20,782 - EarlyStopping counter: 7 out of 10
Mode_train:38: 100% 101/101 [00:02<00:00, 45.33it/s]
2026-10-29 15:34:23,085 - {'epoch': 38, 'rec_loss': '0.3863'}
Mode_test:38: 100% 5/5 [00:00<00:00, 22.72it/s]
2026-10-29 15:34:23,435 - {'Epoch': 38, 'HR@5': '0.0422', 'NDCG@5': '0.0253', 'HR@10': '0.0670', 'NDCG@10': '0.0334', 'HR@20': '0.1046', 'NDCG@20': '0.0429'}
2026-10-29 15:34:23,436 - EarlyStopping counter: 8 out of 10
Mode_train:39: 100% 101/101 [00:02<00:00, 46.05it/s]
2026-10-29 15:34:25,705 - {'epoch': 39, 'rec_loss': '0.3881'}
Mode_test:39: 100% 5/5 [00:00<00:00, 25.24it/s]
2026-10-29 15:34:26,030 - {'Epoch': 39, 'HR@5': '0.0440', 'NDCG@5': '0.0281', 'HR@10': '0.0743', 'NDCG@10': '0.0378', 'HR@20': '0.1092', 'NDCG@20': '0.0465'}
2026-10-29 15:34:26,031 - EarlyStopping counter: 9 out of 10
Mode_train:40: 100% 101/101 [00:02<00:00, 47.02it/s]
2026-10-29 15:34:28,259 - {'epoch': 40, 'rec_loss': '0.3821'}
Mode_test:40: 100% 5/5 [00:00<00:00, 23.93it/s]
2026-10-29 15:34:28,593 - {'Epoch': 40, 'HR@5': '0.0468', 'NDCG@5': '0.0313', 'HR@10': '0.0670', 'NDCG@10': '0.0378', 'HR@20': '0.1037', 'NDCG@20': '0.0469'}
2026-10-29 15:34:28,594 - EarlyStopping counter: 10 out of 10
2026-10-29 15:34:28,595 - Early stopping
2026-10-29 15:34:28,595 - ---------------Test Score---------------
Mode_test:0: 100% 5/5 [00:00<00:00, 25.33it/s]
2026-10-29 15:34:28,935 - {'Epoch': 0, 'HR@5': '0.0477', 'NDCG@5': '0.0334', 'HR@10': '0.0624', 'NDCG@10': '0.0381', 'HR@20': '0.0982', 'NDCG@20': '0.0472'}
2026-10-29 15:34:28,936 - SASRec_LastFM_final_s43
2026-10-29 15:34:28,936 - {'Epoch': 0, 'HR@5': '0.0477', 'NDCG@5': '0.0334', 'HR@10': '0.0624', 'NDCG@10': '0.0381', 'HR@20': '0.0982', 'NDCG@20': '0.0472'}

In [11]:
!python main.py --model_type SASRec --data_name LastFM --lr 0.001 --num_attention_heads 1 --seed 44 --train_name SASRec_LastFM_final_s44

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:424: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
2026-10-29 15:34:31,650 - Namespace(data_dir='./data/', output_dir='output/', data_name='LastFM', do_eval=False, load_model=None, train_name='SASRec_LastFM_final_s44', num_items=10, num_users=1091, lr=0.001, batch_size=256, epochs=200, no_cuda=False, log_freq=1, patience=10, num_workers=4, seed=44, weight_decay=0.0, adam_beta1=0.9, adam_beta2=0.999, gpu_id='0', variance=5, model_type='SASRec', max_seq_length=50, hidden_size=64, num_hidden_layers=2, hidden_act='gelu', num_attention_heads=1, attention_probs_dropout_prob=0.5, hidden_dropout_prob=0.5, initializer_range=0.02, cuda_condition=True, data_file='./data/LastFM.txt', item_size=3647, checkpoint_path='output/SASRec_LastFM_final_s44.pt', same_target_path='./data/LastFM_same_target.npy')
2026-10-29 15:34:31,662 - SASRecModel(
  (item_embeddings): Embedding(3647, 64, padding_idx=0)
  (position_embeddings): Embedding(50, 64)
  (LayerNorm): LayerNorm()
  (dropout): Dropout(p=0.5, inplace=False)
  (item_encoder): TransformerEncoder(
    (blocks): ModuleList(
      (0-1): 2 x TransformerBlock(
        (layer): MultiHeadAttention(
          (query): Linear(in_features=64, out_features=64, bias=True)
          (key): Linear(in_features=64, out_features=64, bias=True)
          (value): Linear(in_features=64, out_features=64, bias=True)
          (softmax): Softmax(dim=-1)
          (attn_dropout): Dropout(p=0.5, inplace=False)
          (dense): Linear(in_features=64, out_features=64, bias=True)
          (LayerNorm): LayerNorm((64,), eps=1e-12, elementwise_affine=True)
          (out_dropout): Dropout(p=0.5, inplace=False)
        )
        (feed_forward): FeedForward(
          (dense_1): Linear(in_features=64, out_features=256, bias=True)
          (dense_2): Linear(in_features=256, out_features=64, bias=True)
          (LayerNorm): LayerNorm()
          (dropout): Dropout(p=0.5, inplace=False)
        )
      )
    )
  )
)
2026-10-29 15:34:32,855 - Total Parameters: 336704
/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
Mode_train:0: 100% 101/101 [00:02<00:00, 39.50it/s]
2026-10-29 15:34:35,511 - {'epoch': 0, 'rec_loss': '1.3344'}
Mode_test:0: 100% 5/5 [00:00<00:00, 22.70it/s]
2026-10-29 15:34:35,855 - {'Epoch': 0, 'HR@5': '0.0174', 'NDCG@5': '0.0109', 'HR@10': '0.0303', 'NDCG@10': '0.0150', 'HR@20': '0.0523', 'NDCG@20': '0.0204'}
2026-10-29 15:34:35,856 - Validation score increased.  Saving model ...
Mode_train:1: 100% 101/101 [00:02<00:00, 46.90it/s]
2026-10-29 15:34:38,088 - {'epoch': 1, 'rec_loss': '1.2207'}
Mode_test:1: 100% 5/5 [00:00<00:00, 26.17it/s]
2026-10-29 15:34:38,407 - {'Epoch': 1, 'HR@5': '0.0156', 'NDCG@5': '0.0091', 'HR@10': '0.0294', 'NDCG@10': '0.0137', 'HR@20': '0.0596', 'NDCG@20': '0.0214'}
2026-10-29 15:34:38,408 - Validation score increased.  Saving model ...
Mode_train:2: 100% 101/101 [00:02<00:00, 45.94it/s]
2026-10-29 15:34:40,685 - {'epoch': 2, 'rec_loss': '1.1442'}
Mode_test:2: 100% 5/5 [00:00<00:00, 23.76it/s]
2026-10-29 15:34:41,029 - {'Epoch': 2, 'HR@5': '0.0165', 'NDCG@5': '0.0096', 'HR@10': '0.0321', 'NDCG@10': '0.0147', 'HR@20': '0.0587', 'NDCG@20': '0.0213'}
2026-10-29 15:34:41,030 - EarlyStopping counter: 1 out of 10
Mode_train:3: 100% 101/101 [00:02<00:00, 46.61it/s]
2026-10-29 15:34:43,266 - {'epoch': 3, 'rec_loss': '1.0853'}
Mode_test:3: 100% 5/5 [00:00<00:00, 26.73it/s]
2026-10-29 15:34:43,587 - {'Epoch': 3, 'HR@5': '0.0147', 'NDCG@5': '0.0091', 'HR@10': '0.0330', 'NDCG@10': '0.0150', 'HR@20': '0.0615', 'NDCG@20': '0.0221'}
2026-10-29 15:34:43,588 - Validation score increased.  Saving model ...
Mode_train:4: 100% 101/101 [00:02<00:00, 47.92it/s]
2026-10-29 15:34:45,781 - {'epoch': 4, 'rec_loss': '1.0266'}
Mode_test:4: 100% 5/5 [00:00<00:00, 27.11it/s]
2026-10-29 15:34:46,097 - {'Epoch': 4, 'HR@5': '0.0220', 'NDCG@5': '0.0128', 'HR@10': '0.0404', 'NDCG@10': '0.0188', 'HR@20': '0.0633', 'NDCG@20': '0.0245'}
2026-10-29 15:34:46,098 - Validation score increased.  Saving model ...
Mode_train:5: 100% 101/101 [00:02<00:00, 44.95it/s]
2026-10-29 15:34:48,430 - {'epoch': 5, 'rec_loss': '0.9759'}
Mode_test:5: 100% 5/5 [00:00<00:00, 26.84it/s]
2026-10-29 15:34:48,751 - {'Epoch': 5, 'HR@5': '0.0239', 'NDCG@5': '0.0147', 'HR@10': '0.0495', 'NDCG@10': '0.0233', 'HR@20': '0.0725', 'NDCG@20': '0.0291'}
2026-10-29 15:34:48,752 - Validation score increased.  Saving model ...
Mode_train:6: 100% 101/101 [00:02<00:00, 45.94it/s]
2026-10-29 15:34:51,039 - {'epoch': 6, 'rec_loss': '0.9267'}
Mode_test:6: 100% 5/5 [00:00<00:00, 25.87it/s]
2026-10-29 15:34:51,363 - {'Epoch': 6, 'HR@5': '0.0266', 'NDCG@5': '0.0164', 'HR@10': '0.0495', 'NDCG@10': '0.0236', 'HR@20': '0.0743', 'NDCG@20': '0.0298'}
2026-10-29 15:34:51,365 - Validation score increased.  Saving model ...
Mode_train:7: 100% 101/101 [00:02<00:00, 47.20it/s]
2026-10-29 15:34:53,602 - {'epoch': 7, 'rec_loss': '0.8782'}
Mode_test:7: 100% 5/5 [00:00<00:00, 27.25it/s]
2026-10-29 15:34:53,913 - {'Epoch': 7, 'HR@5': '0.0275', 'NDCG@5': '0.0176', 'HR@10': '0.0486', 'NDCG@10': '0.0243', 'HR@20': '0.0743', 'NDCG@20': '0.0306'}
2026-10-29 15:34:53,914 - Validation score increased.  Saving model ...
Mode_train:8: 100% 101/101 [00:02<00:00, 47.82it/s]
2026-10-29 15:34:56,102 - {'epoch': 8, 'rec_loss': '0.8279'}
Mode_test:8: 100% 5/5 [00:00<00:00, 25.31it/s]
2026-10-29 15:34:56,424 - {'Epoch': 8, 'HR@5': '0.0284', 'NDCG@5': '0.0168', 'HR@10': '0.0541', 'NDCG@10': '0.0250', 'HR@20': '0.0789', 'NDCG@20': '0.0312'}
2026-10-29 15:34:56,426 - Validation score increased.  Saving model ...
Mode_train:9: 100% 101/101 [00:02<00:00, 47.98it/s]
2026-10-29 15:34:58,616 - {'epoch': 9, 'rec_loss': '0.7877'}
Mode_test:9: 100% 5/5 [00:00<00:00, 24.15it/s]
2026-10-29 15:34:58,955 - {'Epoch': 9, 'HR@5': '0.0284', 'NDCG@5': '0.0196', 'HR@10': '0.0440', 'NDCG@10': '0.0245', 'HR@20': '0.0807', 'NDCG@20': '0.0337'}
2026-10-29 15:34:58,956 - Validation score increased.  Saving model ...
Mode_train:10: 100% 101/101 [00:02<00:00, 48.01it/s]
2026-10-29 15:35:01,142 - {'epoch': 10, 'rec_loss': '0.7464'}
Mode_test:10: 100% 5/5 [00:00<00:00, 25.04it/s]
2026-10-29 15:35:01,470 - {'Epoch': 10, 'HR@5': '0.0266', 'NDCG@5': '0.0170', 'HR@10': '0.0495', 'NDCG@10': '0.0245', 'HR@20': '0.0835', 'NDCG@20': '0.0329'}
2026-10-29 15:35:01,472 - EarlyStopping counter: 1 out of 10
Mode_train:11: 100% 101/101 [00:02<00:00, 46.60it/s]
2026-10-29 15:35:03,711 - {'epoch': 11, 'rec_loss': '0.7131'}
Mode_test:11: 100% 5/5 [00:00<00:00, 24.56it/s]
2026-10-29 15:35:04,051 - {'Epoch': 11, 'HR@5': '0.0294', 'NDCG@5': '0.0173', 'HR@10': '0.0550', 'NDCG@10': '0.0254', 'HR@20': '0.0881', 'NDCG@20': '0.0337'}
2026-10-29 15:35:04,052 - EarlyStopping counter: 2 out of 10
Mode_train:12: 100% 101/101 [00:02<00:00, 47.67it/s]
2026-10-29 15:35:06,249 - {'epoch': 12, 'rec_loss': '0.6836'}
Mode_test:12: 100% 5/5 [00:00<00:00, 25.49it/s]
2026-10-29 15:35:06,577 - {'Epoch': 12, 'HR@5': '0.0257', 'NDCG@5': '0.0159', 'HR@10': '0.0578', 'NDCG@10': '0.0260', 'HR@20': '0.0853', 'NDCG@20': '0.0329'}
2026-10-29 15:35:06,578 - EarlyStopping counter: 3 out of 10
Mode_train:13: 100% 101/101 [00:02<00:00, 48.28it/s]
2026-10-29 15:35:08,745 - {'epoch': 13, 'rec_loss': '0.6531'}
Mode_test:13: 100% 5/5 [00:00<00:00, 26.82it/s]
2026-10-29 15:35:09,059 - {'Epoch': 13, 'HR@5': '0.0284', 'NDCG@5': '0.0161', 'HR@10': '0.0514', 'NDCG@10': '0.0235', 'HR@20': '0.0872', 'NDCG@20': '0.0326'}
2026-10-29 15:35:09,060 - EarlyStopping counter: 4 out of 10
Mode_train:14: 100% 101/101 [00:02<00:00, 46.65it/s]
2026-10-29 15:35:11,303 - {'epoch': 14, 'rec_loss': '0.6245'}
Mode_test:14: 100% 5/5 [00:00<00:00, 24.87it/s]
2026-10-29 15:35:11,640 - {'Epoch': 14, 'HR@5': '0.0239', 'NDCG@5': '0.0137', 'HR@10': '0.0541', 'NDCG@10': '0.0233', 'HR@20': '0.0890', 'NDCG@20': '0.0321'}
2026-10-29 15:35:11,641 - EarlyStopping counter: 5 out of 10
Mode_train:15: 100% 101/101 [00:02<00:00, 46.37it/s]
2026-10-29 15:35:13,896 - {'epoch': 15, 'rec_loss': '0.6030'}
Mode_test:15: 100% 5/5 [00:00<00:00, 25.20it/s]
2026-10-29 15:35:14,226 - {'Epoch': 15, 'HR@5': '0.0284', 'NDCG@5': '0.0171', 'HR@10': '0.0477', 'NDCG@10': '0.0232', 'HR@20': '0.0798', 'NDCG@20': '0.0314'}
2026-10-29 15:35:14,227 - EarlyStopping counter: 6 out of 10
Mode_train:16: 100% 101/101 [00:02<00:00, 47.49it/s]
2026-10-29 15:35:16,424 - {'epoch': 16, 'rec_loss': '0.5802'}
Mode_test:16: 100% 5/5 [00:00<00:00, 24.46it/s]
2026-10-29 15:35:16,768 - {'Epoch': 16, 'HR@5': '0.0257', 'NDCG@5': '0.0145', 'HR@10': '0.0560', 'NDCG@10': '0.0244', 'HR@20': '0.0872', 'NDCG@20': '0.0322'}
2026-10-29 15:35:16,769 - EarlyStopping counter: 7 out of 10
Mode_train:17: 100% 101/101 [00:02<00:00, 46.44it/s]
2026-10-29 15:35:19,021 - {'epoch': 17, 'rec_loss': '0.5578'}
Mode_test:17: 100% 5/5 [00:00<00:00, 26.13it/s]
2026-10-29 15:35:19,350 - {'Epoch': 17, 'HR@5': '0.0303', 'NDCG@5': '0.0195', 'HR@10': '0.0578', 'NDCG@10': '0.0283', 'HR@20': '0.0963', 'NDCG@20': '0.0379'}
2026-10-29 15:35:19,351 - Validation score increased.  Saving model ...
Mode_train:18: 100% 101/101 [00:02<00:00, 45.52it/s]
2026-10-29 15:35:21,654 - {'epoch': 18, 'rec_loss': '0.5382'}
Mode_test:18: 100% 5/5 [00:00<00:00, 24.73it/s]
2026-10-29 15:35:21,991 - {'Epoch': 18, 'HR@5': '0.0330', 'NDCG@5': '0.0197', 'HR@10': '0.0505', 'NDCG@10': '0.0253', 'HR@20': '0.0890', 'NDCG@20': '0.0348'}
2026-10-29 15:35:21,992 - EarlyStopping counter: 1 out of 10
Mode_train:19: 100% 101/101 [00:02<00:00, 44.24it/s]
2026-10-29 15:35:24,351 - {'epoch': 19, 'rec_loss': '0.5289'}
Mode_test:19: 100% 5/5 [00:00<00:00, 25.35it/s]
2026-10-29 15:35:24,676 - {'Epoch': 19, 'HR@5': '0.0321', 'NDCG@5': '0.0195', 'HR@10': '0.0550', 'NDCG@10': '0.0270', 'HR@20': '0.1018', 'NDCG@20': '0.0386'}
2026-10-29 15:35:24,677 - Validation score increased.  Saving model ...
Mode_train:20: 100% 101/101 [00:02<00:00, 45.43it/s]
2026-10-29 15:35:26,982 - {'epoch': 20, 'rec_loss': '0.5149'}
Mode_test:20: 100% 5/5 [00:00<00:00, 26.54it/s]
2026-10-29 15:35:27,326 - {'Epoch': 20, 'HR@5': '0.0330', 'NDCG@5': '0.0207', 'HR@10': '0.0596', 'NDCG@10': '0.0292', 'HR@20': '0.0982', 'NDCG@20': '0.0388'}
2026-10-29 15:35:27,327 - Validation score increased.  Saving model ...
Mode_train:21: 100% 101/101 [00:02<00:00, 45.32it/s]
2026-10-29 15:35:29,639 - {'epoch': 21, 'rec_loss': '0.5026'}
Mode_test:21: 100% 5/5 [00:00<00:00, 26.88it/s]
2026-10-29 15:35:29,954 - {'Epoch': 21, 'HR@5': '0.0468', 'NDCG@5': '0.0281', 'HR@10': '0.0725', 'NDCG@10': '0.0362', 'HR@20': '0.1028', 'NDCG@20': '0.0437'}
2026-10-29 15:35:29,955 - Validation score increased.  Saving model ...
Mode_train:22: 100% 101/101 [00:02<00:00, 45.47it/s]
2026-10-29 15:35:32,266 - {'epoch': 22, 'rec_loss': '0.4838'}
Mode_test:22: 100% 5/5 [00:00<00:00, 25.30it/s]
2026-10-29 15:35:32,611 - {'Epoch': 22, 'HR@5': '0.0339', 'NDCG@5': '0.0219', 'HR@10': '0.0606', 'NDCG@10': '0.0306', 'HR@20': '0.0945', 'NDCG@20': '0.0393'}
2026-10-29 15:35:32,612 - EarlyStopping counter: 1 out of 10
Mode_train:23: 100% 101/101 [00:02<00:00, 44.39it/s]
2026-10-29 15:35:34,962 - {'epoch': 23, 'rec_loss': '0.4811'}
Mode_test:23: 100% 5/5 [00:00<00:00, 25.63it/s]
2026-10-29 15:35:35,290 - {'Epoch': 23, 'HR@5': '0.0367', 'NDCG@5': '0.0236', 'HR@10': '0.0633', 'NDCG@10': '0.0322', 'HR@20': '0.1000', 'NDCG@20': '0.0413'}
2026-10-29 15:35:35,291 - EarlyStopping counter: 2 out of 10
Mode_train:24: 100% 101/101 [00:02<00:00, 45.19it/s]
2026-10-29 15:35:37,609 - {'epoch': 24, 'rec_loss': '0.4691'}
Mode_test:24: 100% 5/5 [00:00<00:00, 26.90it/s]
2026-10-29 15:35:37,924 - {'Epoch': 24, 'HR@5': '0.0385', 'NDCG@5': '0.0241', 'HR@10': '0.0615', 'NDCG@10': '0.0314', 'HR@20': '0.0982', 'NDCG@20': '0.0406'}
2026-10-29 15:35:37,925 - EarlyStopping counter: 3 out of 10
Mode_train:25: 100% 101/101 [00:02<00:00, 48.48it/s]
2026-10-29 15:35:40,084 - {'epoch': 25, 'rec_loss': '0.4556'}
Mode_test:25: 100% 5/5 [00:00<00:00, 25.69it/s]
2026-10-29 15:35:40,407 - {'Epoch': 25, 'HR@5': '0.0367', 'NDCG@5': '0.0238', 'HR@10': '0.0606', 'NDCG@10': '0.0314', 'HR@20': '0.1028', 'NDCG@20': '0.0419'}
2026-10-29 15:35:40,408 - EarlyStopping counter: 4 out of 10
Mode_train:26: 100% 101/101 [00:02<00:00, 46.69it/s]
2026-10-29 15:35:42,654 - {'epoch': 26, 'rec_loss': '0.4515'}
Mode_test:26: 100% 5/5 [00:00<00:00, 22.71it/s]
2026-10-29 15:35:43,046 - {'Epoch': 26, 'HR@5': '0.0376', 'NDCG@5': '0.0232', 'HR@10': '0.0642', 'NDCG@10': '0.0315', 'HR@20': '0.0927', 'NDCG@20': '0.0388'}
2026-10-29 15:35:43,048 - EarlyStopping counter: 5 out of 10
Mode_train:27: 100% 101/101 [00:02<00:00, 47.49it/s]
2026-10-29 15:35:45,274 - {'epoch': 27, 'rec_loss': '0.4428'}
Mode_test:27: 100% 5/5 [00:00<00:00, 25.51it/s]
2026-10-29 15:35:45,607 - {'Epoch': 27, 'HR@5': '0.0349', 'NDCG@5': '0.0197', 'HR@10': '0.0624', 'NDCG@10': '0.0287', 'HR@20': '0.1000', 'NDCG@20': '0.0382'}
2026-10-29 15:35:45,608 - EarlyStopping counter: 6 out of 10
Mode_train:28: 100% 101/101 [00:02<00:00, 45.44it/s]
2026-10-29 15:35:47,897 - {'epoch': 28, 'rec_loss': '0.4337'}
Mode_test:28: 100% 5/5 [00:00<00:00, 23.46it/s]
2026-10-29 15:35:48,243 - {'Epoch': 28, 'HR@5': '0.0321', 'NDCG@5': '0.0200', 'HR@10': '0.0550', 'NDCG@10': '0.0275', 'HR@20': '0.0945', 'NDCG@20': '0.0373'}
2026-10-29 15:35:48,245 - EarlyStopping counter: 7 out of 10
Mode_train:29: 100% 101/101 [00:02<00:00, 47.43it/s]
2026-10-29 15:35:50,454 - {'epoch': 29, 'rec_loss': '0.4290'}
Mode_test:29: 100% 5/5 [00:00<00:00, 25.76it/s]
2026-10-29 15:35:50,782 - {'Epoch': 29, 'HR@5': '0.0339', 'NDCG@5': '0.0230', 'HR@10': '0.0615', 'NDCG@10': '0.0317', 'HR@20': '0.0972', 'NDCG@20': '0.0406'}
2026-10-29 15:35:50,783 - EarlyStopping counter: 8 out of 10
Mode_train:30: 100% 101/101 [00:02<00:00, 44.85it/s]
2026-10-29 15:35:53,110 - {'epoch': 30, 'rec_loss': '0.4308'}
Mode_test:30: 100% 5/5 [00:00<00:00, 23.04it/s]
2026-10-29 15:35:53,515 - {'Epoch': 30, 'HR@5': '0.0349', 'NDCG@5': '0.0214', 'HR@10': '0.0606', 'NDCG@10': '0.0295', 'HR@20': '0.1000', 'NDCG@20': '0.0392'}
2026-10-29 15:35:53,516 - EarlyStopping counter: 9 out of 10
Mode_train:31: 100% 101/101 [00:02<00:00, 48.17it/s]
2026-10-29 15:35:55,696 - {'epoch': 31, 'rec_loss': '0.4167'}
Mode_test:31: 100% 5/5 [00:00<00:00, 25.70it/s]
2026-10-29 15:35:56,019 - {'Epoch': 31, 'HR@5': '0.0330', 'NDCG@5': '0.0209', 'HR@10': '0.0541', 'NDCG@10': '0.0278', 'HR@20': '0.0991', 'NDCG@20': '0.0392'}
2026-10-29 15:35:56,020 - EarlyStopping counter: 10 out of 10
2026-10-29 15:35:56,020 - Early stopping
2026-10-29 15:35:56,020 - ---------------Test Score---------------
Mode_test:0: 100% 5/5 [00:00<00:00, 27.28it/s]
2026-10-29 15:35:56,348 - {'Epoch': 0, 'HR@5': '0.0541', 'NDCG@5': '0.0381', 'HR@10': '0.0697', 'NDCG@10': '0.0433', 'HR@20': '0.0945', 'NDCG@20': '0.0495'}
2026-10-29 15:35:56,349 - SASRec_LastFM_final_s44
2026-10-29 15:35:56,349 - {'Epoch': 0, 'HR@5': '0.0541', 'NDCG@5': '0.0381', 'HR@10': '0.0697', 'NDCG@10': '0.0433', 'HR@20': '0.0945', 'NDCG@20': '0.0495'}

## G. Ringkasan metrik test otomatis dari log

Sel ini mengambil metrik dari bagian `Test Score` di log—bukan dari metrik validasi tiap epoch. Jika suatu run belum ada atau gagal, namanya akan ditampilkan sebagai belum tersedia.

In [12]:
import re
import pandas as pd

METRICS = ['HR@5', 'NDCG@5', 'HR@10', 'NDCG@10', 'HR@20', 'NDCG@20']
PAPER = {
    'BSARec': [0.0523, 0.0344, 0.0807, 0.0435, 0.1174, 0.0526],
    'SASRec': [0.0413, 0.0284, 0.0633, 0.0355, 0.0927, 0.0429],
}
OUTPUT_DIR = SRC / 'output'

def read_final_test(model, seed):
    log_path = OUTPUT_DIR / f'{model}_LastFM_final_s{seed}.log'
    if not log_path.exists():
        return None
    log_text = log_path.read_text(encoding='utf-8', errors='ignore')
    marker = '---------------Test Score---------------'
    if marker not in log_text:
        return None
    final_section = log_text.rsplit(marker, 1)[-1]
    result = {}
    for metric in METRICS:
        pattern = re.compile(r"['\"]" + re.escape(metric) + r"['\"]\s*:\s*['\"]?([0-9]+\.[0-9]+)")
        found = pattern.findall(final_section)
        if not found:
            return None
        result[metric] = float(found[-1])
    return result

rows = []
missing = []
for model in ('BSARec', 'SASRec'):
    for seed in (42, 43, 44):
        result = read_final_test(model, seed)
        if result is None:
            missing.append(f'{model} seed {seed}')
            continue
        rows.append({'model': model, 'seed': seed, **result})

if missing:
    print('Run belum memiliki log Test Score:', ', '.join(missing))

if rows:
    detail = pd.DataFrame(rows)
    display(detail.sort_values(['model', 'seed']).round(4))
    summaries = []
    for model in ('BSARec', 'SASRec'):
        model_rows = detail[detail['model'] == model]
        if model_rows.empty:
            continue
        means = model_rows[METRICS].mean()
        stds = model_rows[METRICS].std(ddof=1)
        summary = pd.DataFrame({'Mean': means, 'Std': stds, 'Paper': PAPER[model]})
        summary['Gap vs paper (%)'] = (summary['Mean'] / summary['Paper'] - 1) * 100
        print(f'\n=== {model}: {len(model_rows)} completed seeds ===')
        display(summary.round(4))
        summary.insert(0, 'model', model)
        summary.insert(1, 'metric', summary.index)
        summaries.append(summary.reset_index(drop=True))
    detail.to_csv(OUTPUT_DIR / 'LastFM_final_test_by_seed.csv', index=False)
    if summaries:
        pd.concat(summaries, ignore_index=True).to_csv(OUTPUT_DIR / 'LastFM_final_test_summary.csv', index=False)
else:
    print('Belum ada hasil test yang bisa diringkas. Jalankan sel training dan pastikan log selesai.')

    model  seed    HR@5  NDCG@5   HR@10  NDCG@10   HR@20  NDCG@20
0  BSARec    42  0.0495  0.0333  0.0706   0.0402  0.1101   0.0502
1  BSARec    43  0.0477  0.0353  0.0771   0.0449  0.1147   0.0545
2  BSARec    44  0.0541  0.0356  0.0725   0.0414  0.1083   0.0503
3  SASRec    42  0.0450  0.0337  0.0642   0.0398  0.0881   0.0458
4  SASRec    43  0.0477  0.0334  0.0624   0.0381  0.0982   0.0472
5  SASRec    44  0.0541  0.0381  0.0697   0.0433  0.0945   0.0495

=== BSARec: 3 completed seeds ===

           Mean     Std   Paper  Gap vs paper (%)
HR@5     0.0504  0.0033  0.0523           -3.5692
NDCG@5   0.0347  0.0013  0.0344            0.9690
HR@10    0.0734  0.0033  0.0807           -9.0458
NDCG@10  0.0422  0.0024  0.0435           -3.0651
HR@20    0.1110  0.0033  0.1174           -5.4231
NDCG@20  0.0517  0.0025  0.0526           -1.7744

=== SASRec: 3 completed seeds ===

           Mean     Std   Paper  Gap vs paper (%)
HR@5     0.0489  0.0047  0.0413           18.4826
NDCG@5   0.0351  0.0026  0.0284           23.4742
HR@10    0.0654  0.0038  0.0633            3.3702
NDCG@10  0.0404  0.0027  0.0355           13.8028
HR@20    0.0936  0.0051  0.0927            0.9709
NDCG@20  0.0475  0.0019  0.0429           10.7226

## G.1 Perbandingan berpasangan antar-seed

Sel ini membandingkan BSARec dan SASRec pada seed yang sama. Delta positif berarti BSARec lebih tinggi. Dengan tiga seed, hasil ini deskriptif dan belum cukup untuk klaim signifikansi statistik atau generalisasi.

In [13]:
if 'detail' not in globals() or detail.empty:
    print('Tidak ada tabel metrik lengkap di memori. Jalankan sel ringkasan setelah enam log tersedia.')
else:
    expected_models = {'BSARec', 'SASRec'}
    assert set(detail['model']) == expected_models
    assert sorted(detail['seed'].unique().tolist()) == [42, 43, 44]
    assert len(detail) == 6 and not detail.duplicated(['model', 'seed']).any()
    paired_rows = []
    for metric in METRICS:
        deltas = []
        for seed in (42, 43, 44):
            b = float(detail.loc[(detail['model'] == 'BSARec') & (detail['seed'] == seed), metric].iloc[0])
            s = float(detail.loc[(detail['model'] == 'SASRec') & (detail['seed'] == seed), metric].iloc[0])
            deltas.append(b - s)
        paired_rows.append({
            'metric': metric, 'mean_delta_BSARec_minus_SASRec': sum(deltas) / len(deltas),
            'BSARec_wins': sum(x > 0 for x in deltas), 'ties': sum(x == 0 for x in deltas),
            'SASRec_wins': sum(x < 0 for x in deltas),
        })
    paired = pd.DataFrame(paired_rows)
    display(paired.round(5))
    paired.to_csv(OUTPUT_DIR / 'LastFM_paired_seed_deltas.csv', index=False)

    metric  mean_delta_BSARec_minus_SASRec  BSARec_wins  ties  SASRec_wins
0     HR@5                         0.00150            1     2            0
1   NDCG@5                        -0.00033            1     0            2
2    HR@10                         0.00797            3     0            0
3  NDCG@10                         0.00177            2     0            1
4    HR@20                         0.01743            3     0            0
5  NDCG@20                         0.00417            3     0            0

## 1. Arsip artefak ke Google Drive

**Status saat salinan ini dibuat: BELUM DIEKSEKUSI.** Jalankan di runtime Colab yang masih memiliki keenam log/checkpoint dan file CSV/JSON. Sel membuat satu folder Drive, menyalin hanya artefak yang diminta (tanpa data mentah atau `LastFM*.txt`), lalu menulis SHA-256 semua file yang disalin ke `ARTIFACTS_SHA256.txt`. File checksum tidak memasukkan dirinya sendiri.

In [ ]:
from google.colab import drive
from datetime import datetime
import hashlib, shutil
from pathlib import Path
drive.mount('/content/drive')

RUN_PREFIXES = [f'BSARec_LastFM_final_s{s}' for s in (42, 43, 44)] + [f'SASRec_LastFM_final_s{s}' for s in (42, 43, 44)]
repo_files = [p for p in REPO.rglob('*') if p.is_file()]
archive_sources = []
for _prefix in RUN_PREFIXES:
    _logs = sorted(p for p in repo_files if p.name.startswith(_prefix) and p.suffix.lower() == '.log')
    _checkpoints = sorted(p for p in repo_files if p.name.startswith(_prefix) and p.suffix.lower() == '.pt')
    assert _logs, f'Log .log tidak ditemukan untuk {_prefix}'
    assert _checkpoints, f'Checkpoint .pt tidak ditemukan untuk {_prefix}'
    archive_sources.extend(_logs)
    archive_sources.extend(_checkpoints)

for _name in (
    'LastFM_final_test_by_seed.csv',
    'LastFM_final_test_summary.csv',
    'LastFM_paired_seed_deltas.csv',
):
    _path = OUTPUT_DIR / _name
    assert _path.is_file(), f'CSV wajib tidak ditemukan: {_path}'
    archive_sources.append(_path)
for _name in (
    'LastFM_preprocessing_manifest.json',
    'LastFM_user2id.json',
    'LastFM_artist2id.json',
):
    _path = DATA_OUT / _name
    assert _path.is_file(), f'JSON wajib tidak ditemukan: {_path}'
    archive_sources.append(_path)

# Hindari duplikasi nama/sumber dan jangan pernah menyalin file sequence atau raw data.
archive_sources = sorted({p.resolve(): p for p in archive_sources}.values(), key=lambda p: p.name)
assert not any(p.name.startswith('LastFM') and p.suffix.lower() == '.txt' for p in archive_sources), 'File LastFM*.txt tidak boleh masuk arsip.'
DRIVE_ARCHIVE_PATH = Path('/content/drive/MyDrive') / ('BSARec_LastFM_Artifacts_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
DRIVE_ARCHIVE_PATH.mkdir(parents=True, exist_ok=False)
copied_files = []
for _src in archive_sources:
    _target = DRIVE_ARCHIVE_PATH / _src.name
    if _target.exists():
        _target = DRIVE_ARCHIVE_PATH / f'{_src.parent.name}_{_src.name}'
    shutil.copy2(_src, _target)
    copied_files.append(_target)

def _sha256(path):
    digest = hashlib.sha256()
    with open(path, 'rb') as f:
        for block in iter(lambda: f.read(1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()

_hash_lines = [f'{_sha256(p)}  {p.name}' for p in copied_files]
CHECKSUM_FILE = DRIVE_ARCHIVE_PATH / 'ARTIFACTS_SHA256.txt'
CHECKSUM_FILE.write_text('\n'.join(_hash_lines) + '\n', encoding='utf-8')
print('Folder Drive:', DRIVE_ARCHIVE_PATH)
print('Jumlah file yang disalin dan di-hash:', len(archive_sources))
print('Daftar checksum:', CHECKSUM_FILE)

## 2. Runtime info

**Status saat salinan ini dibuat: BELUM DIEKSEKUSI.** Sel ini harus dijalankan setelah training dalam runtime/repository yang sama untuk mengaitkan metadata ke run lama. Pada runtime baru, hasil hanya mendeskripsikan lingkungan saat audit dijalankan.

In [ ]:
import json, platform, subprocess, sys
from importlib.metadata import version, PackageNotFoundError
import torch
EXPECTED_AUDIT_COMMIT = 'c80bdc0f1a889b78fe9a27e2058389cc84caea84'

def _git(args):
    r = subprocess.run(['git', '-C', str(REPO), *args], capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f'git {args} gagal: {r.stderr}')
    return r.stdout.strip()

_HEAD = _git(['rev-parse', 'HEAD'])
_STATUS = _git(['status', '--porcelain'])
_versions = {}
for _pkg in ('torch', 'numpy', 'pandas', 'scipy'):
    try:
        _versions[_pkg] = version(_pkg)
    except PackageNotFoundError:
        _versions[_pkg] = 'not-installed'
_HEAD_COMPARISON = 'SAMA' if _HEAD == EXPECTED_AUDIT_COMMIT else 'BERBEDA'
runtime_info = {
    'git_head': _HEAD,
    'expected_audit_commit': EXPECTED_AUDIT_COMMIT,
    'head_comparison': _HEAD_COMPARISON,
    'git_dirty': bool(_STATUS),
    'git_status_porcelain': _STATUS,
    'python_version': platform.python_version(),
    'package_versions': _versions,
    'gpu_name': torch.cuda.get_device_name(0) if torch.cuda.is_available() else None,
}
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
RUNTIME_INFO_FILE = OUTPUT_DIR / 'LastFM_runtime_info.json'
RUNTIME_INFO_FILE.write_text(json.dumps(runtime_info, ensure_ascii=False, indent=2), encoding='utf-8')
print(json.dumps(runtime_info, ensure_ascii=False, indent=2))
print('Disimpan ke:', RUNTIME_INFO_FILE)
print('HEAD vs commit audit:', _HEAD_COMPARISON)

## 3. Statistik timestamp

**Status saat salinan ini dibuat: BELUM DIEKSEKUSI.** Sel berikut menghitung gap bertetangga, gap nonpositif, timestamp pasangan bertetangga yang sama, serta jumlah nilai unik dan lima residu terbanyak dari timestamp modulo satu hari dalam milidetik.

In [ ]:
from collections import Counter
DAY_MS = 86_400_000
_time_rows = [np.asarray(ts, dtype=np.int64) for ts in time_sequences.values()]
_timestamp_values_ms = np.concatenate(_time_rows)
_gap_values_ms = np.concatenate([np.diff(ts) for ts in _time_rows if len(ts) > 1])
_timestamp_residues = np.remainder(_timestamp_values_ms, DAY_MS)
_residue_counts = Counter(map(int, _timestamp_residues))

timestamp_stats = {
    'total_gap': int(_gap_values_ms.size),
    'gap_le_zero_count': int(np.count_nonzero(_gap_values_ms <= 0)),
    'gap_le_zero_pct': float(np.mean(_gap_values_ms <= 0) * 100),
    'equal_adjacent_count': int(np.count_nonzero(_gap_values_ms == 0)),
    'equal_adjacent_pct': float(np.mean(_gap_values_ms == 0) * 100),
    'unique_day_residues': len(_residue_counts),
    'top5_day_residues': _residue_counts.most_common(5),
}
print(f"Total gap bertetangga: {timestamp_stats['total_gap']:,}")
print(f"Gap <= 0: {timestamp_stats['gap_le_zero_count']:,} ({timestamp_stats['gap_le_zero_pct']:.4f}%)")
print(f"Pasangan bertetangga dengan timestamp sama: {timestamp_stats['equal_adjacent_count']:,} ({timestamp_stats['equal_adjacent_pct']:.4f}%)")
print(f"Jumlah nilai unik timestamp modulo satu hari: {timestamp_stats['unique_day_residues']:,}")
print('Lima residu terbanyak (residu_ms, frekuensi):', timestamp_stats['top5_day_residues'])

Jika output sel 3 menunjukkan mayoritas gap bernilai nol, pasangan item dengan timestamp sama tidak memiliki urutan waktu yang dapat dibedakan: stable sort mempertahankan urutan baris file sumber. Ini mengikuti prosedur S3Rec. Karena timestamp file ini adalah waktu pemberian tag artis, bukan waktu scrobble/mendengarkan, LastFM kurang cocok sebagai dataset utama untuk eksperimen time-aware; MovieLens-1M lebih sesuai bila timestamp rating yang dibutuhkan. Kesimpulan ini adalah interpretasi semantik data, bukan hasil perbandingan model notebook.

## 4. Verifikasi loss pada commit audit

**Status saat salinan ini dibuat: BELUM DIEKSEKUSI.** Sel memakai `git show` pada commit audit yang tercatat, lalu mencetak hanya fungsi `calculate_loss` dari kedua file model.

Interpretasi setelah output terverifikasi: BSARec menggunakan cross-entropy multi-kelas pada skor seluruh item; SASRec menggunakan binary cross-entropy pada item positif dan negatif sampel. Jadi selisih hasil adalah perbandingan implementasi repo dengan objective training yang berbeda, bukan efek arsitektur murni.

In [ ]:
import ast, subprocess
AUDIT_COMMIT = 'c80bdc0f1a889b78fe9a27e2058389cc84caea84'
LOSS_FILES = [
    ('BSARec', 'src/model/bsarec.py', 'BSARecModel'),
    ('SASRec', 'src/model/sasrec.py', 'SASRecModel'),
]
loss_audit = {}
for _label, _relative_path, _class_name in LOSS_FILES:
    _show = subprocess.run(
        ['git', '-C', str(REPO), 'show', f'{AUDIT_COMMIT}:{_relative_path}'],
        capture_output=True, text=True
    )
    if _show.returncode != 0:
        raise RuntimeError(f'git show gagal untuk {_relative_path}: {_show.stderr}')
    _source = _show.stdout
    _tree = ast.parse(_source)
    _cls = next((n for n in _tree.body if isinstance(n, ast.ClassDef) and n.name == _class_name), None)
    assert _cls is not None, f'Class {_class_name} tidak ditemukan di {_relative_path}@{AUDIT_COMMIT}'
    _fn = next((n for n in _cls.body if isinstance(n, ast.FunctionDef) and n.name == 'calculate_loss'), None)
    assert _fn is not None, f'calculate_loss tidak ditemukan di {_relative_path}@{AUDIT_COMMIT}'
    _snippet = ast.get_source_segment(_source, _fn)
    assert _snippet
    loss_audit[_label] = _snippet
    print(f'===== {_label}: calculate_loss dari {AUDIT_COMMIT}:{_relative_path} =====')
    print(_snippet)

## 5. Granularitas noise HR

**Status saat salinan ini dibuat: BELUM DIEKSEKUSI.** Satu target test per user membuat resolusi HR sebesar `1/n_test`. Sel ini menghitung selisih mean BSARec−SASRec dalam ekuivalen user, delta per seed, serta sample SD delta antar-seed dalam ekuivalen user. Nilai user-equivalent bersifat perkiraan karena log metrik telah dibulatkan.

In [ ]:
assert 'detail' in globals() and len(detail) == 6, 'Jalankan sel G agar enam hasil log tersedia.'
assert set(detail['model']) == {'BSARec', 'SASRec'}
assert sorted(detail['seed'].unique().tolist()) == [42, 43, 44]
assert not detail.duplicated(['model', 'seed']).any()
n_test = sum(1 for items in item_sequences.values() if len(items) >= 3)
assert n_test > 0
print('n_test (jumlah user/target test):', n_test)
print(f'Resolusi HR terkecil 1/n_test: {1/n_test:.8f} ({100/n_test:.6f} percentage point)')
hr_noise_rows = []
for _metric in ('HR@5', 'HR@10', 'HR@20'):
    _b = detail.loc[detail['model']=='BSARec'].set_index('seed')[_metric].sort_index()
    _s = detail.loc[detail['model']=='SASRec'].set_index('seed')[_metric].sort_index()
    assert list(_b.index) == list(_s.index) == [42, 43, 44]
    _delta = (_b - _s) * n_test
    hr_noise_rows.append({
        'metric': _metric,
        'mean_delta_user_equivalent': float(_delta.mean()),
        'delta_seed42_users': float(_delta.loc[42]),
        'delta_seed43_users': float(_delta.loc[43]),
        'delta_seed44_users': float(_delta.loc[44]),
        'sample_SD_delta_across_seeds_users': float(_delta.std(ddof=1)),
    })
hr_noise = pd.DataFrame(hr_noise_rows)
display(hr_noise.round(4))

## 6. Diagnostik epoch dan early stopping

**Status saat salinan ini dibuat: BELUM DIEKSEKUSI.** Parser membatasi diri pada teks sebelum `---------------Test Score---------------`; baris `Epoch 0` test tidak ikut masuk. Ia melaporkan epoch validasi terakhir, semua epoch yang tie pada maksimum NDCG@20 setelah pembulatan log, skor tersebut, rec_loss terakhir, dan epoch penyimpanan checkpoint dari pesan early stopping.

In [ ]:
import ast, re
DIAGNOSTIC_RUNS = [(model, seed) for model in ('BSARec', 'SASRec') for seed in (42, 43, 44)]
TEST_MARKER = '---------------Test Score---------------'

def _parse_training_log(log_path):
    assert log_path.is_file(), f'Log tidak ditemukan: {log_path}'
    text = log_path.read_text(encoding='utf-8', errors='replace')
    assert TEST_MARKER in text, f'Penanda Test Score tidak ditemukan: {log_path}'
    before_test = text.split(TEST_MARKER, 1)[0]
    validation, losses, saved_epochs, counters = [], [], [], []
    current_validation_epoch = None
    for line in before_test.splitlines():
        match = re.search(r'(\{[^{}]*\})', line)
        if match:
            try:
                record = ast.literal_eval(match.group(1))
            except (ValueError, SyntaxError):
                record = None
            if isinstance(record, dict) and 'Epoch' in record and 'NDCG@20' in record:
                current_validation_epoch = int(record['Epoch'])
                validation.append(record)
            elif isinstance(record, dict) and 'epoch' in record and 'rec_loss' in record:
                losses.append(record)
        if 'Validation score increased' in line and current_validation_epoch is not None:
            saved_epochs.append(current_validation_epoch)
        counter_match = re.search(r'EarlyStopping counter: (\d+) out of (\d+)', line)
        if counter_match and current_validation_epoch is not None:
            counters.append((current_validation_epoch, int(counter_match.group(1)), int(counter_match.group(2))))
    assert validation, f'Tidak ada baris validasi pre-test di {log_path}'
    assert losses, f'Tidak ada rec_loss pre-test di {log_path}'
    best_printed = max(float(r['NDCG@20']) for r in validation)
    best_epochs_printed = [int(r['Epoch']) for r in validation if float(r['NDCG@20']) == best_printed]
    return {
        'last_epoch': int(validation[-1]['Epoch']),
        'best_rounded_epoch_first': best_epochs_printed[0],
        'best_rounded_epochs_tied': best_epochs_printed,
        'best_ndcg20_logged': best_printed,
        'last_rec_loss_epoch': int(losses[-1]['epoch']),
        'last_rec_loss': losses[-1]['rec_loss'],
        'last_checkpoint_saved_epoch': saved_epochs[-1] if saved_epochs else None,
        'last_earlystop_counter': counters[-1] if counters else None,
        'saved_epochs': saved_epochs,
        'counter_events': counters,
    }

diagnostic_rows = []
for _model, _seed in DIAGNOSTIC_RUNS:
    _prefix = f'{_model}_LastFM_final_s{_seed}'
    _result = _parse_training_log(OUTPUT_DIR / f'{_prefix}.log')
    diagnostic_rows.append({'model': _model, 'seed': _seed, **_result})
    print(f"{_prefix}: last_epoch={_result['last_epoch']}; rounded_best_NDCG@20_epoch(s)={_result['best_rounded_epochs_tied']}; score={_result['best_ndcg20_logged']}; last_rec_loss(epoch={_result['last_rec_loss_epoch']})={_result['last_rec_loss']}; checkpoint_saved_epoch={_result['last_checkpoint_saved_epoch']}; last_counter={_result['last_earlystop_counter']}")
diagnostic = pd.DataFrame(diagnostic_rows)

_s42 = next(r for r in diagnostic_rows if r['model']=='BSARec' and r['seed']==42)
if len(_s42['best_rounded_epochs_tied']) > 1 and _s42['last_checkpoint_saved_epoch'] in _s42['best_rounded_epochs_tied']:
    _last_saved = _s42['last_checkpoint_saved_epoch']
    _later_counters = [x for x in _s42['counter_events'] if x[0] > _last_saved]
    print('BSARec seed 42: nilai NDCG@20 pada log dibulatkan sehingga beberapa epoch dapat tampak tie; pesan "Validation score increased" menunjukkan perbandingan internal presisi penuh menyimpan checkpoint pada epoch yang lebih akhir. Counter patience dimulai ulang setelah simpan itu; baris counter setelahnya menjelaskan epoch berhenti.')
    print('Epoch counter setelah checkpoint terakhir:', [(e, c, p) for e, c, p in _later_counters])
else:
    print('BSARec seed 42: pola tie/checkpoint tidak terkonfirmasi oleh log yang tersedia; jangan gunakan penjelasan tie pembulatan.')

## H. Interpretasi dan batas klaim untuk presentasi

- **Data:** GroupLens HetRec 2011 Last.fm 2K; hasil 1.090 user, 3.646 artis, 52.551 interaksi. Sel audit D.1 membandingkan setiap sequence terurut dan mapping ID dengan implementasi preprocessing rujukan, bukan hanya mencocokkan jumlah total. Lokasi manifest dan mapping: folder Google Drive yang dicetak sel 1 setelah arsip berhasil dibuat.
- **Protokol:** validasi menargetkan item kedua terakhir, test menargetkan item terakhir, dan evaluasi full-item memakai mask interaksi sebelumnya sesuai kode resmi BSARec. Hasil enam run memakai seed 42/43/44; jangan campur log run pemetaan lama.
- **Hasil:** laporkan semua seed, mean ± sample SD, dan gap paper sebagai perbandingan deskriptif. Paper bukan distribusi tiga seed, jadi gap bukan uji signifikansi. SASRec di notebook ini adalah baseline yang dijalankan dengan konfigurasi yang dinyatakan, bukan klaim reproduksi semua konfigurasi SASRec di paper.
- **Perbandingan model:** gunakan tabel paired seed di G.1. Hindari klaim umum “BSARec selalu lebih baik”; simpulkan per metrik dan jumlah seed yang menang/seri.
- **Timestamp:** timestamp adalah waktu pemberian tag artis, bukan waktu mendengar musik. Model vanilla tidak mengonsumsi file timestamp/gap, jadi hasil ini bukan eksperimen temporal.
- **Reproduksibilitas kode:** manifest merekam commit/hash saat audit dijalankan. Output training yang tersimpan belum merekam commit repo; bila audit tidak dijalankan pada runtime training yang sama, commit run lama tetap tidak terverifikasi. W&B opsional untuk kurva/log terpusat, bukan syarat agar metrik valid.

- **Perbandingan per metrik:** sel H.1 menghitung jumlah seed menang/seri per metrik berdasarkan G.1, menampilkan selisih HR dalam satuan user beserta variasi antar-seed, lalu menyusun kesimpulan hanya jika didukung output. Jangan menyatakan BSARec selalu lebih baik.
- **Gap paper:** tabel G menunjukkan arah deviasi untuk SASRec dan BSARec. Perlakukan gap sebagai deskriptif; versi library, GPU, dan seed adalah kemungkinan penyebab yang belum diuji.
- **Loss:** pakai caveat objective pada output sel 4; jangan mengatribusikan seluruh selisih ke arsitektur saja.
- **Timestamp:** pakai statistik residu dan gap pada output sel 3. Jika mayoritas gap nol, tie mengikuti urutan baris file karena stable sort sesuai prosedur S3Rec; timestamp tag bukan waktu mendengar sehingga LastFM kurang cocok sebagai dataset utama time-aware.
- **Early stopping:** pakai output sel 6. Bila skor NDCG@20 tercetak tie setelah pembulatan tetapi pesan `Validation score increased` muncul pada epoch berikutnya, penjelasan harus membedakan skor log yang dibulatkan dan skor internal yang dibandingkan early stopping.

In [ ]:
# Narasi H dihitung hanya dari output G, G.1, dan sel analisis 2-6 yang benar-benar dijalankan.
assert 'detail' in globals() and len(detail) == 6, 'Jalankan sel G terlebih dahulu.'
assert 'timestamp_stats' in globals(), 'Jalankan sel 3 terlebih dahulu.'
assert 'loss_audit' in globals(), 'Jalankan sel 4 terlebih dahulu.'
assert 'hr_noise' in globals(), 'Jalankan sel 5 terlebih dahulu.'
assert 'diagnostic' in globals() and len(diagnostic) == 6, 'Jalankan sel 6 terlebih dahulu.'

print('=== Perbandingan berpasangan per metrik ===')
paired_outcomes = {}
for _metric in METRICS:
    _d = []
    for _seed in (42, 43, 44):
        _b = float(detail.loc[(detail['model'] == 'BSARec') & (detail['seed'] == _seed), _metric].iloc[0])
        _s = float(detail.loc[(detail['model'] == 'SASRec') & (detail['seed'] == _seed), _metric].iloc[0])
        _d.append(_b - _s)
    _wins, _ties, _losses = sum(x > 0 for x in _d), sum(x == 0 for x in _d), sum(x < 0 for x in _d)
    paired_outcomes[_metric] = (_wins, _ties, _losses, float(np.mean(_d)))
    print(f"{_metric}: BSARec menang {_wins}, seri {_ties}, SASRec menang {_losses} dari tiga seed; mean delta={np.mean(_d):+.6f}.")
    if _metric.startswith('HR@'):
        _nr = hr_noise.loc[hr_noise['metric'] == _metric].iloc[0]
        print(f"  Mean delta={float(_nr['mean_delta_user_equivalent']):+.3f} user; per seed 42/43/44={float(_nr['delta_seed42_users']):+.3f}/{float(_nr['delta_seed43_users']):+.3f}/{float(_nr['delta_seed44_users']):+.3f} user; SD delta antar-seed={float(_nr['sample_SD_delta_across_seeds_users']):.3f} user.")
if paired_outcomes['HR@20'][0] == 3 and paired_outcomes['NDCG@20'][0] == 3:
    print('BSARec konsisten unggul di HR@20 dan NDCG@20 pada ketiga seed.')
if paired_outcomes['HR@10'][0] == 3:
    print('HR@10 searah: BSARec lebih tinggi pada ketiga seed.')
_hr5 = hr_noise.loc[hr_noise['metric'] == 'HR@5'].iloc[0]
if abs(float(_hr5['mean_delta_user_equivalent'])) <= float(_hr5['sample_SD_delta_across_seeds_users']):
    print('HR@5 setara dalam noise pada tiga seed ini: mean delta user tidak melebihi SD delta antar-seed.')
else:
    print('HR@5: tampilkan mean delta user dan SD antar-seed tanpa menyebut setara dalam noise.')
print('NDCG@5 tetap dilaporkan dengan jumlah seed menang/seri dan mean delta di atas; interpretasinya deskriptif.')

print('=== Perbandingan terhadap angka paper (deskriptif) ===')
paper_gaps = {}
for _model in ('BSARec', 'SASRec'):
    _mean = detail.loc[detail['model'] == _model, METRICS].mean()
    _paper = pd.Series(PAPER[_model], index=METRICS)
    _gap = (_mean / _paper - 1) * 100
    paper_gaps[_model] = _gap
    print(f"{_model} gap per metrik (%): " + ', '.join(f"{m}={_gap[m]:+.2f}%" for m in METRICS))
if all(float(x) > 0 for x in paper_gaps['SASRec']) and sum(float(x) < 0 for x in paper_gaps['BSARec']) >= 5:
    print('SASRec berada di atas angka paper pada semua metrik, sedangkan BSARec sedikit di bawah pada mayoritas metrik.')
print('Kedua perbandingan bersifat deskriptif; penyebab deviasi belum diuji.')

print('=== Caveat objective loss ===')
print('BSARec: CrossEntropy multi-kelas atas skor seluruh item, sesuai calculate_loss yang dicetak pada sel 4.')
print('SASRec: BCE-with-logits pada item positif dan negatif sampel, sesuai calculate_loss yang dicetak pada sel 4.')
print('Objective training berbeda, jadi hasil bukan perbandingan efek arsitektur murni.')

print('=== Caveat timestamp ===')
print(f"Total gap={timestamp_stats['total_gap']:,}; gap <= 0={timestamp_stats['gap_le_zero_count']:,} ({timestamp_stats['gap_le_zero_pct']:.4f}%); pasangan timestamp sama={timestamp_stats['equal_adjacent_count']:,} ({timestamp_stats['equal_adjacent_pct']:.4f}%); residu harian unik={timestamp_stats['unique_day_residues']:,}; lima residu teratas={timestamp_stats['top5_day_residues']}.")
if timestamp_stats['equal_adjacent_pct'] > 50:
    print('Sebagian besar gap bernilai 0; urutan item dengan timestamp sama mengikuti urutan baris file lewat stable sort sesuai prosedur S3Rec. Timestamp tag bukan waktu mendengar, sehingga LastFM kurang cocok untuk eksperimen time-aware.')
else:
    print('Timestamp tag bukan waktu mendengar; gunakan statistik gap/residu di atas untuk membatasi klaim time-aware.')

_s42 = diagnostic.loc[(diagnostic['model'] == 'BSARec') & (diagnostic['seed'] == 42)].iloc[0]
print('=== Early stopping BSARec seed 42 ===')
print('Epoch validasi terakhir=', _s42['last_epoch'], '; epoch dengan NDCG@20 tercetak terbaik=', _s42['best_rounded_epochs_tied'], '; skor tercetak=', _s42['best_ndcg20_logged'], '; epoch checkpoint terakhir disimpan=', _s42['last_checkpoint_saved_epoch'], '; counter terakhir=', _s42['last_earlystop_counter'])
print('Jika skor tercetak tie tetapi pesan "Validation score increased" muncul pada epoch sesudahnya, skor internal berpresisi penuh membaik dan counter di-reset saat checkpoint disimpan. Epoch berhenti dihitung dari checkpoint terakhir, bukan tie pertama pada log yang dibulatkan.')

## Referensi

- Paper BSARec, AAAI 2024: https://ojs.aaai.org/index.php/AAAI/article/view/28747
- Implementasi resmi BSARec: https://github.com/yehjin-shin/BSARec
- Split dan pemuatan data BSARec: https://github.com/yehjin-shin/BSARec/blob/main/src/dataset.py
- Evaluasi full-item BSARec: https://github.com/yehjin-shin/BSARec/blob/main/src/trainers.py
- Dataset HetRec 2011 Last.fm 2K, GroupLens: https://grouplens.org/datasets/hetrec-2011/
- Preprocessing LastFM rujukan (deduplikasi, timestamp order, 5-core, mapping ID): https://github.com/RUCAIBox/CIKM2020-S3Rec/blob/master/data/data_process.py

- Source model pada commit audit: `git show c80bdc0f1a889b78fe9a27e2058389cc84caea84:src/model/bsarec.py` dan `...:src/model/sasrec.py`.
- MovieLens-1M, GroupLens: https://grouplens.org/datasets/movielens/1m/